feature_means: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCAAAADU5MzMxNDg4cQJYAwAAAGNwdXEDTU0GTnRxBFEugAJdcQBYCAAAADU5MzMxNDg4
    cQFhLk0GAAAAAAAAlVS1QXSriUFEqqw8O9dLPs5NFkL5lR1AP0mbQM5NFkIFoac/Uq+IQDqGi0Cf
    8iE+Yq0fQGGKFERUgZNBQ//eQC8TmEHlhp1B+CZBQgvK5UEAAAAA53qZO+Ch9kDmg5xBAAAAAJMh
    qEE375NAhGnwPwbilT4AAAAA/BEmP9XUVz6WEiM9WzhmPD3RaT9vJdNDGGrUQ8P8GUQXXBVEUvEM
    RDvSAkTL9/VDicnbQ5y1t0OQMC1DEalYQ7IFqEMb+bdDkiSxQ0E5qkNp859DavCSQ3BPgUN59GZD
    QkoqQ/WImEPkJq1DIXm5Q2UYsENekKlDYfKgQ84tj0Pd8K5E8JC0RGpQBUX6XQ9FDZ4KRWK3AkWS
    B/pEmUPoRPWVykSwv7JFFgmuRQ4K/kW3VgVGAv7+RZa+70Xh3uRFrPXTRZOOt0VPWzNGmQNgRtjT
    okahdbJGMHSsRu/XpUZzxJ5GH5iSRoNDgEavFL1DlNvJQymqKUSWklNEoM9eRPyUWESEXE1E3AtF
    RM+GNUT0iZtDvhWqQ9teDUQ7By5E3RM2RDFxMETAqSdEkzYgRNHaEkTKqZlDc0emQ9vxCkQNRCtE
    lZEzRLAQLkQxWiVEwv8dRO/gEETYGZ1CRp3CQvgzEEN7fyJD4KQfQ7q7GUMrXRNDMTwKQwvn9EJ3
    MvZF+HXtRbhDUEZ41oVGb+yPRs/PjEbs44RGoLGARo/0b0ZJSA1BHCwGQZ/u6UCzd7VAEs6hQGWS
    mEAxUZZAHLCKQD+AdEAcH2dAVpKHQLQGfECBf1tASmNIQBYpREAjakFA5t42QDqUK0ANPZlAg0tW
    QGcwZED8DE9AC9dRQNocS0CK3E5Aw2JMQB2BQ0AfVO1BVyviQVYcyUHvB61BXCKfQSKUmEFuBJlB
    ln2TQd2ZiUEOxPNCljraQk0JwEIdcKFCMeaSQk1ajEKHW4xCjeiGQm+8eUJDw29DAzmMQyL1dENK
    3lVDIg1EQx4gQEMC0EBDlc43QzaLK0O0wPpADYL7QHAO/EAbB/pAtIn5QNhA+EDmm/hAoVH3QPz6
    9UDIcc5A4QfUQEU90kC47c1A9UDMQIRwykCQActAQSPJQCnQxkCm4ctAG0fPQAuLzkCTkspAT1zJ
    QKahx0CtKchAmFTGQJAgxEBxLdI/wHDzP4+32D8OWMI/Qii1P0oAsj/sALM/K2OtP+GSpD9E+SJD
    1eYTQzFIGkOToh1DGpkgQyUjIUPY2iBDs3ghQ4ACI0Op3nU/nucMv3hrGT5GEgi+R4fKPbkJuLyU
    z6a9F9KrPajzOb1NwUND7IdcQiKZ30G428TBL2GkwS/O28EgoRrCNO+awQeHPcEIhexBf3EdQdE2
    T78pZaDAWy9lwHYrMMABt5XAIO55wA75JMC/BJZCebXVwAZ6o0FlrcbAOsl7wIxK/MBq+gjB1jFf
    vXzgD8DHtPFDyGrFQVJbEEJYYEnCJ9ckwskgvsHAEHLCguGvwboTccEFehJFmfvhQpLSMEOeqHHD
    zrNBw+lxzcIrQJHDM8XbwsopkcLXlBJFpqcsQold2EJmNZDD9vyIw3A6a0Km5XDDnOaJw4mAQMMC
    Bn1AfH87vo6XRT8aIxy/ApaKvj73AL8ahO6+QHdDPm0+4rz2O8dAmdfxvTp+oD8QC2e/KrbnvvEO
    Nr9HR1+/Uy7ePQFdWb3Lp9ZAUd96vvJ4uT/tYoG/NTXnvjc4Tb8Zt2i/B9A0PiO4vr1rMEFB12Nu
    vqdpDD/EN8S/TAanv/ngkj5/eU2/3XmFv94xkr/jRrdCztwmwRRNAEGZtInBQ3v+wOATF79PFyvA
    LHsNwEDjB8HE5aM8AvAwvH7e4TpB6Jm6NaFqOt02krlj1Ti6kvxWOl8zBrpbIoFANlWHPzB0oD5o
    rn++CFd5voVGib5Xsb6+f1BFvji52710qxw/R2pGPuHIE7yb+FO9kw4fvckc9rwcxz+9ZZUnvTgL
    vLxVfsQ/nmoHvtSCaD7D6Wm9iywnvZ/Ykb0SaqW9U8eTu3jjzrxrbSVB39TdPqEk0D4rT/y+AVDg
    vlCYe74KWxW/ovdQviU9CL6VsElCtzz/P1DM/j8W1hjAb5cEwOuIib+KgjTAwKiDv8R7I78BzkFC
    zwCBPylsiz9GGDTA7803wOVaez5tFwTAeIgxwDC/zb9U4KU9Qa96uz1dETyzvrG7aBo1u9QPmbst
    xJi7bSb3Om9n8bgwwwI+wig2u5aLazybYgG86jGou/AR3bvXSgq8S1GbOv5OnrkZuAw+h2mouyZZ
    iDzUFxC8lTGlu/JQ+bsgUhK8E+zdOmPDUrosv4A+yKUtu7REuDs+B3y8j9dMvOT4kjqWuuy7vCEz
    vER/HrxYVvM/6eA9vslmqz3miim+gB+SvQ+sCLzYceS83S4KvZvon71xGwe/p1KhPT8LZb2BGyA9
    muFFvGQoBr24KSM9J2HQvFvqhj7jgpg9F3t7vWbmc73i24W9Q4i8vZTHV71ncPa81O2iPgOpeLyg
    86y9o0+DvUSySL0ja6C9M9eIvdbQFr2VI6y91ELfPaNCEb3v0a+8/UJavWvZVr1S2By7Lh6+vMQv
    TD1bGz49MdZNvYmXZL2B2P+8+Dxwvdn4xLwOMoW8eTtJPXP+QT0yz029RGpnvZUB9byzd229LlzM
    vGJOhLzxIqo8Mc21PAehcL2B8Xa9yZN6OzhNLL1GlGS97m8FvTMlMr2Bs7o9a8eHvSCBAr2baG+9
    HPxtvYzUjzwAlEG8lB+GvN26wj3oJYC93nsavQXlW70FFIW9TF4aO5//N7xIPQW9DtPOPWFWhL16
    7Qa9ED5pvSl1hb1KGpQ7LRFvvKQOZrw0J7885cqAvST2W7267nQ7DlzkvLclNb2Xpye9CmnMvQ0P
    ET08GK29oo8cvfzdQbsSULO8gHeZvACwFL3nKMg/QpZ8Pwpejj+ru4E/eZSEP0mggz+tDm4/E2Z6
    P3ZaAT8jZ1c/AGKCP14lhT+Lg4c/V3+JP1Lggj8Ig4I/QTQ/P2NDlD+f7pM//hGIP2Zwhj91YYY/
    s6d/P2H0dD9bazU/JV4cP3PJaj+iVH0/9JeCP4wShD+Jynk/ebOBP+F3Mj9oHks/EQh5P89fgT81
    zX0/ApqBP5JBgD8vCoY/IRkyP/YjSj/5eXg/fSuBP8MCfT+BdYE/E1OAP3wHhj8ujF4/GxNiPwEJ
    gD9h0oE/Sah2P1K7gD/LEIU/y7aFP8NIRj9S/Uk/8waCPxwCgj9+7IE/R2WBP6fDbT+kWXs/MpM4
    P4y2Qj9B9H0/HaCBP2JcgT/AzoI/c4t0P8Zhfz/OGEI/m1ZGP3i2gD+jHYI/NUyCP3l7gz/vQnM/
    /5h9PwFreD/9zmw/CqODP1nxgT8xbXQ/bvt7P0V+gT9FHoQ/SdSXP0m4gT9kZ4s/fjyDP1MTdT9Q
    6nw/WgZ3P81ueD9t9+A+gZjlvh/rxkDsUIc/btpbQMZCgD9hidNAEt+KP22XTEHf7rVATl7VQdgp
    O0EBgLJBNXRlQdkmcUCfaRtA1OVnQFrfDkAgb2xAH6MLQDi9FUAIPTU/VKx4QSZzLEHn7Ks/Sv2C
    Q7izA0OdzkZD5LuDQ0BJC0G4swNDSQLbP8OIp0BQHUA+7zIrQMiuOkMEn8pAKjrGQGvygkNGqwND
    zshGQ76zg0OoQAtBRqsDQ4cE3j/DiadAbB5APk8zK0ApqTpDCpnKQD05xkDmVahDZRUnQ0wHfUOq
    d6dDaycwQWUVJ0OvKCDA/minQIz1Pz5BJitAH1g7Q3pgy0CGWcZAOGWFQ4YPBkPJCUpDHwWGQ0Gl
    DUGGDwZD6N+xPyuBp0BiFEA+ADArQPzhOkOw1spAEEPGQCMthEPH5QRDBTZIQ5/ahEPabwxBx+UE
    QyrWwT9Af6dAUxJAPkovK0BF5zpD3dvKQNJDxkDnkIJDvVoDQ7nLRUPDToNDkNgKQb1aA0MIZdU/
    lXynQDsPQD5CLitAj+46Q7rjykANRcZA2l+8Q0WbOUPLcIxDj466Q4zeQ0FFmzlD5L+wwCsfp0Ae
    oD8+xQkrQOlUPENHc8xAVITGQIeogUNeZgJDkAxEQ05cgkPN2AlBXmYCQ2qtzD8gbqdAE/8/Psso
    K0CbLjtDKyfLQH1PxkBEB4xE45JNQuCh/kGtoPRB8UqJP/4IUz3lhp1BGYWmQTEKJUK9TyFByaA5
    PlJg5j2h2T8953oZPFZQLkDsZTJBXS8TQIpLBkC0fJA/n+UDPls45jygXTw+OLk7PmQMlDzhc0U8
    +Ez5PVcn3z61fCo/ZAyUPPKyLTzLOmk9rp8ZPszZPT43XANA6fuLPTm75j6L4PY81IFqPyq8lTx/
    zgk+ir2VO13ljkB69OFA7fgoQbWQ3D9AcxBAUk8yQNfRoEEig15BJJhLQU7AKUGNjA5BL+vkQLEw
    nkDMu2pAfhAzP3zK3z5QupA+ZCI3PnOL6T03MJY95MA/PW7x9jw0m4FBSr8ZQbjb6EDDC6RApZRk
    QBQwGEAsZq4/qepVP0lCED9HB5o+Z68kPtZfrz1zJDk9h7LEPMXYTjzOw9o7S4cLQrKTBUI07wBC
    mMpDQvxIPkI4vEBCE5IHQjnPWUJnkzo/OOAyP8LcKz+Fy4E/zmh8P1mefz9AlDQ/EEKQP1lkH0R5
    VJ9DgevjQ1lkH0SY4KtBeVSfQwAAAAA0eqhATz1BPniQK0BcjjdDsA3HQP6jxUD4WZdFqGuxQyVr
    MUPG/IRDqGuxQ8MgPEElazFDb6OnQDU9QD5LPStAI686Q2WeykANOsZAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAPsiWP+d6mTtn/BFAAAAAAESqrDxgIA5BMQrNPgAAAABbOGY9/ghTP8BAvEA64J4/
    qqwgPgAAAAD8FJc+AAAAAAAAAABJlZU/ikuGPqHZPz0AAAAA53qZO9q/AEDBOto+AAAAABOj0D4A
    AAAAdrEIPr1MgD+MRSQ/odm/PfwRJj8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAPNBNj054w8+AAAAACc9zj3V1Fc+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlhIjPQAAAAAAAAAAAAAAAAAAAABbOGY8
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAABUBu1I08AtjUPwAAAADw
    1Q89lVx8QTtGnDsAAAAAZXkCPg9Nb75DxlJA/muAP8nRAb8AAAAAcWTaPwAAAAAAAAAA50ZdQFJo
    SD9hpNs+AAAAAKRBrDxl5AtByI1bPwAAAAB4bDc/AAAAAE8Loj8m40RBpH1fQLA0Bj9AqAtBAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtmYk907xSPgAAAAAWoLm+
    oYmkPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAADZVCz4AAAAAAAAAAAAAAAAAAAAAbTLuPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAALPOk/U5FsQFCnOz8AAAAAC0jUPyd59j9WJS09AAAAAPkdDkB+z2C+fc1n
    Px39VD9C50nAAAAAAMENukAAAAAAAAAAAJYZRUAJLD9A34oSQQAAAAC+qI9AOxOPQCFGBEAAAAAA
    cIHoPwAAAACoVRhBC4hGQVQdsECFG7NAe6VZQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAA7EXDPwpsuz8AAAAAsGlmwN+uw0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqu1pAAAAAAAAAAAAAAAAAAAAA
    AF9vBEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUtjaP1ORbECpiPI+
    AAAAAAydzj9fdMA/SU3pvAAAAAAqUQ1AECu5vkMK4z13hDw/m59KwAAAAACEJbhAAAAAAAAAAAAf
    3zlAhsw+QN+KEkEAAAAAvqiPQPJPhkBDuv4/AAAAAElF4j8AAAAANN4XQXVlQkGw66xA/HeyQDoF
    V0EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDXvz/1P7s/AAAA
    ALBpZsBhqMJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAartaQAAAAAAAAAAAAAAAAAAAAABfbwRAAAAAAAAAAAAAAAAAAAAAAGFaPURB
    O1pBLGTzPhyd4z1kz6s+yIktPHaxH0II7bI/xiKYQX9pKT8mQKdBknA8PxCvlD9zKCQ9WEuxQb4t
    QD/HGMBADn9UPmJsU0LKYeY/IoNeQS0H+D5qjfVB60qGP33t/EClx40+2PC8PlkoSzzH2jg/MRXM
    PGX9Pzotvc88v74gP3xWWD9jNeM+I3YNP1pyTj80kDw+zESaPZvb3r0LQh49CNbxP6M4mD30exA/
    BDMZPgAAAAATW2JDsvH/PiwitUCZA+4/4abSP0mSZUCzE5JAR4KkQKR5p0C3D6hAqDCfQhDELkMi
    gF9DVq97Qx0YgEO4oIBDK66YPk0MJj8vAlM/rZttP0DmcT/ztHI/VEqPPvDmGz+xH0Y/NQxfP3EQ
    Yz811GM/pXt5QJh5+j+7nno/R1TOPnbenj44fZU+bqiLQY/bD0LsjC5CL401QvNvNkKGmzZCGEi5
    QnDXTUKwXf9BRvbXQdLz0kG/rtFB9YmuQepeHUG4j6lAq6kvP5YPMj8CpMDALxmPQxraJ0Nn6GVB
    wsbSQDJnDUGQmJVAd8EOQNcSokE5UyhCz/jhQeC/g0GCvTJBOdF6QOzOikBSWj1AnKc0QaVffD7E
    83lB70/FP14VZ0G+zJRBF/uBQgAAAADOaFNBXKNBQVW0A0IRwOBADb2RQEaUc0G3bWBCV4GHP9fv
    gkEAAAAAdKpVQZg9aUAuR8dAxdgmQayRokHRP99B2IEmQTTzr0ExmelBU+jCQYFUDkFtdgFBPcyA
    QfhpkUFcyv5A19qQQAUN/j48nFhBodonQMmU/z88pg4/XhbAPlvbKECZnStAo0JfP5ZiQEGIYa5B
    1Df1P0YNC0Gu/NY/o6y6PfLXuz6i7Jc+8cnOPlnlCT6zxVc/q31/PiHTuz+AupU/vBbGPoFabEJq
    qQNAKdlyQRAgBz83pC9Cy8LDP0lRGEFNvK0+4BldQKJl6z1dtcs/WFlaPTfvM0ISpm1CPNScQodd
    xEIE7tVCBej3QpYSDUNYRxlD4ZsjQ5DNgESZbHBAbEuMQBxfn0CmnbJAIrXDQEcEzUAsUdpAKFPn
    QCj68EB8ZvpAhJgQQSZnYkJLKd1BU1+DQLN/gT0AAAAAUmWFP48zPkD+CNM8AAAAAAAAAAAAAAAA
    AAAAAOd6GTvnehk7lRUUQAAAAAAAAAAALhmCPxt5oj/+CNM8AAAAAAAAAAAAAAAAAAAAAOd6GTvn
    ehk7/wViQAAAAAAAAAAAjTxRP9u2LUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5oPsPwAA
    AAAAAAAAjTxRP5/lgz8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAn+ISP7N/gT0AAAAAWzhm
    Pp/lgz7+CNM8AAAAAAAAAAAAAAAAAAAAAOd6GTvnehk7FJ3uPgAAAAAAAAAAO9dLPuGbdD7+CNM8
    AAAAAAAAAAAAAAAAAAAAAOd6GTvnehk7eaVEPwAAAAAAAAAAAAAAAAAAAABbOOY7WEoMPzAQLz6K
    S4Y8AAAAAP4I0zyNP0I/AAAAAAAAAAAAAAAAAAAAAFs45jtYSgw/gXglPopLhjwAAAAA/gjTPG3e
    Jz8AAAAAAAAAAAAAAAAAAAAAAAAAAKTN+z6BeCU+AAAAAAAAAADnehk7/BEmPwAAAAAAAAAAAAAA
    AAAAAAAAAAAApM37Pr9GHj4AAAAAAAAAAOd6GTtbOOY9AAAAAAAAAAAAAAAAAAAAAFs45jtbOGY9
    53oZPIpLhjwAAAAAodm/PIRs4T0AAAAAAAAAAAAAAAAAAAAAWzjmO1s4Zj1bOOY7ikuGPAAAAACh
    2b88+SCbQPBBFj5jYX1A7IrcQjjepkJgvrJCMQq9QGK/TUCGXgNAVNzQP1UydT8LrCA/KQnbPi+H
    mT7ZAks+O9wOPllaOz6EBZQ9qJQ5PYBmHj1gasY8WYGGPBRVTDxNfSg8a5EDPBIqzjt0eNU+MQ1u
    QQbi9UCc4G4/Vrz2PsoKqUN3c75A4KH+QZhmoEA+x7tATxjYQL0N9EDfRAhBF18WQU2oJEGW1DJB
    GiVBQXxECUMWioRA20PvPTgQr0A14BFA+MXfQB1BiEB2oQlBX5rBQBocJEHCyJlC71XIQ+whBkHX
    uyhFe5k0QhOgGUPsZTVDLHoIQdh4yEA=
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
feature_vars: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADI1NTM0MzM2MHECWAMAAABjcHVxA01NBk50cQRRLoACXXEAWAkAAAAyNTUzNDMz
    NjBxAWEuTQYAAAAAAABHJN1B7YMoQS1sqTzPuFM+CnuSQlo6OTsrPwo8CnuSQsaHhjqGJ2s9YZ4m
    PmFwZjrm6tI9WpMISca9ykMiOJk/eye7QeHcyUHh1hhDm6swQgAAAADnehk8pInEQOZeI0IAAAAA
    /djDQWu4MEB0e/Q/EbeQPgAAAAD8Dag/NaOAPqPyHD2dhGM8jG++P7M9WEYCix1Gzz7ZRsBt8UaY
    1RVHbcgVR4X7F0cLtBhHK8obR5ZJ0kRt1ydFDAvdRfjVJEbU7jVGTBBLRgLiVEZuhGlG0fNtRtpv
    FEaSIMBEg0o2RlriN0ZPE5FG4dGNRq4xjUbBJpNGRgyLRsEajEiT1QNId8CSSIGazEimh+1IHzn9
    SEG7CUnuIBJJpAoTSZ9F3EpzRvdJp/+HSqYwuEqWCNdK6O/gSh2c80oitABLvKcCSy571UoX+S1L
    CfPAS7CjDExTxCBMOpE2TCFDTEwbiVhMr5hZTFu/EUatSyFGYKILR6t1gEdAr6VHX7qvRwqDsEdU
    qcpHbsTLR9DtwkVXBeJFXc29RpHmKUdqKVhHXKFmR/19akfuqoRH0oCFR2hpwUWn4thFTQO6RgeE
    JkfhXFRHQZdiR12EZUdCpIFH31uCR0FKrENNYwlExcOdRHdd8kRM1AxFCPQbRZDwLkWhU0FFmkxA
    Rf5agkoUfmNKq4ZkS69t30vuJhVM6WwaTEyGF0x5bjNM9bUzTFjzE0CUjKM/g6T5P5j9tD/qFb0/
    ik7UPy1vyD8uk9w/dCXxP79kZj32X4A98CyUPYmolj3fV7c9wPDGPeJlyj07Rfw9ki4PPhMmMECu
    qcw9P/NPP2EXnD6fs+s+NtzePhG0AT/i3RA/CAb7Pk6xIUPslxpBaNxVQcSIdUHWgpxBxKCWQQCG
    j0ExLrJBxnLZQXwMkkUV3DVDKu1+Q3W7jEO4wrhDb6WwQ1m1oEOpTsZDlsgBRMQdokMyenpDIULY
    Q8uoxkPoCOtD9JUGRE20GESBpSxEz3kxRNj8gz3dWos8AmogPVnQED1E5U89yUpYPc4HfD1tL4U9
    GGFpPZ98qT30BJ88a2pCPY+ALz1mVH09yNOFPfUzlD1ITaw9GWKcPRTyvj2fPLU8vbRePcliND3u
    +YQ9pFCMPTjNmz32Daw9AfiaPUUe/DzI5n08DT+6PDLClTxMYbc8dUi3PJkV1jy3Dew8xOfqPBcn
    iEEvqCxBZrDEQXkohkHjyK9BEDmcQack6kHA0cxBb+DLQSy/AT4j/YI9oCihPWZykz0ff7Y9dmi3
    PWNHpz3s/Zw9EjGYPToKVUVbwhZE/gyXREcaAEXbnA9FDKhNRdwVO0UfhXJF35oURQL8h0LEpYlB
    EGuoQVjf/EGb1g1C6xkdQuX+SEJR2jBCjVXmQf5bI0U7HkJCZ4qURFeeoENKmjFE3y2vQwwDFkQy
    xjhEXiCtQ8Ek7kei9mdEJF1TRcCEH0YyMTpGDMU2RgiTTEbZlXRGx3QgRislbUq0UIhGWSSSR2A3
    a0iqiIRIT0qASHvglkg+8a1IP79jSJxbwEhI0AZGb2wISJ4KJ0gT7FtIlOVQSDHAgEgEVaVImeA7
    SPc2hEDh0IQ9F70EQP6Jcj+iybs/ZHOXP8Dntz9ma+Y/JxWXP7pEBUG+0Ow9YfaFQA8kCUB53VhA
    k81HQJt3dUCsf5BAZoo+QJU8NkFuFhw+z9m7QA0FLkAsA4lARshkQBXDlUA4Aq9A/txgQOHlaEGW
    tV0/AXmNQMi+l0Bct7xAJgi+QCsF3UCBUN9APqGtQMz/hUQ4MiNDIUUURLpYtEPNnMlDsTPFQx/q
    10N7cgdEaMwARLtfBjio5KY3G8QyN92ByDbfee426RUJN34HFDfZQx83EFooN21Eej5HHPs9dvQS
    PqNKKz66b1o+VuuCPkOUnT4onAs/1BzSPtIwgzu3h6E7qTFHO+/ZRjuxT3o7N5aDOzegojtZLNw7
    Sd62O6Iacz8vUZA8VuAcPpSuvzxUqkI9UvvDPEogiz1eVbI9gtxDPT2Vp0J664E+Jc7UPigHjD/Z
    oZ0/kKefP56Y9z9H1SZAUMXsPxN5LUWNkZdAgHITQeGI2kE0JeNBIzHnQZC1O0L0d3VCoForQorI
    vEAbUodACpCkQZuHgkHDCJ1BoZWzQaOYz0Ei5WZC9noTQny+pjps2es3NhSPOWWVkzgtQOc4nJSu
    OHYbMjk7hmM5BrFHOdigEzvoJ2g40LMOOlvULDlHIIk5QvdvOWRk7Tkr3xM6+I70OZHoWDtMSZQ4
    /JBJOuXNWDkeqao5IQeIOU/QETrTWTI6vEoQOmJ1kDs/Lb05vQQlOs6d9TlCXhc66aosOhxoSjqu
    jIw6a8d6OmIoej4/5oU9LVKwPXpY/jwe1/w8E98cPcnGNj2S4Xw9z8aEPcBbfDzsurU8515WPKT7
    eDyMdoY87nuOPL/lkzzAyqo8KdjxO7W2Azzn1B88nWdSPAXddDwDtos8wXcCPUuOwzwfDE089PAG
    PEsW/DspkSg8G2ExPPqsVzyhyJY8xV1vPB4nyzvf7oU8p4PxO1I9VzzG7hg8/lNiPKftyDw795M8
    sjMZO5spsTvX8uc7GnUkPIMsRzzBUEg8MmYFPTh7ozxFqwY7T0yxO4xY5DtqSiM8MXFEPAZhRzyM
    ogU9T5CjPOK08zpU7hM86JnlO41nCTzjvyY8GeI0PGCA4jzABoY8BVOWO+UvmDyCgA08qq1kPGJX
    Pzw/+IE8XBfJPEchszxL8Ws7oUp3PCcDEjwsVmY8IddgPDxXkjykAus8RRnLPO49gjvZ94w8iwIX
    PNJGbzyftFc8ljaUPALx4jwyhsQ83dDRO2NeMDyOK/k7GrICPJC+LzzCRDo84BmwPMN6eTwlC6c8
    /d2CPLP16DvGLQY8ngsmPOEzOTx6XXU8diOBPGPA5DxQE0w9L1HtPLGVHj0T6SQ9zU1QPSaAZj08
    QHU947GKO0rIaDx+Wjo8BrV0PPeXqTxdi+o8aXomPV0Z/DzUSIQ8ZdSBPBX+Uzz2uqA8X32lPOlu
    1zxKSfc8K2L/PF5/DD3BLdQ8QgrzPM41Wz3pJrI9BnPsPV0aEj53ZyE+SVQZPEBEbTwkth48SriJ
    PMB9AD3wzAw9Zs0ZPaNSDD0wehs8fIFiPKCqFzzShYI8FpD4PElECT1m3RY9rNkFPWz1LzzzSwg8
    GKjXO55SBDxjzEU8xpQtPEOVoTz+GVc8qP+kPCrJTj3UH+w8jb4kPcfQXj3F6o49zVjBPam1xj1v
    7Us8kfUVPZaOxjwx3Po8f7ksPfKhbz3xVZg9ZL6XPSSUdDzzojA96dHjPE6LET1lCEs9/MWMPb9A
    sT3Fn649+HXsPAitajz17Bw8Te9dPGt6rzzhops8kWrYPGzPszyKWDY9bEl9POopNTyhlR08tmx2
    PL7ZpTy1LNw8+pPIPJQVoTq774Y7uzPaPqGouD5tIOg9q3qXPIv4J0ADHQ8+GoxrQkmzTDnMTqND
    Kb5jOWGAjUAnNhs/rIcvPaM6KDmq4p49iPArOXW/yT0W5kk56cycPqlklzxReOM/MpefPRTrUD1Z
    f15GWstfRfWGB0YzB2BGXemcQFrLX0Xx6hA/Kd3CPvpMFzrEGgk+xjh7RdLQCz8j/rw+W2deRjW9
    X0UYiQdGHfdfRujlnEA1vV9Ff9AZP7ngwj5yTBc6PxsJPtsne0WBxAs/ovu8PugR0EY0L85FYLF7
    RuWrzkbTuyNBNC/ORRH/ej8FVsM+mEIWOg5RCT56i3xF1jALP4dGvD4ocmdGcOdoRXQ3DEaP52hG
    biWhQHDnaEXTgps+kc3CPgovFzomHgk+a+R7Rc/nCz8L9Lw+gUZiRk7TY0V98whGUtRjRnHQnEBO
    02NF+dG6PirCwj4jNRc6JRwJPikBfEUACww/cv68Pqo0W0ae5VxFQJsERuTmXEbu95ZAnuVcRTHc
    4T4XwcI+ijMXOoocCT5IDXxFRhUMP3MDvT6vYwlH94IGRvaTo0Z9ZQdHg3hnQfeCBkbrGwZBOCTD
    PuPPFTpjYAk+7T5/RaRfDT/BWLw+R0tXRrm1WEWNdgFGz7xYRuk0lEC5tVhFQGW1Pv+Qwj7GPRc6
    IRYJPsrefEWnygw/Aiy9Pt9GuEdoqShDYNJWQl2K90LbQJI/yqFIPeHcyUEEbsZBaMwGQ+0ExkBw
    VxY7r2t2Oh5LNz2sHpk814G5PyiAg0F0qAhARUR3QBVMRkBk+O89hkbgPF/OjDw1S4s8fA+3OzaJ
    MTv4rhc8EbRqPDRWBD18D7c7FpMGOxy7UTtkDWs7kF3KO8dPKz/BEJA8XiGCPWWi1DurSjI+4v8Z
    O7B9ETx3OEw5VfjkPwgqjEAKbzVBp+zsPn+xUD95psI/boqyQbi3IkGfKRZB69O/QPdRjUAxv0dA
    KyTfPwRqjz/9oF858PIxOEpBjzic9kI4kHsAONZbqDcLZVo366nzNnqob0HifL9ABSGFQCp8DkB9
    +po/TaUePyM7iT4+7fw9X6M2OhtB9zmp+5c5sJ/zOE66PThvCno3GM7UNvuyGjYaDItCyyqAQiGl
    aEL7tBtDNEgRQz/sFUOWaoNCguNGQ6vqujuMt+k7dP6GOuC6VjlhSrs5xADROQaVhzrRET05akto
    R7GaZ0YJsQBHaktoR8wqX0GxmmdGAAAAADYHwz4ZQxw6GmwIPvPJdUVGpg8/SofAPugUAks7ocBG
    VaLAReM2Z0Y7ocBGhUD1QFWiwEV9AMM+vwwYOiIFCT5DyHpFmFYLP6FCvT4AAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAh/6I/rB6ZOz5Yr0AAAAAAxGYOPXYrGUGx8cw+AAAAABEggD1RkYw/yIN7QC9J
    mT8rNBY+AAAAACTYpj4AAAAAAAAAAIXHjT8nB1U+Hks3PQAAAACsHpk7lrSOP1Fy1j4AAAAA+jGz
    PgAAAACNJQU+UC1yP2OeRz+LXN49/A2oPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAYclBPVvEAD4AAAAAzee5PTWjgD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACj8hw9AAAAAAAAAAAAAAAAAAAAAJ2E
    YzwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGImCQLsRgz1PFJFAAAAA
    AD1/zT3cghBCLG6IPQAAAAABJ7U+eUIqPmNReUBf5n0/KdUQQAAAAAANmC5BAAAAAAAAAABeJBhB
    DYXuP8GecEAAAAAAtarCPS3RrEECzNQ/AAAAAK4chj8AAAAAwtA5QdVZD0PxU7hBaMNbQHzbakMA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC393z0gbIw+AAAAALD3
    mT9D0RVBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAk+XlPgAAAAAAAAAAAAAAAAAAAAAatXQ9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAEwnPj08SiA5CJewPQAAAAARXTg6blaqPKiHWD0AAAAAHO5TO/ZPYT0D
    zEI99zbdPEqUCT8AAAAA21qhPAAAAAAAAAAAbRRWPViSETycMcA7AAAAAOc8ZTqYvUo9SbgOPQAA
    AAC4LtU8AAAAALgHuzygf0g+Z85VPaM+hTxnUBA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAiyws7aaVwOwAAAAAHgtc8ovL6OwAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKXCvToAAAAAAAAAAAAAAAAA
    AAAAYC2TOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACPLG49PEogObC7
    5j0AAAAAfdU/OiMZxz0QBmQ9AAAAAKR+HjuwoH892ruePjyoxTxjRQs/AAAAAJf8rTwAAAAAAAAA
    AFjOvD3K/Q08nDHAOwAAAADnPGU6nPQjPVgDSz0AAAAAMjkQPQAAAADoitQ869pWPjTzcz3mo4M8
    SErwPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgISO4MgbzsA
    AAAAB4LXPHC13zsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAClwr06AAAAAAAAAAAAAAAAAAAAAGAtkzkAAAAAAAAAAAAAAAAAAAAAxELy
    RwxNGkGQ1mE5pJBcO4TY0zql/dk5bIegQvfqOjwEw6RBCuU9OkYl0kHRdlQ8/IMDP2oPBTqpJoFC
    BruIPOuzN0AJCiQ6NS6UQ7fZEj24tyJBLSEbOA1YxEJ0xGo8rdpQQBXzMzr8Lks97FslOMYxeD0N
    aN03/pylN5YYJjk/cvc6dsL4OiUAnzYSUZI6ma4TOzfG/jrHkvQ5hWCaOqocMDrEZVdBp9+CPP0S
    yzr7Ess6AAAAAEmJHEaU+pY7eh5jQIODmz/VJ7c80vmyPWOh7T0imvo9YFwBPp5zBj5JqPBDXEsm
    RSznlEUWO7lFzGW/RWl7xEUInJI6FCBCOzGi9TqHyLk63TfGOqxNszo+Im46HM0mOyyQ1TpvNGk6
    cdRmOm7rUDrzESc+tiYMPrq5jD1POUI9INBJPVFeMz1QGbNBbrD0QcBy6UG12OhBbRPoQXFk6EGC
    AdlDLCXiQozpt0FMXEZBqbIzQfDjKEGFGPZBb0L2QPoQUUCOBV0+8FlZPqAfG0AcyYxFQyq4RM1O
    cUIPlMJByJRIQpYBA0Ilep1B8DhbQ7k9j0Me8StDHsK+Qut5gUKm9f1BEtq1QW81hEHKIYNCfpee
    P/YDFUKC5RFBGCc2Q2hbV0NDk9tDAAAAAGnhwEJxrXpC3iKHQ0UMUkK7qQ1CkjkvQ/sDrkPn0cpA
    42vbQgAAAABQM95CrNjkQdrhq0If0J1CpGE/Q5CwjkMQ+rFCIR53QyT11EPagTBDrZRjQkPmQ0IL
    r6FDMZStQn5Z10FdDHRB36zvPzb6+kEJvepADt+jQDq1VkD4FCc9bW+iP3Ly2T/DSe89mr3tQUmQ
    LEIwg1U9LME9QXqT6zwsGPg1OJfYPO2ObjzxvYU8fwAuOYgnuT3vLv86Xs5uP3nlTD7XumY8QqI6
    Q2hYGjr0+blBj3I+PLEI1UIcPmo8pQw8QZywhTxsH85AafLRO9p/jUAPaZs70+fiQuaPQ0ONJ7pD
    5BIqRH7DgURhYNREw4QrRTBre0XMubJFJHrjR/4YTj3hmk094JpNPdxzez1r9589TbMIPtXUSD5a
    MYg+vrfAPtXxAT8Q+Yc+6EA3Q4HDpUKjqkc/QNOMPQAAAAAZ/Lw+QCBSP80UzjwAAAAAAAAAAAAA
    AAAAAAAA53oZO+d6GTt7fU0/AAAAAAAAAACoxMM+OkUiP80UzjwAAAAAAAAAAAAAAAAAAAAA53oZ
    O+d6GTue71o/AAAAAAAAAAAoCtg+41wxPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2L04/
    AAAAAAAAAAAoCtg+W9rRPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD0CtQ+QNOMPQAAAABx
    TUE+SrhSPs0UzjwAAAAAAAAAAAAAAAAAAAAA53oZO+d6GTvCjZw+AAAAAAAAAAAHQy0+G2w/Ps0U
    zjwAAAAAAAAAAAAAAAAAAAAA53oZO+d6GTuiG6E+AAAAAAAAAAAAAAAAAAAAAKkj5TuHLKM+n3kR
    PlJnhDwAAAAAzRTOPGvVnj4AAAAAAAAAAAAAAAAAAAAAqSPlO4csoz68Dgs+UmeEPAAAAADNFM48
    eIGVPgAAAAAAAAAAAAAAAAAAAAAAAAAALnqHPrwOCz4AAAAAAAAAAOd6GTvEy5E+AAAAAAAAAAAA
    AAAAAAAAAAAAAAAueoc+TyAGPgAAAAAAAAAA53oZO/3RzD0AAAAAAAAAAAAAAAAAAAAAqSPlO1nK
    WT01Zhg8UmeEPAAAAAAFzLs8FBXJPQAAAAAAAAAAAAAAAAAAAACpI+U7WcpZPakj5TtSZ4Q8AAAA
    AAXMuzwGf6hA8XopOw48AkDg/htEa3EuRE9DWUTF0YdAjx5NP8Z8DT9EPLQ+LIgLPpV7lT1Doic9
    s4vfPKgHiDx9tEs8hg7COrWNITnEJ8c4FfcmOAqQ9DfTkW031vYwN2q+EzdejRI3O20PN10ehjuZ
    fINBjBSEQIYetztD1N45oD7aRREX/T1g0lZCVCh1Pe4EdT3y13w9rVaAPQYzhj3cq4s9QKyUPU1D
    nj0S7Ko9PbGBQ+Cdaj329mI+aWx4PdsSfz/JHX895Dc/QDVKgz2Te7xABBuKPdD1sUKPGxBGbXKC
    P6TyPEqqiwtDdOCgRKAg4ESVF71AjS0EQA==
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
hidden_sizes: !!python/tuple
- 1800
- 1800
input_dim: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  SgAAAAAAAAA=
learning_rate: 1.0e-05
task_type: CLASSIFICATION
