feature_means: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADIyMDkxNTg0MHECWAMAAABjcHVxA01NBk50cQRRLoACXXEAWAkAAAAyMjA5MTU4
    NDBxAWEuTQYAAAAAAACxXLRBNEeJQVs45jwnPU4+OWUVQrzKHUDaa5tAOWUVQs+Fpz+IhohAQ06L
    QINtIj5nOx9AID0PRLCsj0GhVd5Ane6WQSNPnEFKjz9C5oPkQQAAAAAAAAAA6m71QEakmkEAAAAA
    kx6nQXqckUD/AvE/8keYPgAAAAC0eR8/ikuGPqHZPz1bOOY7hGlwPzdq0UPXu9JDdhYZROuhFETg
    5AtEKdIBRGQf80NYwtdDjtezQyg3LENNgFdDsBGnQzvatkPS469D+SCpQ/W1nkNPdJFDH2d/Q2lN
    ZUPVsihD0m6XQ6XMq0PRWLdDyXOuQzkBqEMNFJ9DWa+MQ2RLrkRS5bNEyAYFRWuKD0VBiQpFTHYC
    Rcg2+UR6/OdEFtHIREGDsUUPca1FEaj9RVCoBUZT//5FI2/vRbdF5EUH19NF2se1RTV8MkZkxF5G
    dQeiRnygsUZFn6tGHgClRpsEnkZw6pFGPkx+Ruycu0NDPMhD9DsoRBrCUUT1kVxESs9WRNhVS0T2
    YkNEfdYzRPNTmkNVtqhDBjEMRFWOLEQmRjREjfcuREAEJkTI1h5EcGMRRJxmmEN85qRDUsAJRPDC
    KUR4tjFEUo0sRBisI0TOkBxEgVoPRHdMnEInm8FCmIsPQzW/IUNY9B5DvhUZQ+e4EkMWzglDjGHz
    Qnnw80WtY+tF401ORquChEacO45GyJOLRnxhg0bd2H5GxbJtRvBRDUGfLQZBYrbqQOZntkB9raJA
    OQmZQFxQlkD15YhAYzVxQKG4Z0CQ8IdAEcV8QMcqXEAyN0lAkrREQBDsQUCqUTZA2asqQGCamUBV
    /lVAya5kQLlyT0CECFJAbUJLQKpMT0C2xEtA1k1CQNxf7UG/LONBkWLKQVnSrkEyw6BBdrWZQRUL
    mkE/R5RBO1OJQeqJ8kKqO9tCbFjBQm9Fo0KedJRCRXGNQoNYjUJSp4dCQcp4QrB6cEOIi4xD4Ml1
    QwfDVkM2QEVDW+tAQ7fqQUO1RjhDK0IrQ6jo+kCyiftAJhv8QOQ5+kB0rvlAlVH4QP6y+EB+TvdA
    lsT1QL2PzkAbC9RA0EvSQMwbzkBMacxAtnzKQEQcy0DdE8lAk37GQC7qy0AVP89A94zOQIOwykDd
    bslAu5zHQDE0yEBdLcZAy7bDQPKg0j+nFvQ/I4HZP+wewz+GRLY/48myP0//sz/kDq4/zqikP0bU
    IkP7zxNDhyYaQ1KKHUNiYSBDOv0gQ6yfIENcPyFDHdciQyxJcz+Yswu/yOIXPjpbBr42osA90b1J
    vPUiqL0IgJo9mlkqvZV3QUNbo1dCcOfaQfh1wsH6+6HBX/3OwVSkI8IfRLLBgbglwSKb60F9+BxB
    HYw+v6kEoMAPD2TAECI5wJuno8CNv4TA1NInwDzwlEIlO9rAZzOjQSt0wsDLZYnA1dDewIpLA8Fr
    m1G/BFsOwFMH70PEV8JBIPIXQnGJOsKeKTHC1a3CwU9fd8L4UbzBnquBwbjbD0UcU95CTG05Q0lB
    XsOiFlHDpbzTwvOgk8MULejC8qyewphZEUUVszNCZpzdQpJti8PQiJPDNTyRQjo1dMOFe5TD5ndD
    w8vqekD54j2+aO5DP5iLF78FlIq+psnsvnpH6b6ztiU+F8cNvZ3CxECPFwO+GPyeP3HQX78/+e2+
    +9Ukv5GOW78RGDU9bS09vXRN00BXN4K+oRC4P10Pe78FdO2+sFU5v2H5Yr9TCdc9TUS/veMLP0G/
    L2K+noMdP/TPvr92EbW/dO2TPnSSRL/zbYy/haKbv8WvtEL52CPBaAL4QBs0hsE+wQXBH5AFPptz
    7b9hhRXAwKEQwbS8ozwQWTG83VHlOkgenLrd1GI6tIo/uY6BObrAVEA6R/XxuUW/gEA4nYU/elOh
    PsNSer4PzXS+cB+GvpTnzb7cY2m+DIa2vdB/HT9b2kc+F2b4u/rpUb2Tax+9MO0DvYJhVr18fzS9
    HcK4vPI0xT+tTAy+6vhrPvksb72o7Cq9/LGDvck4ob1e62O8C1m9vP5AI0Fylt4+Qx7iPoHT5L5n
    yOu+aqmQvjUDHL+IA1q+aM8ZvhcnRULquv8/8q4JQIpLCcDctwvACLSgv4HbOsCCSYa/2fk+v9+w
    QULbUYY/+2yRP+RGLcCxs0DAgHGXPj3jCsD/BUDA9X/WvxsNpj1J1H27Oi8TPExzr7vPLjC72uWR
    u+r/lrtki806kbkFuTREAj7jakO70jhuPAfE/bvwXKe71FXRu7OCCbwNLvk5UuYPudq3Cz77nK+7
    ShOKPJzlDbyuH6S7vwPqu1XPD7yH2WA6weM1um38fz6BRiO7uHXTO31EdLwBAFq8jc8xOqSC57s5
    CT+8/MMvvJSP8T+Iwzu+gAOmPewqJ779Dpa9KySRu25ZmbxOgBS9L8CpvcZoB79Ev6M93bdrvVnI
    Hz3Aog+8DYAFvcWnDz1uMbC8PsuFPmrQmj0LoXO9SYxvvSTHhL0vaM69kTJ8vc5uy7xSc6M+RbNK
    vAo5qb341oK9PSZXvdTusb18IZO9qgUSvZIEsb236989nXkLvW1TqbytjkS9lyhdvSbUS7zq5aa8
    AgNIPcO+ST3hSD+9Ox9nvSafAL1u2Xq9Ur3wvG7mfLxyMkU9az9NPTc4P72JMGq9WSr2vCwld70t
    n/e8auV9vJPFsTx3+7o8MFxova5Ggb2xkqg7p1Y1vXDqd73qagu9ZCYyvbB+vD0aUIK92gz3vCsa
    a731LXa9xvEpPAugCbwmX5G87QTFPfCAdL08qBW9yDBVvc+0jL1Tl8q7xibeu5i5C71EXNE9vBh+
    vRfOAb1wlmG9pCCNvShml7vBkSG8q/JRvHbK0TzGh3q9B1dmvUmLVzv5Q9q88QJDvX94Mr2dOsq9
    6xEKPc9mrL0lNyO9yyrpumiRirzUiqe8EyIbvRpkyD/qRHw/ulWOP4ZNgT+kKYQ/u7CDP7CLbD+n
    9XU/+OIBP/gtVz/TYYI/qeSEP8B7hz81dYo//4mDP+9PgT+s5T4/iq+TP07Qkz8iGYg/qhiHPwiP
    hz+s/38/uAJ0Pxv1NT8jkxw/eTtrP+hvfT9kuoE/ehqFPxR1ez8r9X4/7UwxP7qRSD8RcXg//5CB
    PzWEfj/lMoE/TQmBPzCIhj9w6zA/Y6tHP+3Sdz8IWYE/+LF9PyYJgT/CG4E/YZOGP/umXT/yYWE/
    kjx/P9wagj8wgnY/2cqAP2rzhT+CeIY/yGZFP/8iST+9soE/+1CBP8umgT+zsIE/Z59tPwdMdz9b
    WDg/FQNCP8NefT8aFYE/1QSBP4wZgz/XN3U/DAN8P+AaQj+D6UU/SYKAP6SZgT+Y/IE/7fSDP7yx
    cz/GNHk/C1J3P1iEaz8jaoM/I12CP7FAdT+h73o/cTeCPw3bhD+P2pc/6hWCP5eCiz8NhIM/mP50
    Px8Yez/AEXc/B593P88l4T6jnOS+aJnGQCvZgz+y+1tAzFJ/P/RX00BW3Yo/h+ZOQSqYtUDIYtdB
    BcU6Qft2skEgdmVBJ+dwQAJvG0CiemdASuEOQBD1a0C0qgtAXuUUQP79NT8a/3dBTYgsQfv+rD9h
    RoFD/PsBQ9EXRENDBYJD3i0KQfz7AUP4Uto/PBCnQAiYQD4fripAjS45QxUvykDn0cVAYlaBQ9kK
    AkO0LERDIBeCQx1BCkHZCgJDaMXZP3wOp0A2lkA+c60qQLYuOUNPL8pA29HFQIzZpUOonCRDGRZ5
    Q/P9pEPzaC5BqJwkQ1dxHsDG8qZAAnRAPoOiKkDw1TlDgu3KQK3wxUCVl4NDqEEEQ7klR0P8NoRD
    b3oMQahBBEPqMrE/3wqnQOCRQD4YrCpAv145Q19jykBH2sVA12aCQ64eA0NqWkVDShODQ7RLC0Gu
    HgNDw5TAP+sIp0Cuj0A+W6sqQHpkOUNJacpALdvFQPbUgENNnQFDYf1CQyORgUMXvQlBTZ0BQ09s
    0z8rBqdAfYxAPkyqKkBxbDlD8HHKQIXcxUAWdLlD8Lo2QyUzikOYqrdDJLRBQfC6NkPQ463AkKmm
    QCsfQD48hipA3Ms6Q+n5y0CFGsZAKOp/Q0axAEMfTEFD/aaAQ4/DCEFGsQBDgI3KP6X3pkD+e0A+
    v6QqQAysOUPztcpAH+fFQOx8i0Rr6ktCKDr9QZIn8kH2L5A/80E2PSNPnEFEraVBT3cjQi8WIUEp
    yTk+a7bmPed6GT1bOGY8AvcsQINyM0FVVhBAJEwDQN2wiz9NfQ0+odm/PGwUOj40UTk+LpaZPCD5
    SDxgYPs9+2jfPvE0LD8ulpk8NKYuPCV+bT1sSho+uWRBPr0kA0B/4Ik9rs3rPmGL/TwsK2s/73yN
    PKo5Dz407Zg7JnOPQD1z4kCw1SlBppnfPz5iEkDMnDVADASgQQspXUG3kUpBKRMpQeLfDUF8BuRA
    wtedQBTdaUCALjM/wrTfPvmakD5L1zY+8NvoPT2dlT237D49pK31PLQSgUEBERlBF03oQFsspECL
    qGRAhGkYQHSArz+eI1c//X8QP2JMmj5kEiU+fgqwPSOkOT0vL8U8tuhPPL4n3Duc8gpCaBAFQuoj
    AEJNOUJCVsQ8QsgpP0KovAZCMetXQjVEOz+XkDM/SjAsP6LVgT9cfXw/aqh/P5rnND8CM5A/GnMd
    RGtvnUO/zeBDGnMdROzTqkFrb51DAAAAAGgFqEA3wEE+wg0rQJ8LNkO2isZAajfFQHuJlEUhK69D
    ISsvQ5wwg0MhK69DSbE6QSErL0OfLKdAF7tAPlm5KkDJLzlDxS3KQI3RxUAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAABTYpQ/53qZO6LWDkAAAAAAodm/PCg6DUF5pcQ+AAAAAP4IUz0J02A/dLq7QAvH
    nD/nehk+AAAAAOd6mT4AAAAAAAAAAHHJkD9YSow+53oZPQAAAADnepk75oD7P5gG3z4AAAAAJz3O
    PgAAAABiFws+lRiFPyVGIT8Qr5Q9tHkfPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAA53oZPfwUFz4AAAAAraDcPYpLhj4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACh2T89AAAAAAAAAAAAAAAAAAAAAFs4
    5jsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFvoDQG7UjTzm19E/AAAA
    APbvHD1CYHpBVerrOwAAAADoo/Y9B394vpNHVEB/NXs/TzL+vgAAAAC8gd0/AAAAAAAAAAApL1VA
    nxhTP+0dsD4AAAAApEGsPCu6CEH2/F8/AAAAAAxoND8AAAAASKykPxUbTEH+AlxAqzbMPjSnBUEA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOUebT0NBV0+AAAAAHNZ
    x74dzcw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAXJAkPgAAAAAAAAAAAAAAAAAAAABzYG48AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAIJA6j9TkWxAHIw8PwAAAAA17s4/RTn2P9NvTD0AAAAAoz8RQFBDQ74W
    MGc/BZtSPykST8AAAAAAAIS5QAAAAAAAAAAAOQNEQI/DQED14BJBAAAAAL6oj0AuK49A+cEDQAAA
    AADfTuc/AAAAAJDfF0E4dEZBYr2wQKHHr0DfV1lBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAABEwcU/ejS7PwAAAADN5mbAENnDQAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiXW0AAAAAAAAAAAAAAAAAA
    AAAA9YgEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABvC9w/U5FsQHhJ
    9z4AAAAAgBLKP96awD+LUt28AAAAAF3hD0AM672+DuX4PTD+Oj+T00/AAAAAAMm5t0AAAAAAAAAA
    AHUFOUBsREBA9eASQQAAAAC+qI9AxHaGQAxb/T8AAAAAfcTgPwAAAAAxjxdB04VCQcL2rECJbK9A
    U6JWQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARMHFP4cKuz8A
    AAAABvtmwIapwkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAIl1tAAAAAAAAAAAAAAAAAAAAAAPWIBEAAAAAAAAAAAAAAAAAAAAAAQ7A6
    RGJHWUFyovM+BBvpPfyhrD5oAzU80+AeQhTnsj/CN5dBiFMpP+SJpkGiejw/U2KUP6s/JD1c969B
    cgxAP9jFvkAgcFQ+g/tRQtw/5j8LKV1BA+33Pqv/80EEMIY/QYz7QDKrjT74br8+zGBPPHC9OT8X
    Ss48ZpAsOrCZyjz4CiE/2mlYP8U04z7HmA0/JIhOP1nCPT6MkZs9JvPfvVUbHj0sIvU/xziZPcaT
    ED+30xg+AAAAAKgNYEMa0P8+xiKyQK2d6z/cC9M/+09lQKi9kUBGQaRAqjenQNK6p0AxFp5CIxAt
    Q2IcXUMXMnlDqap9Q6GYfkMOSJk+ATQmP4nxUj8DtW0//v9xP920cj9iy48+bPwbPxb+RT8rEF8/
    wBRjPwLAYz8mk3hANJL5Pwt3ej9DtMw+BE6dPocblT4lioxBUwgQQvXULkKz6TVCz802QsAAN0KX
    LLhCA9dNQsC0/0F/KdhBhC3TQePu0UEQi61Bqu4bQSB+p0B4qDU/B9wzP0/3v8AaV45DdyAnQ9BD
    YEE5n9lABxUOQXd6jUBkSAtA9IOpQRxjJUKxlN9Bre+BQQ6HM0EtxYFAtWyCQCc1Q0CmUzNBHuZJ
    PsnjdUGKVsw/rg9hQaRmkkFb3YFCAAAAAMVOUUFwtj1B578CQqtx5ECrA4xAtHlwQVNAX0LzoKg/
    tIWCQQAAAABDSk9BvZNmQFsUykC6aiVBrG+jQSyt2kF6aylBk9WwQZrB40HSa8BBetcVQc/+AUFl
    /HtBZ0+TQYlJ9UAnU5FAsVf3PubyV0F/dyFArZD8P8F8Bz/ABrU+FCQoQP6+KECMMlg/jI49QSKg
    rUFM2/g/K3wMQZox2z+9AAY+rtW+PpSLmj6t0M4+YWwMPl/lUj8cR30+58y4P75Tkz/EFs0+bf5q
    QoSgA0AfcnFBDTsHP3eZLkKEmsM/Z/sVQXk/rD5GK11ArfbtPTqU0T9qgF899ywzQs77bELnfZxC
    jEXEQsBA1kL7F/hCKTENQ8MuGUPP9SJDkqSARAEdcECOL4xARkufQMqPskBKrsNApw7NQPNh2kD5
    ZedAz/7wQDhS+kDtmBBBvAJhQuPG2kEI2YJAikuGPQAAAADN/oU/O9o8QP4I0zwAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAC8VRNAAAAAAAAAAACpsoI/qqygP/4I0zwAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAACOOWBAAAAAAAAAAAAdcE8/h10sQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADCN+k/
    AAAAAAAAAAAdcE8/s3+BPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG4hU/ikuGPQAAAAD1
    NXI+n+WDPv4I0zwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADXzvU+AAAAAAAAAADV1Fc+uGd5Pv4I
    0zwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDckM/AAAAAAAAAAAAAAAAAAAAAFs45jts5Ak/RKos
    PopLhjwAAAAAiksGPZcMQT8AAAAAAAAAAAAAAAAAAAAAWzjmO2zkCT+WEiM+ikuGPAAAAACKSwY9
    jEUkPwAAAAAAAAAAAAAAAAAAAAAAAAAA1871PqqsID4AAAAAAAAAAOd6mTsbeSI/AAAAAAAAAAAA
    AAAAAAAAAAAAAADXzvU+53oZPgAAAAAAAAAA53qZO7hn+T0AAAAAAAAAAAAAAAAAAAAAWzjmOwrQ
    bz2h2T88ikuGPAAAAABbOOY84Zv0PQAAAAAAAAAAAAAAAAAAAABbOOY7CtBvPed6GTyKS4Y8AAAA
    AFs45jyc9JhAPTwVPqgpfUA7ettCknClQnB5sUJYSrxAX9JOQH3jA0C3XtI/Zr52P+PtID9uI9w+
    7HeZPnr6SD7Qswo+iag7Ppg/lT20XTs9BwMgPfBPyDy/koc8nwNPPKFpKjyT7AQ8JLDLO/uv1j6t
    nWtB/gjzQKFybz/RCPc+ew6oQzgyvkAoOv1BwEKgQByru0B/BNhAEQT0QNlECEG1ZBZBK7MkQVvl
    MkFfO0FBS+8IQ8ZehEAgmfg9Uu6uQIw8EUBHr99APYqHQK+cCUHvjMBAxx4kQatRmUKGjcdDyaMG
    QcK0JUVfJjRCBOsYQ9u5NEP/WQhBKD7HQA==
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
feature_vars: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCAAAADQyNzUxMTg0cQJYAwAAAGNwdXEDTU0GTnRxBFEugAJdcQBYCAAAADQyNzUxMTg0
    cQFhLk0GAAAAAAAAGuHYQSwMIkGGRuA8dvhZPh8UkEIlQDw7hh0PPB8UkEKvq4M6f9xpPW9gKD6j
    Fl86+/HUPelF/Ehxo7xDEXCSP8e/vkEwn8xB8JoUQ4n3LEIAAAAAAAAAAALiv0AN+yBCAAAAAIjp
    wUF6HixAIHD8P/2Blj4AAAAAzVilP4dlnz4eSzc9qSPlO4I6wj/GZ1RGfQYdRrXd00bSpeZGAK4K
    R2ywDkdHxBBHFCkUR6pYFEf0mMxErU4jRYiC1UUqax9GdRUuRuwjQUYsxElGctBdRpP3Y0ZCSBFG
    HgK9RGXQMkYYTTBGTgGHRtHxhUbSqYRGD6uKRh24fkaqzXdI840BSChFkUgIA8tIbeTmSAIq8kiP
    XgNJ/pMOSXZvDUlLR7VKEwj0SeuHh0pF1rdKWNfQSmBg2EoUu+lK1gf+Sph7+0rpFdJKzxIqS9VQ
    vEtQWAlMPuEaTOJ6LUxF0EFMLKROTJ0vUUxIJw1GcI4cRuVdB0cp7HhHeDuhR/Uuqke/WadH46a/
    R3cuwUdY/LxFAIrbRZYSuEY4pSRHqutRRy9/Xkec4l1Hj+l6Rwv2fEetXrtFFZ/SRchetEZCTSFH
    ZCJORxucWkckE1lHfih1R6/edkdUL6pDKVQGRKxEmkTgE+5EQo4JRScMFkWGDydFiPQ4RYp0OUWc
    f31KCD1dSpBzXkvdXdlLZygSTJudF0wUhBBM2fEpTOMLK0xS3hlAXF6wP6z5A0CWUrk/kwa8PyTp
    3T/1HtE/1aLdP6W48j+q6XU9ML2IPZbfmT3Bx5c9gWi6PSflzj1DsdE9ycD3PXdqFj41fTJAXL/Z
    PRpAVz8TgZo+w+HlPhE53T7M//Y+oTMQP+KnBD8LNvNC3XUmQbyHZEF8OoFBqTKaQYPTmEFu4IxB
    UXK3QUeq2UHt/k1Fxak/Q+MIhkOOEZJDJsqxQ2oBsUNZhpxDVyXMQ2Xf+kOoUaZDN3KBQyGD4UMa
    sc1D6t3xQ2rKDEQmKR9E9oktRHPwP0QT5og9HQORPM4lIz05LBg9rUdQPYwtTz1n02E9kz6HPTeI
    cD3IsK89l82nPJ6qSj2yxTc9lEx8PVwfgT0c04g9bxusPQktoj3RmcM9GK69PDGFZT1YkTo9bAmD
    Pfcwhj2mSY49YdKqPcGhnj3RHOA8E1KBPGJBvzzJjpo8HoS+PFRIwjwM7dw8JenqPLEe+TzE4IxB
    XnouQZtUx0FLTIlBa+O2QTyTpEEg+d1BhCHOQRvs1kG+Xf49pPd+PeGwlT0zZoc9uyGlPWpBpj33
    z6E92FGOPbTihj3JtUtFUuIURI7ajUQYxu5E/4oJRT9wQkV4cyxFc/dmRROsBUVhJ4FCnMGNQWdd
    rkHWNPZBLusEQrrcIUJXyzdCWVM1Qja3AUKU0B9FEshGQocElET3HZ1DJGUnRLHGrkOmj/ND4i07
    RKO/ikNljrlHqENvRABBUkUJXRJGC306Rq1bNEbd51JG8eN4RpLBKUYdjS9KWV2MRrklkUcbLFFI
    7VeFSHTke0gjHpxILbyvSP6ib0hhdb1I1koFRjUWDEgq+xxIWYFTSAAwUEhH1HNIAaScSMD7REgH
    k39AWbSLPUycB0C9qXM/dsW1PyItiz9VfKE/rSTnP0aSej+DegBBvWDyPfMih0AR+QhAi2dTQJjP
    OkB1yUtACe6QQIvcHkB5hi9BYCEdPl9tvkAvFC1AsHyEQBZBVUCwZXVAVaOuQFRMNED7plFBWvRZ
    P++Fk0AjNZtAQJy8QLjQwkCKp+RABALdQCUJtED/gYVEIUYhQ2lQEkTYnLVDbzPHQywkt0OehuhD
    u+z+Q3Zn60NH2A047R+qN5D0JjcFOLk2hHjfNp7ZBDdxXRg31jwONwf+FTc+qG0+xdkEPt8MFD6C
    GSM+i8NWPmICgz7C+4o+88QMP95xsj5rp4c7oKWuO5c9Tjsv1kg72X9yOy9cjDu7W5w7zg3pO9gM
    xTuw7HI/18+ZPLTqHT6048U8No47PfiGzDx2aU09ZIq4PVizHj2us2VCdXyRPkyU4T6t8Go/JhuY
    PxztnT9pHfg/1zsoQG4x+j/c2uNEISKpQCw2HEHb8a1BCc3aQcTq4EG8vjtCM8xxQnHONEKGj8dA
    2yKHQFGsq0HQ53VBp52YQTLntEEAEslB0iRoQuDVGkImcqI6d3QBOA5KkzkdnJk4TGjiOCO1rDgv
    SBQ5VVJuOZFAFjlWWA478Q9yOBieETov+TI5hqeHOZXocTmwoLQ5eFYbOmsAvTnrbVA702mZOAxz
    TjrCoF454rinOT1liDnvJts5WJM5OrNA0Dl9cEA75je/ORbAMjpE0f05LEMWOtTKLjryc086Q0CS
    OuLAdTouD3k+6q+FPUBRqz3l3AI9DpT+PGnaDz1DGkM9cMl7PQCvaj3r/mw8y1CnPM48SjyrA2w8
    8YqEPPeKlDwghYk8cxqYPDV5BTyRVgg8RXsZPHdITjzKnHY8tl6FPL+bBT0USKs8871dPJiECzxa
    7Po7fSQkPOQjPzyhzFQ86vaePFTMfzyTD8g7rZKFPGX99TugqUk8B1wdPHi5TzzNf8w8w+lzPPAq
    KTteZK47GCDnO8o7HTyO5kk8VnlCPOapCT1xv6U8ciQVO5aqrjv1FOM7pRccPPl3Rzy+MkE8pMsJ
    PUQhpjw0F/M6q2MZPOJl2js14wU8GRwoPOnqLjwIaOM8YEiNPGq2ojsVGZ48pzYPPLG+VzxwCEE8
    4rSBPJsP0Tz9c5o8Q8RzO4wTfjw5Exc8XrBbPHfXYTwbyog8agz6PM+3rDxA2IM7Oo+RPA7EGzya
    /WM8pIlYPMqwjjzWKu88bQ6jPAg/0DsFPTo87/L/O9ZIAzw2RTU8WZxDPK8etTyf74E8YT2nPBO1
    gzzu9+07K1sJPNxGJjwRKkg8UR9xPDP5Yzxrd9I8UsRPPUIb4jxsiBs9cD0gPZoDWj2mQFM9IkJc
    PfLXlTtd83U8Y8suPCZFgTx+3qw8xIPbPDKeJD3i5NE8Rj+JPOZVezwjnFY8c9qePEsTsTzwDM08
    GkL+PKIBBz3xFww9stnYPJO26Tylr2g9C/+5PZGK8j0p+hM+Pc74PSBRJjz0JnA8J2gZPBALizxF
    eQU9GlkIPaipIz2OXhU91RAoPCkaZjyXGxI87n6DPMKHAD3xQgQ96FYgPVxnDz04bzU8TFcPPLy1
    0zvVuQI8vaxBPEB/KzxOhaM8Iz1kPE+ypjzgZVo9EHrdPEC1Iz2Nw2I9WduOPZdZwz3JoJQ9vN5H
    PLQeHz3nh8A8O+b+PBvkLz2dOGM9P7KePbYlZz10fm48CIE8Pb8n3jxDZRQ9MNdOPb6cij38Nbc9
    K1yBPeYn5zx/lXA8slQiPC8AYTx5N608B4ynPEt32TzhUbw8m8oyPbPpfjzrgDY8oZclPIYTfzzQ
    J64838ncPFl4wjyGIqI6AWODO0MX0T6j16s+/8XmPeqgbzzFjyVAHagPPqC3S0KPzVM9KMaJQxct
    iT5v9G5AihVFP0VELD1PIC05siGbPfOmSDn5AMU9w1FNOexQdz48EpU87gzfPxXYnT3JOFE9YKRd
    RqDlXkVKxAdGrR1fRvKenUCg5V5F8bVNPwqBwD51Bhc61D8IPrJ7c0X79Qg/f4O7PjcZXkZHO19F
    Jt0HRlqLX0ZPvp5ARztfRdC92D8YhMA+ChoXOoY9CD7We3NFrCsJP6qHuz5QUc9GIXfNRTYsfEbK
    9M1GPfoiQSF3zUXEfYc/97TAPjJMFjp/YQg+P890RaOkCD8t9Lo+JnFlRkPZZkVEzgtGj9tmRia3
    oEBD2WZF2T2ZPh5jwD6a9RY6PD8IPtEVdEVlAQk/t4G7PuYkYEYzpWFF8nMIRnKoYUbpTZxAM6Vh
    RcTCtz53XMA+ufcWOl4+CD74KnRFWhkJP2WJuz4ZCllG76taRRcNBEbIr1pGanqWQO+rWkVNzNw+
    8FvAPtX0Fjr6Pgg+Rjd0RWIlCT+ujrs+GeEJR7MFB0ZiJaVG/+cHRx5YaEGzBQdGjLIEQXdywD6B
    6xU6kWsIPg1ud0Uj4go/AQ27Pi41VUZLllZF7wEBRhygVkaS7ZNAS5ZWRVKutj70N8A+U/cWOhg7
    CD6u7XRF6L8JP72vuz5AyLNHWikkQ4ynUkK7vO9CF2aeP3yOLj0wn8xB1jTEQeitA0OuPMZAD/AK
    O/jlejpsExQ9qSPlPKsMtD/1QoVB0jAJQLgdd0CqnkJA+RD+PQXMuzyWCJQ8fsyRPCSnvDtXMTE7
    WagkPB6CbjzhWAY9JKe8O95JAzs3Al876tlwO7qq0jsB3iQ/rmmLPEZcgj1T5Nk7rDAsPjKIBjuz
    IR08ru9FOWaw4j8N54VAa/0sQUZj+j6eOlw/48zOP3gwrkEAkR9BfbQSQYXwvEBRCYhA2X9CQGko
    2T+4a4k/DhlZOSq5NTg6J5I4nXI5OOQKAzj4Jas3ICpYN0+o7jbZiGpBknW6QMQggkCU3g1AXWmZ
    P9FZHT+9H4o+OID6PZe9PTo2fwQ6N+WhOa5CBzmxCVU4p4GPNyvM8TZ46DA20wyJQsSafUK9QmNC
    DhQXQyL/DEOnchFDoKOAQjZSQUMgsLo7T4LkOyoJjTpPB2E5jQfFObCA2TmRAoc62cBCOdxCXUdf
    MV1GmqL0RtxCXUdoaFNBXzFdRgAAAAC47r8+w3AcOh5rBz6p0W9F4wkPP7GVvz4+VPVKsHy/RrB8
    v0VkWmdGsHy/RoP/9UCwfL9FXGPAPs7+FzrtGQg+7ShzRY69CD9b5Ls+AAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAXpeZP6wemTtu1LBAAAAAAK+WFz1IfBpBpiHLPgAAAAA8KYE9r46kPyTOfUBn+Jw/
    cjQRPgAAAAC8AqM+AAAAAAAAAACvzoY/l2hfPmwTFD0AAAAArB6ZOx/5kz8tIeM+AAAAAD69sj4A
    AAAAdhgCPlEvej9vpU8/dXGdPc1YpT8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAGwTFD2p5gU+AAAAANrvzj2HZZ8+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHks3PQAAAAAAAAAAAAAAAAAAAACpI+U7
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHYbfkC7EYM9P52RQAAAAACt
    +9U9+IMQQlikgD0AAAAAxczFPoBEPT5BZnhAvlSAP5TqDkAAAAAAYJMqQQAAAAAAAAAAFnYPQa4G
    /z8SRENAAAAAALWqwj1sZrJBsmHkPwAAAADBEoU/AAAAAPDqNUH3JxNDql/BQcM9FkCD4mRDAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADhGbQ9zMuRPgAAAACchK0/
    JmM5QQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAACVABz8AAAAAAAAAAAAAAAAAAAAAdcT2PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAABYBEk9PEogOTVTsT0AAAAAp4dlOq7xqzzbTz49AAAAAGkkhDsz61k9yeVL
    PWoJ0DzoaPw+AAAAAP06rzwAAAAAAAAAAFHkUT1FWUM8ZyyUOwAAAADnPGU6MI9TPX6HIz0AAAAA
    W//XPAAAAAA4jtA8BW5EPkR8Nz1enZA8GR4JPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAiE3YOh04hDsAAAAAtz3YPFp0FzwAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmk8Y6AAAAAAAAAAAAAAAAAAAA
    AOBJDTkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApyBoPTxKIDmiH/A9
    AAAAAIFdYDo29cY9OMZLPQAAAABdL0A7wBqDPeZumj5NIbk8M6f/PgAAAAA7ZLg8AAAAAAAAAAC9
    K7g92Y09PGcslDsAAAAA5zxlOvt+Nj3NoFk9AAAAAGViDT0AAAAA3t7dPET+Wz7STkw9HGWPPIym
    8j0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIhN2Dp3cIM7AAAA
    ANbO2Dyk4wY8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAJpPGOgAAAAAAAAAAAAAAAAAAAADgSQ05AAAAAAAAAAAAAAAAAAAAAP/M8kct
    NBhBGUxnOQcNUTu4Vdc6haDwOZCXn0IHmjo8bMqhQbhnQDoz+9JB4b9UPIu2Bj+YcAY6rX52QlIl
    hDz48DBATpcqOh2FjkN4TQ09AJEfQXBHGDhaa79C7Rl1PEomUkDsNjg62xhRPVByMTgNkX09eCT6
    N0kliDc+wC05qvAEO69H9zrR/5o2zfqWOiDDDjuXYAg7AN3+OeJ8njpuDyk6/1lWQVl5gzz5C8w6
    +AvMOgAAAADSnBdGfpydOxncVEBxx5E/Yfy7PA/CsD1iQOs9aPD6PcTzAD7Y6AU+bRHoQxbqIEWo
    kpBF9w60RSdpukUdAr9Fo0qXOmpqRTsoF/c6l2K6OhM7wzoPJLQ6mK5yOmsZJztVRNQ63hlnOre2
    YDrJIlA61FcnPp5pDT4ML4w9wuNBPfClRT0+djM90vinQQq870HTPutBQPrrQfQK60GgNetBB/7T
    Q19q4UKwS7hBnbJEQXRRNEEiGStBxXvwQQIr80C5IlFADIJTPvd6Vj64XCFAsMeJReGXtUSE0WhC
    XzrLQUgMTUKpWAhCP5aRQbryWEO3V45DzuovQ+RMwEKaHoRCEEACQg/Xp0EH8I9BMS2AQs4egD97
    5RZCXdERQWWdMEOCKlFDs/nhQwAAAAD8Z8BCFctjQtsRhEPL31ZCSLcCQm/HJEMp+K1DK1H7QAN3
    2kIAAAAAu7jeQh075UF/+aVCp5KYQpm0PUMK35JDxsrEQpj1gEPgYNdDy6Y5Q2BmhELzpkFCBbCg
    QyCDrkK/Js5BsoRuQW2X6j8SzvZB7vrjQCOKn0CzuVRA2BcYPfULoD+Hcco/vcnYPd7S5UExMyxC
    BL58PVG4PEFgMi091RVCOIn87jwpBHE8J4WFPD6yKjlMerc9h8S0OtV0Xj+31D4+H8eAPMH1NkM2
    3hE6aMG0QeYXQDxkMtNC/+tqPASgN0EvgIc8eUPUQCA/4zvSW5BARzSYO1M43ULPvz1Di3ixQ6PM
    I0RsXHpEl0fLRHhmJEX1OnJFGhyrRXbp2UdR7U093V5OPX4qTT2wdXc9fNugPRqQCD5rW0U+kpGF
    Po5OwT73JwM/sYqHPoFhM0MniqFCFEdEP3MDkT0AAAAAx2LGPonsWz/NFM48AAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAXyJLPwAAAAAAAAAAC0vNPmeOID/NFM48AAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAdzBbPwAAAAAAAAAAfU3aPtv6Oz8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8zdWPwAA
    AAAAAAAAfU3aPtcQ1z4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAU33VPnMDkT0AAAAAdpVM
    PpHpTT7NFM48AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7L+hPgAAAAAAAAAAkik5PhXpQT7NFM48
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC5SdPgAAAAAAAAAAAAAAAAAAAACpI+U7iP6lPjnjDz5S
    Z4Q8AAAAAGYyAj2pqZ0+AAAAAAAAAAAAAAAAAAAAAKkj5TuI/qU+z2wJPlJnhDwAAAAAZjICPdHX
    kj4AAAAAAAAAAAAAAAAAAAAAAAAAAE62iT4AyAc+AAAAAAAAAACsHpk7iG+RPgAAAAAAAAAAAAAA
    AAAAAAAAAAAATraJPkfIAj4AAAAAAAAAAKwemTv6i9s9AAAAAAAAAAAAAAAAAAAAAKkj5TtVTWI9
    eAw+PFJnhDwAAAAAhkbgPCHm1z0AAAAAAAAAAAAAAAAAAAAAqSPlO1VNYj01Zhg8UmeEPAAAAACG
    RuA8otqjQEjAKjvZwQFA3L0ZREN6I0Re1U9E3BWGQLXZTz9TvwQ/37+sPqM2CD552ok9EPYgPXuh
    1zyFT4E8koE7PP5Pwzp7Lh85f7XKOAyMKjjxfO43relsNx2iMDf0UBU3GEIfNysZCjf2ZIc7pEyE
    QVtGhEBfJro7hmLiOW/A1UXNBfw9jKdSQgcwdD1223M9Zth6PdEjfj3MYIQ9TnuJPWvrkT1FHJs9
    9j2nPYjsfUPxmmk90vNqPhF/dz1lDYY/zq5+Pay5SEBKR4M9M7PFQDIvij0FkqdCxIMORkOSfj8+
    WzpKTKQHQ09AnUQFf9pEmUq1QIorAUA=
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
hidden_sizes: !!python/tuple
- 1800
- 1800
input_dim: 1613
learning_rate: 1.0e-05
task_type: CLASSIFICATION
