feature_means: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADIxNzY2MDQzMnECWAMAAABjcHVxA01NBk50cQRRLoACXXEAWAkAAAAyMTc2NjA0
    MzJxAWEuTQYAAAAAAACxXLRBNEeJQVs45jwnPU4+OWUVQrzKHUDaa5tAOWUVQs+Fpz+IhohAQ06L
    QINtIj5nOx9AID0PRLCsj0GhVd5Ane6WQSNPnEFKjz9C5oPkQQAAAAAAAAAA6m71QEakmkEAAAAA
    kx6nQXqckUD/AvE/8keYPgAAAAC0eR8/ikuGPqHZPz1bOOY7hGlwPzdq0UPXu9JDdhYZROuhFETg
    5AtEKdIBRGQf80NYwtdDjtezQyg3LENNgFdDsBGnQzvatkPS469D+SCpQ/W1nkNPdJFDH2d/Q2lN
    ZUPVsihD0m6XQ6XMq0PRWLdDyXOuQzkBqEMNFJ9DWa+MQ2RLrkRS5bNEyAYFRWuKD0VBiQpFTHYC
    Rcg2+UR6/OdEFtHIREGDsUUPca1FEaj9RVCoBUZT//5FI2/vRbdF5EUH19NF2se1RTV8MkZkxF5G
    dQeiRnygsUZFn6tGHgClRpsEnkZw6pFGPkx+Ruycu0NDPMhD9DsoRBrCUUT1kVxESs9WRNhVS0T2
    YkNEfdYzRPNTmkNVtqhDBjEMRFWOLEQmRjREjfcuREAEJkTI1h5EcGMRRJxmmEN85qRDUsAJRPDC
    KUR4tjFEUo0sRBisI0TOkBxEgVoPRHdMnEInm8FCmIsPQzW/IUNY9B5DvhUZQ+e4EkMWzglDjGHz
    Qnnw80WtY+tF401ORquChEacO45GyJOLRnxhg0bd2H5GxbJtRvBRDUGfLQZBYrbqQOZntkB9raJA
    OQmZQFxQlkD15YhAYzVxQKG4Z0CQ8IdAEcV8QMcqXEAyN0lAkrREQBDsQUCqUTZA2asqQGCamUBV
    /lVAya5kQLlyT0CECFJAbUJLQKpMT0C2xEtA1k1CQNxf7UG/LONBkWLKQVnSrkEyw6BBdrWZQRUL
    mkE/R5RBO1OJQeqJ8kKqO9tCbFjBQm9Fo0KedJRCRXGNQoNYjUJSp4dCQcp4QrB6cEOIi4xD4Ml1
    QwfDVkM2QEVDW+tAQ7fqQUO1RjhDK0IrQ6jo+kCyiftAJhv8QOQ5+kB0rvlAlVH4QP6y+EB+TvdA
    lsT1QL2PzkAbC9RA0EvSQMwbzkBMacxAtnzKQEQcy0DdE8lAk37GQC7qy0AVP89A94zOQIOwykDd
    bslAu5zHQDE0yEBdLcZAy7bDQPKg0j+nFvQ/I4HZP+wewz+GRLY/48myP0//sz/kDq4/zqikP0bU
    IkP7zxNDhyYaQ1KKHUNiYSBDOv0gQ6yfIENcPyFDHdciQyxJcz+Yswu/yOIXPjpbBr42osA90b1J
    vPUiqL0IgJo9mlkqvZV3QUNbo1dCcOfaQfh1wsH6+6HBX/3OwVSkI8IfRLLBgbglwSKb60F9+BxB
    HYw+v6kEoMAPD2TAECI5wJuno8CNv4TA1NInwDzwlEIlO9rAZzOjQSt0wsDLZYnA1dDewIpLA8Fr
    m1G/BFsOwFMH70PEV8JBIPIXQnGJOsKeKTHC1a3CwU9fd8L4UbzBnquBwbjbD0UcU95CTG05Q0lB
    XsOiFlHDpbzTwvOgk8MULejC8qyewphZEUUVszNCZpzdQpJti8PQiJPDNTyRQjo1dMOFe5TD5ndD
    w8vqekD54j2+aO5DP5iLF78FlIq+psnsvnpH6b6ztiU+F8cNvZ3CxECPFwO+GPyeP3HQX78/+e2+
    +9Ukv5GOW78RGDU9bS09vXRN00BXN4K+oRC4P10Pe78FdO2+sFU5v2H5Yr9TCdc9TUS/veMLP0G/
    L2K+noMdP/TPvr92EbW/dO2TPnSSRL/zbYy/haKbv8WvtEL52CPBaAL4QBs0hsE+wQXBH5AFPptz
    7b9hhRXAwKEQwbS8ozwQWTG83VHlOkgenLrd1GI6tIo/uY6BObrAVEA6R/XxuUW/gEA4nYU/elOh
    PsNSer4PzXS+cB+GvpTnzb7cY2m+DIa2vdB/HT9b2kc+F2b4u/rpUb2Tax+9MO0DvYJhVr18fzS9
    HcK4vPI0xT+tTAy+6vhrPvksb72o7Cq9/LGDvck4ob1e62O8C1m9vP5AI0Fylt4+Qx7iPoHT5L5n
    yOu+aqmQvjUDHL+IA1q+aM8ZvhcnRULquv8/8q4JQIpLCcDctwvACLSgv4HbOsCCSYa/2fk+v9+w
    QULbUYY/+2yRP+RGLcCxs0DAgHGXPj3jCsD/BUDA9X/WvxsNpj1J1H27Oi8TPExzr7vPLjC72uWR
    u+r/lrtki806kbkFuTREAj7jakO70jhuPAfE/bvwXKe71FXRu7OCCbwNLvk5UuYPudq3Cz77nK+7
    ShOKPJzlDbyuH6S7vwPqu1XPD7yH2WA6weM1um38fz6BRiO7uHXTO31EdLwBAFq8jc8xOqSC57s5
    CT+8/MMvvJSP8T+Iwzu+gAOmPewqJ779Dpa9KySRu25ZmbxOgBS9L8CpvcZoB79Ev6M93bdrvVnI
    Hz3Aog+8DYAFvcWnDz1uMbC8PsuFPmrQmj0LoXO9SYxvvSTHhL0vaM69kTJ8vc5uy7xSc6M+RbNK
    vAo5qb341oK9PSZXvdTusb18IZO9qgUSvZIEsb236989nXkLvW1TqbytjkS9lyhdvSbUS7zq5aa8
    AgNIPcO+ST3hSD+9Ox9nvSafAL1u2Xq9Ur3wvG7mfLxyMkU9az9NPTc4P72JMGq9WSr2vCwld70t
    n/e8auV9vJPFsTx3+7o8MFxova5Ggb2xkqg7p1Y1vXDqd73qagu9ZCYyvbB+vD0aUIK92gz3vCsa
    a731LXa9xvEpPAugCbwmX5G87QTFPfCAdL08qBW9yDBVvc+0jL1Tl8q7xibeu5i5C71EXNE9vBh+
    vRfOAb1wlmG9pCCNvShml7vBkSG8q/JRvHbK0TzGh3q9B1dmvUmLVzv5Q9q88QJDvX94Mr2dOsq9
    6xEKPc9mrL0lNyO9yyrpumiRirzUiqe8EyIbvRpkyD/qRHw/ulWOP4ZNgT+kKYQ/u7CDP7CLbD+n
    9XU/+OIBP/gtVz/TYYI/qeSEP8B7hz81dYo//4mDP+9PgT+s5T4/iq+TP07Qkz8iGYg/qhiHPwiP
    hz+s/38/uAJ0Pxv1NT8jkxw/eTtrP+hvfT9kuoE/ehqFPxR1ez8r9X4/7UwxP7qRSD8RcXg//5CB
    PzWEfj/lMoE/TQmBPzCIhj9w6zA/Y6tHP+3Sdz8IWYE/+LF9PyYJgT/CG4E/YZOGP/umXT/yYWE/
    kjx/P9wagj8wgnY/2cqAP2rzhT+CeIY/yGZFP/8iST+9soE/+1CBP8umgT+zsIE/Z59tPwdMdz9b
    WDg/FQNCP8NefT8aFYE/1QSBP4wZgz/XN3U/DAN8P+AaQj+D6UU/SYKAP6SZgT+Y/IE/7fSDP7yx
    cz/GNHk/C1J3P1iEaz8jaoM/I12CP7FAdT+h73o/cTeCPw3bhD+P2pc/6hWCP5eCiz8NhIM/mP50
    Px8Yez/AEXc/B593P88l4T6jnOS+aJnGQCvZgz+y+1tAzFJ/P/RX00BW3Yo/h+ZOQSqYtUDIYtdB
    BcU6Qft2skEgdmVBJ+dwQAJvG0CiemdASuEOQBD1a0C0qgtAXuUUQP79NT8a/3dBTYgsQfv+rD9h
    RoFD/PsBQ9EXRENDBYJD3i0KQfz7AUP4Uto/PBCnQAiYQD4fripAjS45QxUvykDn0cVAYlaBQ9kK
    AkO0LERDIBeCQx1BCkHZCgJDaMXZP3wOp0A2lkA+c60qQLYuOUNPL8pA29HFQIzZpUOonCRDGRZ5
    Q/P9pEPzaC5BqJwkQ1dxHsDG8qZAAnRAPoOiKkDw1TlDgu3KQK3wxUCVl4NDqEEEQ7klR0P8NoRD
    b3oMQahBBEPqMrE/3wqnQOCRQD4YrCpAv145Q19jykBH2sVA12aCQ64eA0NqWkVDShODQ7RLC0Gu
    HgNDw5TAP+sIp0Cuj0A+W6sqQHpkOUNJacpALdvFQPbUgENNnQFDYf1CQyORgUMXvQlBTZ0BQ09s
    0z8rBqdAfYxAPkyqKkBxbDlD8HHKQIXcxUAWdLlD8Lo2QyUzikOYqrdDJLRBQfC6NkPQ463AkKmm
    QCsfQD48hipA3Ms6Q+n5y0CFGsZAKOp/Q0axAEMfTEFD/aaAQ4/DCEFGsQBDgI3KP6X3pkD+e0A+
    v6QqQAysOUPztcpAH+fFQOx8i0Rr6ktCKDr9QZIn8kH2L5A/80E2PSNPnEFEraVBT3cjQi8WIUEp
    yTk+a7bmPed6GT1bOGY8AvcsQINyM0FVVhBAJEwDQN2wiz9NfQ0+odm/PGwUOj40UTk+LpaZPCD5
    SDxgYPs9+2jfPvE0LD8ulpk8NKYuPCV+bT1sSho+uWRBPr0kA0B/4Ik9rs3rPmGL/TwsK2s/73yN
    PKo5Dz407Zg7JnOPQD1z4kCw1SlBppnfPz5iEkDMnDVADASgQQspXUG3kUpBKRMpQeLfDUF8BuRA
    wtedQBTdaUCALjM/wrTfPvmakD5L1zY+8NvoPT2dlT237D49pK31PLQSgUEBERlBF03oQFsspECL
    qGRAhGkYQHSArz+eI1c//X8QP2JMmj5kEiU+fgqwPSOkOT0vL8U8tuhPPL4n3Duc8gpCaBAFQuoj
    AEJNOUJCVsQ8QsgpP0KovAZCMetXQjVEOz+XkDM/SjAsP6LVgT9cfXw/aqh/P5rnND8CM5A/GnMd
    RGtvnUO/zeBDGnMdROzTqkFrb51DAAAAAGgFqEA3wEE+wg0rQJ8LNkO2isZAajfFQHuJlEUhK69D
    ISsvQ5wwg0MhK69DSbE6QSErL0OfLKdAF7tAPlm5KkDJLzlDxS3KQI3RxUAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAABTYpQ/53qZO6LWDkAAAAAAodm/PCg6DUF5pcQ+AAAAAP4IUz0J02A/dLq7QAvH
    nD/nehk+AAAAAOd6mT4AAAAAAAAAAHHJkD9YSow+53oZPQAAAADnepk75oD7P5gG3z4AAAAAJz3O
    PgAAAABiFws+lRiFPyVGIT8Qr5Q9tHkfPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAA53oZPfwUFz4AAAAAraDcPYpLhj4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACh2T89AAAAAAAAAAAAAAAAAAAAAFs4
    5jsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFvoDQG7UjTzm19E/AAAA
    APbvHD1CYHpBVerrOwAAAADoo/Y9B394vpNHVEB/NXs/TzL+vgAAAAC8gd0/AAAAAAAAAAApL1VA
    nxhTP+0dsD4AAAAApEGsPCu6CEH2/F8/AAAAAAxoND8AAAAASKykPxUbTEH+AlxAqzbMPjSnBUEA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOUebT0NBV0+AAAAAHNZ
    x74dzcw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAXJAkPgAAAAAAAAAAAAAAAAAAAABzYG48AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAIJA6j9TkWxAHIw8PwAAAAA17s4/RTn2P9NvTD0AAAAAoz8RQFBDQ74W
    MGc/BZtSPykST8AAAAAAAIS5QAAAAAAAAAAAOQNEQI/DQED14BJBAAAAAL6oj0AuK49A+cEDQAAA
    AADfTuc/AAAAAJDfF0E4dEZBYr2wQKHHr0DfV1lBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAABEwcU/ejS7PwAAAADN5mbAENnDQAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiXW0AAAAAAAAAAAAAAAAAA
    AAAA9YgEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABvC9w/U5FsQHhJ
    9z4AAAAAgBLKP96awD+LUt28AAAAAF3hD0AM672+DuX4PTD+Oj+T00/AAAAAAMm5t0AAAAAAAAAA
    AHUFOUBsREBA9eASQQAAAAC+qI9AxHaGQAxb/T8AAAAAfcTgPwAAAAAxjxdB04VCQcL2rECJbK9A
    U6JWQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARMHFP4cKuz8A
    AAAABvtmwIapwkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAIl1tAAAAAAAAAAAAAAAAAAAAAAPWIBEAAAAAAAAAAAAAAAAAAAAAAQ7A6
    RGJHWUFyovM+BBvpPfyhrD5oAzU80+AeQhTnsj/CN5dBiFMpP+SJpkGiejw/U2KUP6s/JD1c969B
    cgxAP9jFvkAgcFQ+g/tRQtw/5j8LKV1BA+33Pqv/80EEMIY/QYz7QDKrjT74br8+zGBPPHC9OT8X
    Ss48ZpAsOrCZyjz4CiE/2mlYP8U04z7HmA0/JIhOP1nCPT6MkZs9JvPfvVUbHj0sIvU/xziZPcaT
    ED+30xg+AAAAAKgNYEMa0P8+xiKyQK2d6z/cC9M/+09lQKi9kUBGQaRAqjenQNK6p0AxFp5CIxAt
    Q2IcXUMXMnlDqap9Q6GYfkMOSJk+ATQmP4nxUj8DtW0//v9xP920cj9iy48+bPwbPxb+RT8rEF8/
    wBRjPwLAYz8mk3hANJL5Pwt3ej9DtMw+BE6dPocblT4lioxBUwgQQvXULkKz6TVCz802QsAAN0KX
    LLhCA9dNQsC0/0F/KdhBhC3TQePu0UEQi61Bqu4bQSB+p0B4qDU/B9wzP0/3v8AaV45DdyAnQ9BD
    YEE5n9lABxUOQXd6jUBkSAtA9IOpQRxjJUKxlN9Bre+BQQ6HM0EtxYFAtWyCQCc1Q0CmUzNBHuZJ
    PsnjdUGKVsw/rg9hQaRmkkFb3YFCAAAAAMVOUUFwtj1B578CQqtx5ECrA4xAtHlwQVNAX0LzoKg/
    tIWCQQAAAABDSk9BvZNmQFsUykC6aiVBrG+jQSyt2kF6aylBk9WwQZrB40HSa8BBetcVQc/+AUFl
    /HtBZ0+TQYlJ9UAnU5FAsVf3PubyV0F/dyFArZD8P8F8Bz/ABrU+FCQoQP6+KECMMlg/jI49QSKg
    rUFM2/g/K3wMQZox2z+9AAY+rtW+PpSLmj6t0M4+YWwMPl/lUj8cR30+58y4P75Tkz/EFs0+bf5q
    QoSgA0AfcnFBDTsHP3eZLkKEmsM/Z/sVQXk/rD5GK11ArfbtPTqU0T9qgF899ywzQs77bELnfZxC
    jEXEQsBA1kL7F/hCKTENQ8MuGUPP9SJDkqSARAEdcECOL4xARkufQMqPskBKrsNApw7NQPNh2kD5
    ZedAz/7wQDhS+kDtmBBBvAJhQuPG2kEI2YJAikuGPQAAAADN/oU/O9o8QP4I0zwAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAC8VRNAAAAAAAAAAACpsoI/qqygP/4I0zwAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAACOOWBAAAAAAAAAAAAdcE8/h10sQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADCN+k/
    AAAAAAAAAAAdcE8/s3+BPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG4hU/ikuGPQAAAAD1
    NXI+n+WDPv4I0zwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADXzvU+AAAAAAAAAADV1Fc+uGd5Pv4I
    0zwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDckM/AAAAAAAAAAAAAAAAAAAAAFs45jts5Ak/RKos
    PopLhjwAAAAAiksGPZcMQT8AAAAAAAAAAAAAAAAAAAAAWzjmO2zkCT+WEiM+ikuGPAAAAACKSwY9
    jEUkPwAAAAAAAAAAAAAAAAAAAAAAAAAA1871PqqsID4AAAAAAAAAAOd6mTsbeSI/AAAAAAAAAAAA
    AAAAAAAAAAAAAADXzvU+53oZPgAAAAAAAAAA53qZO7hn+T0AAAAAAAAAAAAAAAAAAAAAWzjmOwrQ
    bz2h2T88ikuGPAAAAABbOOY84Zv0PQAAAAAAAAAAAAAAAAAAAABbOOY7CtBvPed6GTyKS4Y8AAAA
    AFs45jyc9JhAPTwVPqgpfUA7ettCknClQnB5sUJYSrxAX9JOQH3jA0C3XtI/Zr52P+PtID9uI9w+
    7HeZPnr6SD7Qswo+iag7Ppg/lT20XTs9BwMgPfBPyDy/koc8nwNPPKFpKjyT7AQ8JLDLO/uv1j6t
    nWtB/gjzQKFybz/RCPc+ew6oQzgyvkAoOv1BwEKgQByru0B/BNhAEQT0QNlECEG1ZBZBK7MkQVvl
    MkFfO0FBS+8IQ8ZehEAgmfg9Uu6uQIw8EUBHr99APYqHQK+cCUHvjMBAxx4kQatRmUKGjcdDyaMG
    QcK0JUVfJjRCBOsYQ9u5NEP/WQhBKD7HQA==
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
feature_vars: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADIyMTU3NDE3NnECWAMAAABjcHVxA01NBk50cQRRLoACXXEAWAkAAAAyMjE1NzQx
    NzZxAWEuTQYAAAAAAAAa4dhBLAwiQYZG4Dx2+Fk+HxSQQiVAPDuGHQ88HxSQQq+rgzp/3Gk9b2Ao
    PqMWXzr78dQ96UX8SHGjvEMRcJI/x7++QTCfzEHwmhRDifcsQgAAAAAAAAAAAuK/QA37IEIAAAAA
    iOnBQXoeLEAgcPw//YGWPgAAAADNWKU/h2WfPh5LNz2pI+U7gjrCP8ZnVEZ9Bh1Gtd3TRtKl5kYA
    rgpHbLAOR0fEEEcUKRRHqlgUR/SYzEStTiNFiILVRSprH0Z1FS5G7CNBRizESUZy0F1Gk/djRkJI
    EUYeAr1EZdAyRhhNMEZOAYdG0fGFRtKphEYPq4pGHbh+RqrNd0jzjQFIKEWRSAgDy0ht5OZIAiry
    SI9eA0n+kw5Jdm8NSUtHtUoTCPRJ64eHSkXWt0pY19BKYGDYShS76UrWB/5KmHv7SukV0krPEipL
    1VC8S1BYCUw+4RpM4notTEXQQUwspE5MnS9RTEgnDUZwjhxG5V0HRynseEd4O6FH9S6qR79Zp0fj
    pr9Hdy7BR1j8vEUAittFlhK4RjilJEeq61FHL39eR5ziXUeP6XpHC/Z8R61eu0UVn9JFyF60RkJN
    IUdkIk5HG5xaRyQTWUd+KHVHr952R1QvqkMpVAZErESaROAT7kRCjglFJwwWRYYPJ0WI9DhFinQ5
    RZx/fUoIPV1KkHNeS91d2UtnKBJMm50XTBSEEEzZ8SlM4wsrTFLeGUBcXrA/rPkDQJZSuT+TBrw/
    JOndP/Ue0T/Vot0/pbjyP6rpdT0wvYg9lt+ZPcHHlz2BaLo9J+XOPUOx0T3JwPc9d2oWPjV9MkBc
    v9k9GkBXPxOBmj7D4eU+ETndPsz/9j6hMxA/4qcEPws280LddSZBvIdkQXw6gUGpMppBg9OYQW7g
    jEFRcrdBR6rZQe3+TUXFqT9D4wiGQ44RkkMmyrFDagGxQ1mGnENXJcxDZd/6Q6hRpkM3coFDIYPh
    QxqxzUPq3fFDasoMRCYpH0T2iS1Ec/A/RBPmiD0dA5E8ziUjPTksGD2tR1A9jC1PPWfTYT2TPoc9
    N4hwPciwrz2Xzac8nqpKPbLFNz2UTHw9XB+BPRzTiD1vG6w9CS2iPdGZwz0Yrr08MYVlPViROj1s
    CYM99zCGPaZJjj1h0qo9waGePdEc4DwTUoE8YkG/PMmOmjwehL48VEjCPAzt3Dwl6eo8sR75PMTg
    jEFeei5Bm1THQUtMiUFr47ZBPJOkQSD53UGEIc5BG+zWQb5d/j2k93494bCVPTNmhz27IaU9akGm
    PffPoT3YUY49tOKGPcm1S0VS4hREjtqNRBjG7kT/iglFP3BCRXhzLEVz92ZFE6wFRWEngUKcwY1B
    Z12uQdY09kEu6wRCutwhQlfLN0JZUzVCNrcBQpTQH0USyEZChwSURPcdnUMkZSdEscauQ6aP80Pi
    LTtEo7+KQ2WOuUeoQ29EAEFSRQldEkYLfTpGrVs0Rt3nUkbx43hGksEpRh2NL0pZXYxGuSWRRxss
    UUjtV4VIdOR7SCMenEgtvK9I/qJvSGF1vUjWSgVGNRYMSCr7HEhZgVNIADBQSEfUc0gBpJxIwPtE
    SAeTf0BZtIs9TJwHQL2pcz92xbU/Ii2LP1V8oT+tJOc/RpJ6P4N6AEG9YPI98yKHQBH5CECLZ1NA
    mM86QHXJS0AJ7pBAi9weQHmGL0FgIR0+X22+QC8ULUCwfIRAFkFVQLBldUBVo65AVEw0QPumUUFa
    9Fk/74WTQCM1m0BAnLxAuNDCQIqn5EAEAt1AJQm0QP+BhUQhRiFDaVASRNictUNvM8dDLCS3Q56G
    6EO77P5DdmfrQ0fYDTjtH6o3kPQmNwU4uTaEeN82ntkEN3FdGDfWPA43B/4VNz6obT7F2QQ+3wwU
    PoIZIz6Lw1Y+YgKDPsL7ij7zxAw/3nGyPmunhzugpa47lz1OOy/WSDvZf3I7L1yMO7tbnDvODek7
    2AzFO7Dscj/Xz5k8tOodPrTjxTw2jjs9+IbMPHZpTT1kirg9WLMePa6zZUJ1fJE+TJThPq3waj8m
    G5g/HO2dP2kd+D/XOyhAbjH6P9za40QhIqlALDYcQdvxrUEJzdpBxOrgQby+O0IzzHFCcc40QoaP
    x0DbIodAUayrQdDndUGnnZhBMue0QQASyUHSJGhC4NUaQiZyojp3dAE4DkqTOR2cmThMaOI4I7Ws
    OC9IFDlVUm45kUAWOVZYDjvxD3I4GJ4ROi/5MjmGp4c5lehxObCgtDl4Vhs6awC9OettUDvTaZk4
    DHNOOsKgXjniuKc5PWWIOe8m2zlYkzk6s0DQOX1wQDvmN785FsAyOkTR/TksQxY61MouOvJzTzpD
    QJI64sB1Oi4PeT7qr4U9QFGrPeXcAj0OlP48adoPPUMaQz1wyXs9AK9qPev+bDzLUKc8zjxKPKsD
    bDzxioQ894qUPCCFiTxzGpg8NXkFPJFWCDxFexk8d0hOPMqcdjy2XoU8v5sFPRRIqzzzvV08mIQL
    PFrs+jt9JCQ85CM/PKHMVDzq9p48VMx/PJMPyDutkoU8Zf31O6CpSTwHXB08eLlPPM1/zDzD6XM8
    8CopO15krjsYIOc7yjsdPI7mSTxWeUI85qkJPXG/pTxyJBU7lqquO/UU4zulFxw8+XdHPL4yQTyk
    ywk9RCGmPDQX8zqrYxk84mXaOzXjBTwZHCg86eouPAho4zxgSI08araiOxUZnjynNg88sb5XPHAI
    QTzitIE8mw/RPP1zmjxDxHM7jBN+PDkTFzxesFs8d9dhPBvKiDxqDPo8z7esPEDYgzs6j5E8DsQb
    PJr9YzykiVg8yrCOPNYq7zxtDqM8CD/QOwU9Ojzv8v871kgDPDZFNTxZnEM8rx61PJ/vgTxhPac8
    E7WDPO737TsrWwk83EYmPBEqSDxRH3E8M/ljPGt30jxSxE89QhviPGyIGz1wPSA9mgNaPaZAUz0i
    Qlw98teVO13zdTxjyy48JkWBPH7erDzEg9s8Mp4kPeLk0TxGP4k85lV7PCOcVjxz2p48SxOxPPAM
    zTwaQv48ogEHPfEXDD2y2dg8k7bpPKWvaD0L/7k9kYryPSn6Ez49zvg9IFEmPPQmcDwnaBk8EAuL
    PEV5BT0aWQg9qKkjPY5eFT3VECg8KRpmPJcbEjzufoM8wocAPfFCBD3oViA9XGcPPThvNTxMVw88
    vLXTO9W5Ajy9rEE8QH8rPE6FozwjPWQ8T7KmPOBlWj0Qet08QLUjPY3DYj1Z2449l1nDPcmglD28
    3kc8tB4fPeeHwDw75v48G+QvPZ04Yz0/sp49tiVnPXR+bjwIgTw9vyfePENlFD0w1049vpyKPfw1
    tz0rXIE95ifnPH+VcDyyVCI8LwBhPHk3rTwHjKc8S3fZPOFRvDybyjI9s+l+POuANjyhlyU8hhN/
    PNAnrjzfydw8WXjCPIYiojoBY4M7QxfRPqPXqz7/xeY96qBvPMWPJUAdqA8+oLdLQo/NUz0oxolD
    Fy2JPm/0bkCKFUU/RUQsPU8gLTmyIZs986ZIOfkAxT3DUU057FB3PjwSlTzuDN8/FdidPck4UT1g
    pF1GoOVeRUrEB0atHV9G8p6dQKDlXkXxtU0/CoHAPnUGFzrUPwg+sntzRfv1CD9/g7s+NxleRkc7
    X0Um3QdGWotfRk++nkBHO19F0L3YPxiEwD4KGhc6hj0IPtZ7c0WsKwk/qoe7PlBRz0Yhd81FNix8
    Rsr0zUY9+iJBIXfNRcR9hz/3tMA+MkwWOn9hCD4/z3RFo6QIPy30uj4mcWVGQ9lmRUTOC0aP22ZG
    JregQEPZZkXZPZk+HmPAPpr1Fjo8Pwg+0RV0RWUBCT+3gbs+5iRgRjOlYUXycwhGcqhhRulNnEAz
    pWFFxMK3PndcwD659xY6Xj4IPvgqdEVaGQk/ZYm7PhkKWUbvq1pFFw0ERsivWkZqepZA76taRU3M
    3D7wW8A+1fQWOvo+CD5GN3RFYiUJP66Ouz4Z4QlHswUHRmIlpUb/5wdHHlhoQbMFB0aMsgRBd3LA
    PoHrFTqRawg+DW53RSPiCj8BDbs+LjVVRkuWVkXvAQFGHKBWRpLtk0BLllZFUq62PvQ3wD5T9xY6
    GDsIPq7tdEXovwk/va+7PkDIs0daKSRDjKdSQru870IXZp4/fI4uPTCfzEHWNMRB6K0DQ648xkAP
    8Ao7+OV6OmwTFD2pI+U8qwy0P/VChUHSMAlAuB13QKqeQkD5EP49Bcy7PJYIlDx+zJE8JKe8O1cx
    MTtZqCQ8HoJuPOFYBj0kp7w73kkDOzcCXzvq2XA7uqrSOwHeJD+uaYs8RlyCPVPk2TusMCw+MogG
    O7MhHTyu70U5ZrDiPw3nhUBr/SxBRmP6Pp46XD/jzM4/eDCuQQCRH0F9tBJBhfC8QFEJiEDZf0JA
    aSjZP7hriT8OGVk5Krk1ODonkjidcjk45AoDOPglqzcgKlg3T6juNtmIakGSdbpAxCCCQJTeDUBd
    aZk/0VkdP70fij44gPo9l709OjZ/BDo35aE5rkIHObEJVTingY83K8zxNnjoMDbTDIlCxJp9Qr1C
    Y0IOFBdDIv8MQ6dyEUOgo4BCNlJBQyCwujtPguQ7KgmNOk8HYTmNB8U5sIDZOZEChzrZwEI53EJd
    R18xXUaaovRG3EJdR2hoU0FfMV1GAAAAALjuvz7DcBw6HmsHPqnRb0XjCQ8/sZW/Pj5U9UqwfL9G
    sHy/RWRaZ0awfL9Gg//1QLB8v0VcY8A+zv4XOu0ZCD7tKHNFjr0IP1vkuz4AAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAABel5k/rB6ZO27UsEAAAAAAr5YXPUh8GkGmIcs+AAAAADwpgT2vjqQ/JM59QGf4
    nD9yNBE+AAAAALwCoz4AAAAAAAAAAK/Ohj+XaF8+bBMUPQAAAACsHpk7H/mTPy0h4z4AAAAAPr2y
    PgAAAAB2GAI+US96P2+lTz91cZ09zVilPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAbBMUPanmBT4AAAAA2u/OPYdlnz4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeSzc9AAAAAAAAAAAAAAAAAAAAAKkj
    5TsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdht+QLsRgz0/nZFAAAAA
    AK371T34gxBCWKSAPQAAAADFzMU+gEQ9PkFmeEC+VIA/lOoOQAAAAABgkypBAAAAAAAAAAAWdg9B
    rgb/PxJEQ0AAAAAAtarCPWxmskGyYeQ/AAAAAMEShT8AAAAA8Oo1QfcnE0OqX8FBwz0WQIPiZEMA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOEZtD3My5E+AAAAAJyE
    rT8mYzlBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAJUAHPwAAAAAAAAAAAAAAAAAAAAB1xPY8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAFgEST08SiA5NVOxPQAAAACnh2U6rvGrPNtPPj0AAAAAaSSEOzPrWT3J
    5Us9agnQPOho/D4AAAAA/TqvPAAAAAAAAAAAUeRRPUVZQzxnLJQ7AAAAAOc8ZTowj1M9focjPQAA
    AABb/9c8AAAAADiO0DwFbkQ+RHw3PV6dkDwZHgk+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAACITdg6HTiEOwAAAAC3Pdg8WnQXPAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACaTxjoAAAAAAAAAAAAAAAAA
    AAAA4EkNOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACnIGg9PEogOaIf
    8D0AAAAAgV1gOjb1xj04xks9AAAAAF0vQDvAGoM95m6aPk0huTwzp/8+AAAAADtkuDwAAAAAAAAA
    AL0ruD3ZjT08ZyyUOwAAAADnPGU6+342Pc2gWT0AAAAAZWINPQAAAADe3t08RP5bPtJOTD0cZY88
    jKbyPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiE3YOndwgzsA
    AAAA1s7YPKTjBjwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAmk8Y6AAAAAAAAAAAAAAAAAAAAAOBJDTkAAAAAAAAAAAAAAAAAAAAA/8zy
    Ry00GEEZTGc5Bw1RO7hV1zqFoPA5kJefQgeaOjxsyqFBuGdAOjP70kHhv1Q8i7YGP5hwBjqtfnZC
    UiWEPPjwMEBOlyo6HYWOQ3hNDT0AkR9BcEcYOFprv0LtGXU8SiZSQOw2ODrbGFE9UHIxOA2RfT14
    JPo3SSWINz7ALTmq8AQ7r0f3OtH/mjbN+pY6IMMOO5dgCDsA3f454nyeOm4PKTr/WVZBWXmDPPkL
    zDr4C8w6AAAAANKcF0Z+nJ07GdxUQHHHkT9h/Ls8D8KwPWJA6z1o8Po9xPMAPtjoBT5tEehDFuog
    RaiSkEX3DrRFJ2m6RR0Cv0WjSpc6ampFOygX9zqXYro6EzvDOg8ktDqYrnI6axknO1VE1DreGWc6
    t7ZgOskiUDrUVyc+nmkNPgwvjD3C40E98KVFPT52Mz3S+KdBCrzvQdM+60FA+utB9ArrQaA160EH
    /tNDX2rhQrBLuEGdskRBdFE0QSIZK0HFe/BBAivzQLkiUUAMglM+93pWPrhcIUCwx4lF4Ze1RITR
    aEJfOstBSAxNQqlYCEI/lpFBuvJYQ7dXjkPO6i9D5EzAQpoehEIQQAJCD9enQQfwj0ExLYBCzh6A
    P3vlFkJd0RFBZZ0wQ4IqUUOz+eFDAAAAAPxnwEIVy2NC2xGEQ8vfVkJItwJCb8ckQyn4rUMrUftA
    A3faQgAAAAC7uN5CHTvlQX/5pUKnkphCmbQ9QwrfkkPGysRCmPWAQ+Bg10PLpjlDYGaEQvOmQUIF
    sKBDIIOuQr8mzkGyhG5BbZfqPxLO9kHu+uNAI4qfQLO5VEDYFxg99QugP4dxyj+9ydg93tLlQTEz
    LEIEvnw9Ubg8QWAyLT3VFUI4ifzuPCkEcTwnhYU8PrIqOUx6tz2HxLQ61XReP7fUPj4fx4A8wfU2
    QzbeETpowbRB5hdAPGQy00L/62o8BKA3QS+Ahzx5Q9RAID/jO9JbkEBHNJg7UzjdQs+/PUOLeLFD
    o8wjRGxcekSXR8tEeGYkRfU6ckUaHKtFdunZR1HtTT3dXk49fipNPbB1dz1826A9GpAIPmtbRT6S
    kYU+jk7BPvcnAz+xioc+gWEzQyeKoUIUR0Q/cwORPQAAAADHYsY+iexbP80UzjwAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAABfIks/AAAAAAAAAAALS80+Z44gP80UzjwAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAB3MFs/AAAAAAAAAAB9Tdo+2/o7PwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADzN1Y/
    AAAAAAAAAAB9Tdo+1xDXPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABTfdU+cwORPQAAAAB2
    lUw+kelNPs0UzjwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsv6E+AAAAAAAAAACSKTk+FelBPs0U
    zjwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALlJ0+AAAAAAAAAAAAAAAAAAAAAKkj5TuI/qU+OeMP
    PlJnhDwAAAAAZjICPampnT4AAAAAAAAAAAAAAAAAAAAAqSPlO4j+pT7PbAk+UmeEPAAAAABmMgI9
    0deSPgAAAAAAAAAAAAAAAAAAAAAAAAAATraJPgDIBz4AAAAAAAAAAKwemTuIb5E+AAAAAAAAAAAA
    AAAAAAAAAAAAAABOtok+R8gCPgAAAAAAAAAArB6ZO/qL2z0AAAAAAAAAAAAAAAAAAAAAqSPlO1VN
    Yj14DD48UmeEPAAAAACGRuA8IebXPQAAAAAAAAAAAAAAAAAAAACpI+U7VU1iPTVmGDxSZ4Q8AAAA
    AIZG4Dyi2qNASMAqO9nBAUDcvRlEQ3ojRF7VT0TcFYZAtdlPP1O/BD/fv6w+ozYIPnnaiT0Q9iA9
    e6HXPIVPgTySgTs8/k/DOnsuHzl/tco4DIwqOPF87jet6Ww3HaIwN/RQFTcYQh83KxkKN/Zkhzuk
    TIRBW0aEQF8mujuGYuI5b8DVRc0F/D2Mp1JCBzB0PXbbcz1m2Ho90SN+PcxghD1Oe4k9a+uRPUUc
    mz32Pac9iOx9Q/GaaT3S82o+EX93PWUNhj/Orn49rLlIQEpHgz0zs8VAMi+KPQWSp0LEgw5GQ5J+
    Pz5bOkpMpAdDT0CdRAV/2kSZSrVAiisBQA==
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
hidden_sizes: !!python/tuple
- 1800
- 1800
input_dim: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  lgAAAAAAAAA=
learning_rate: 1.0e-05
task_type: CLASSIFICATION
