feature_means: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADI1ODMwNjg0OHECWAMAAABjcHVxA01NBk50cQRRLoACXXEAWAkAAAAyNTgzMDY4
    NDhxAWEuTQYAAAAAAACu3rRBXouJQf4I0zyh2T8+7+kVQjqqHUBPW5tA7+kVQveMpz/1mIhAio6L
    QONQIj6qgx9AV8EQREFkkEFLXd5AmAaXQYxFnEHjj0BCv0PlQQAAAADnepk71871QJ/lm0EAAAAA
    csanQZYPkkAPtfY/EK+UPgAAAABt4Rg/zAF3PqHZPz1bOGY8WzhmP+rh0UPtEtNDAToZRMIkFUR3
    yAxE3eECRNOi9UPvV9pD5u60Q92wLEPGH1hDMoSnQ8Wot0Oj0LBDrCOqQ/wRoEP3rJJDKbGAQyse
    ZkPjVSlD1W+XQ3fmrEN5J7lDKBOwQ/e8qUPaT6FDRyGOQ0hYsERnn7RELiwFRZLHD0XTEAtFMmcD
    RSzl+kQnPelE9VXKRG6FtEUpJa5F4NH9ReXQBUa8DABGd0zxRWa+5UU89NRFWE+3RfgeM0Yvl19G
    iH+iRoA+ska5U6xGETOmRvRBn0Z4zpJGpA2ARhx7vEOEKMlDVgopRNRYU0SJ6V1ENPJXRHxqTUQK
    X0VE+Ss1RJv+mkO9dqlDFtMMREzLLUSJVzVEj/MvRE6yJ0TtbiBEDXoSRB8SmUOCo6VDDWAKRLMC
    K0SQzTJEfYktROpXJURnLh5Eq3MQROwNnUKFZsJCWQ0QQytsIkNPkB9DmAAaQ+DVE0MjigpDXgf1
    QrEq9UXzfuxFkFhPRlaxhUaiLo9GUzCMRt7ChEYN2IBGs3JvRpXMDEEsvgVB7XzpQKKStUCWhaJA
    tkqZQBcDlkDk7YhAW+luQLMiZ0DvqIdAGiB8QE1cW0B1/0hAC75EQAh2QUDx8jVAS1IqQDMDmUAu
    yFVALw5jQFQET0DZalJAbsNLQBwqT0DnnkxAQ+VBQGc88EFY9+JBHK7JQWfnrUGbrKBBbhyaQYyT
    mUEO25NBwz2JQSBC90KNENtC3aPAQslgokKfiZRC8veNQlXqjEJUSIdCZQR5QnwqcEOlZoxDU0Z1
    Q1XiVUPz5kRDkDVBQ4tsQUMKszdDpOcqQ+e3+kB6c/tAB+z7QOQX+kCGmvlA+lX4QBiI+ECfZvdA
    can1QCVVzkDU79NAKRTSQIjrzUBQTsxA24nKQFjyykAMKMlAVlnGQFaxy0DFJM9An1TOQPCIykD1
    W8lAPa3HQHEMyEB5TsZAVZfDQLfG0j/M9fM/VjzZP/SBwj/UAbY/7+uyPzqQsz9TX60/HoOkPyPE
    IkMpxRNDsRAaQ8qnHUMZaiBDq+ggQ4qHIEOSaCFDgNwiQ7S2cz9nHwy/1PUZPgUtBr5Vh8M9wuh+
    vHfevL0Xo8M9n09WvfpxQkNjtVhCWFvjQaYdtsFWXqHB9QDiwT1xIMIZZqfB4yNGwfQH7EENYxxB
    I2pDv2ubmMDqV2HAv583wJTjocAL1IHA9MciwC67lULVeNrAzBeeQXnVycCtOXLA4j39wNAbC8Go
    tcA9X8cbwGQD9kNSKcpBoi4LQi+JQMKkbiHCEJLNwbAgesJzsKXBKc56wUw8FUX0q+ZCyXcqQzUX
    Z8NlzTzDvcfewp+ilsP4LM/CAU2ZwllCEkXVUzBCOtC6QqJ6g8MQT4PDIzxYQgWAgsPS/orDrVI9
    wyzyekDdwDS+brk+P/YzG7+VvYy+/H38vol+7b7K8WI+n7aHvQHixECRZvS9c52bP/P2Yb+e3Oi+
    5mc1v5XRXL/YJgY+PU7OvUyF00Cu73y+Uj20P1mkfL+H9uW+35xMv4ABZ7929Es+DkMSvngqQUFD
    QHS+Inz7PuG4s7/yPJ2/vPJlPlAdZr8y94K/rXCLvzFjtELAOCTBAGzUQNhmgsEGqujApZQEvlpy
    VsBJwsC/IXwIwaI6ozyo2DC8A7XkOnbrmrplxmo6zl9juYvGTLr+EWc6mmUHuk2jgEAgtYU/+E2k
    Pvknab6Z63C+gT6NvluWyL7bZW6+67bjvU3mHD+OY0Y+dwsCvJGKSL2xUB297AsDvRAeVr3YezG9
    zX6svJJoxD+Jawq+UolfPphib73L2RO92wyQvZ6Yob3CGDW8+QvWvGJEKUGH+eI+zw3PPveg8r4t
    4da+k9SKvjoJIL+Aal6+qaQGvoSVTkIwJgJAg9/8P14TE8A1Iv2/UhGYv5IqQsCN94q/4scmv6v6
    QUIv8oM/dDZuP0pWIsC+yzHAasNRPghYGcArVDnA2a++v7rgpD1V7HK7clwMPHXNsLvepyy7OxKW
    u5B+lbu8duw6f9sJuk9sAT4ZcTe7n+pkPK0c/bvLpaC7yyncuxIsBrz5JCs6lMtHuvnVCj7qZam7
    QqyEPJRjDLy/D5u7jyj4uwvmDbx8/4k6N7qmunwogT47GjK7dy+mO2mRZLy3BkO8m9fjOTpTErx8
    vTO8UHkMvIab7z+5OTq+pQ6GPTwUHr4UzIS9xOSUu6egHL1MV968wgCZvUOXB7+q5KM95OJmvYwX
    IT37byG86MURvVzwKz2gjtG8/7uFPnZhnj3jO2S9YZZrvUbKir0Ll8m93hiBvRH997wyn6I+45pZ
    vBOBo72G3IG9W7BVvW6bsb0NFJG93wELvTV0sL3R1N09Y+sIvXphprwCqVO9N3pavf+GVLzIrK28
    +k9OPeifOT00+j29z+FfvVytC70X6nS9PDzzvCapXbzNAks9ENk8PZfKPb2xgmK9Ay8GvZv3cb15
    g/m8+HVhvOLZrTwA/pg8ZfRYvd4Ib72hTVY7kiVJvQeIb73csva8edErvXZFvT2keoS92OH6vC6B
    b73sSHK9FzsxPA3tTLyiMIu8FOHFPZJsdr0aHxW9qfpcvUm7iL32Oce7ToI/vP/kCL0pZdM9EpJ+
    vfHy/rxIJmu93LSKvSMrkrvqonO8itJpvOZApjzbEmq9q4lTvQvOBjtWsgu9zD03va6rFb3ev8m9
    PvTbPEtlo71h7xG9b6YVuyJS5Lwr7Hi82FsOvREryD/uqXs/hHqOP7/YgT8+G4Q/U7KDPwrBbT97
    a3g/k84BP9E2Vj+MEYI/gxeFPyPVhz87EYo/elCEP3w8gj9WeD8/hvCTP6SVkz+xlog/Lf6GP595
    hz/A0X8/ukVzP52uND9nPBs/U9pqP29Dfz86sII/TSiFP92kfj9rGoA/KPYxP80KSj8lhng/bCqB
    PzT+fT9cdYA/0GOAPw7AhT+0mzE/VSpJP2z0dz9C7IA/0DN9PwRjgD+GfIA/ptuFP405Xj+YsWI/
    XnV+P4NygT8WUHY/03iBP/BbhT9M14U/E8FEP+oCSD/D6IE/+eqBPx+fgT9wOoE/UPtwP3u3eT+9
    Azg/XCpBPzv2fT+xhYE/KjKBPx22gj/XE3g/kGF+PyuPQT8RmEQ/2LGAP//9gT+hQYI/UquDP+AV
    dz9D53s/PFR4Px3kbD+T1II/s7SBP8mrdD8Cb3w/nRiBPxiigz+pIJg/VfeCP1sGiz+9MYM/G611
    P2yIfj8Lj3Y/jtN2P1sC4T52ZOS+bofGQORJhj8T5ltAmz5+Pyzx1EB/54o/vWNQQTeYtUCjzNlB
    BcU6QeKlskGGeWVBbvpwQLpuG0AseGdA3eAOQNXwa0CopQtAO6EVQEzwNT+lzHdBdossQSwerT8w
    RoJDsfkCQzZ6RUP7A4NDM6wKQbH5AkM/Zdk/HVCnQOxaQD758CpAmBk6Q4dgykD2BMZAD1eCQzgJ
    A0Pej0VDlhaDQ07ACkE4CQNDzrPYP0xOp0AHWUA+RvAqQPwZOkMDYcpA9gTGQBcTp0Px1CVD29h6
    Q6Q2pkMNBi9B8dQlQ6b7HsCKMqdAcTdAPmXlKkAXwTpDbR3LQFMjxkCBo4RDLE0FQ2efSEPJQoVD
    //wMQSxNBUOENrE/8UinQHhSQD417ipAsE46Q2iaykBEDsZA3HCDQ1UoBEMb0UZDPR2EQ2jMC0FV
    KARDcKrAP79Gp0D0T0A+Xu0qQDVVOkM0ocpAUA/GQH7cgUOZpAJDuXBEQ7yYgkMuPApBmaQCQ+Gv
    0z/AQ6dAX0xAPjLsKkCxXTpDmarKQNEQxkCeiLpDl843Q6f0ikNzvbhDQytCQZfON0OAHa7AY+um
    QInlPz4ByipA8bI7Q78jzEAdTMZA2uuAQ2inAUOin0JDfp2BQ6EzCUFopwFDVW7KP6U0p0AjO0A+
    beYqQMSfOkNA8cpA1xvGQGjAi0Se6ExCNfX9QQfc80EQr5Q/UHFJPYxFnEE19aVBjEUkQtnCIUH5
    qDk+bnDnPfNBNj3nehk8fZAtQHmiM0H2LxBAZ/8CQBCvlD8lSRI+53qZPN4uPD6ufzs+6d2fPARR
    TDx/qPU9AUzdPi58KT/p3Z884wM3PJILZT3LdBc+0ko8Pgb2AkCwmok9tsvmPlwy4jy8KGw/LMmV
    PHkkDD68wZU7xsaOQFbw4UDfXClB9gveP6qiEUD2kjRAiYigQWTuXUENCUtBlk8pQdMhDkFnSORA
    3cWdQIPmaUB8LTM/stffPku2kD7yETc+3lvpPaXtlT1sXj89t172PGiDgUFH0RlBV0HpQI87pED4
    5WRAvJgYQNdArz9iA1c/W40QPw2Vmj6KciU+cBSwPcznOT1Fc8U89B9QPBlm3DuBdgtCro4FQhSp
    AEIOMENC0a09QjUYQEKuVQdCOglZQlgWOz/nbDM/LwMsP2vKgT8eXnw/14l/P63RND+lLZA/7UIe
    RHEynkNJBeJD7UIeRJ70qkFxMp5DAAAAAMRDqECff0E+t08rQLP8NkPbycZA/mzFQO8rlkWcYrBD
    GGIwQw4KhEOcYrBDEzc7QRhiMEMTbKdAB31APvL7KkCGHjpDkmPKQFkFxkAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAABTYpQ/53qZO+xiEUAAAAAAodm/PMgWDkHqbtU+AAAAAK2gXD31OGM/WEe7QDT7
    lz9iFws+AAAAADnjjz4AAAAAAAAAAEmVlT+f5YM+80E2PQAAAADnepk7mQD9P+Ch1j4AAAAA/gjT
    PgAAAAAlSRI+8UqJPy8TID9t3qc9beEYPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAOeMPPXaxCD4AAAAACtDvPcwBdz4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACh2T89AAAAAAAAAAAAAAAAAAAAAFs4
    ZjwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2F4DQG7UjTzzWdU/AAAA
    APbvHD3k4ntBE/MmOwAAAACo5/k9VYJ3vrABUkCfyHI/pwvivgAAAACJdc8/AAAAAAAAAADk+VtA
    MLRFP/4R0T4AAAAApEGsPP2gCUHA9lc/AAAAAOhXOD8AAAAA6bytPy7hUkEdZVlAJIzlPla9AEEA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIqjWj1jXUk+AAAAAH4+
    1L5iH7w/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAACJIkPgAAAAAAAAAAAAAAAAAAAABtMu48AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAJMY6j9TkWxAGmc8PwAAAAA27s4/2/T1P5JRJj0AAAAA4+4NQLkPQ76d
    ZmU/gy1SP8F4TsAAAAAA85W5QAAAAAAAAAAAvAZEQA4BQECj1BJBAAAAAL6oj0BARo9An6cEQAAA
    AABScOc/AAAAAA2XGEHRskZBE9CvQOOurkCZ5VlBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAA5J8U/b4e8PwAAAAA2GWLA27HDQAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEOZW0AAAAAAAAAAAAAAAAAA
    AAAAX28EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8zto/U5FsQGfg
    9T4AAAAAgBLKP7t+wT+uBiC9AAAAALsbDUC8Ir6+ifXyPQW1OT9ZfU7AAAAAAJC0t0AAAAAAAAAA
    AEBcOEBDqD9Ao9QSQQAAAAC+qI9A+XeGQPKT/j8AAAAA6IjgPwAAAADWJxhBj7RCQSGLrEBWG65A
    fBJXQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0b3AP/5YvD8A
    AAAAyCtiwLBmwkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAABDmVtAAAAAAAAAAAAAAAAAAAAAAF9vBEAAAAAAAAAAAAAAAAAAAAAAtfY7
    RID+WUFqsfM+jFPoPRv3qz5VYzM8UmUfQkLesj9Hm5dB5DEpP10vp0Ghijw/9DuUP2rcIz0ftrBB
    BzNAP66yv0BizVQ+1v1SQt925j9k7l1Bd/n3PoxF9UG8U4Y/HCr8QAWJjT4ov74+dPJNPFZYOT/X
    Mc088yhjOuVeyzxptyA/uzRYP7su4z7Gag0/9mhOPy+APD4TZZo9SZvevWC8HD1ZQfk/5MWaPXe3
    ED/wRBg+AAAAALfpYEPqqP8+xSi0QKPQ7D+TutI/tLhkQBqtkUA2XKRAZ2inQBj4p0C0up5C+Z0t
    Q8NDXkPtvHpDk11/Q9YxgEOO35g+L5AlPymXUj8MlG0/Ff1xP/jCcj98cI8+emsbP9KyRT+R+l4/
    NBtjP7PWYz+xKHlAkJr7Px+vfD98bM4+c6mdPl6ulD7ek4xBwNoPQp7CLkJQ9jVCW+o2QjYWN0JB
    6bhCXMZOQn40AEJDK9hBN+jSQf+40UFQSq5BWBodQcgqqUARqTI/EakyP8v9v8A48Y5D5KQnQ08B
    YUFilNtAto8MQXQ/jkCF5AlALhqmQeh1KUKk7t5BtIyDQTfYLEFFA4FAXpWGQKevTEDaBjRBRMFv
    PgvTd0Gn28Y/cIFmQWRGkkHsXYJCAAAAAMV2UkGtdD5BO4YDQtjE30Dz9o9AfZB3QRsBYUIGFJs/
    N9+BQQAAAADVPE5BVjpjQMFYzEA3NSlBGsimQYvW1kGneiVBZna4QUoY4UEyb8FBouoQQepLA0Hb
    7XpBJV6UQVY//UDR7I1AYhjePiJ0WUFwhilAUOb7P6cz8D5Nybo+xCQpQK9aKUAuV2w/HStAQT6W
    rkEVi+8/9V8MQYoW0z+O4zg+PrbAPiD7mz6APdM+1ecKPoATWj8W6Xw+Eoi5P37bmD+0ytQ+Prxr
    QvubA0B26HFBX+wGP7M5L0LHuMM/aH8WQXLiqz4YMGJAXyHzPafryD+PHlY9g3IzQssHbULpcZxC
    YRrEQnPA1UIXjvdCRKoMQ9fLGEPdsCJDHHOAREpEcEBwNYxApUCfQAt4skCXlMNAxtvMQGAm2kCf
    GudA4M/wQD4f+kCHfhBBSQJiQtFc3EHYxYJAYheLPQAAAADsZYI/jzM+QP4I0zwAAAAAAAAAAAAA
    AAAAAAAA53oZO+d6GTvilRJAAAAAAAAAAACPM34/G3miP/4I0zwAAAAAAAAAAAAAAAAAAAAA53oZ
    O+d6GTtyxl9AAAAAAAAAAADLCko/v0MtQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMBOg/
    AAAAAAAAAADLCko/Z/+CPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8FBc/YheLPQAAAAAy
    BGs+gH6HPv4I0zwAAAAAAAAAAAAAAAAAAAAA53oZO+d6GTvhm/Q+AAAAAAAAAAATo1A+pM17Pv4I
    0zwAAAAAAAAAAAAAAAAAAAAA53oZO+d6GTtPdDo/AAAAAAAAAAAAAAAAAAAAAFs45js45gA/MBAv
    PopLhjwAAAAAuGf5PGQOOD8AAAAAAAAAAAAAAAAAAAAAWzjmOzjmAD+BeCU+ikuGPAAAAAC4Z/k8
    LxMgPwAAAAAAAAAAAAAAAAAAAAAAAAAAKDfsPpYSIz4AAAAAAAAAAOd6mTu/Rh4/AAAAAAAAAAAA
    AAAAAAAAAAAAAAAoN+w+0+AbPgAAAAAAAAAA53qZO/4I0z0AAAAAAAAAAAAAAAAAAAAAWzjmO0Sq
    LD2h2T88ikuGPAAAAAD+CNM8Jz3OPQAAAAAAAAAAAAAAAAAAAABbOOY7RKosPed6GTyKS4Y8AAAA
    AP4I0zyumppADFYWPkT5e0DVMdxCgQenQhFPskIfZ7xAUR9OQHEfBEA6ldE/P4l3P7fTIT+689o+
    +36ZPqPsSD7aVA0+wjw7Pu+3lD0gYjs9ELcePVCKxzyWeoc8ZW1MPHD1KDzMpwI83tPMO3fz1T4V
    l2xBxSj0QIpTbz/W+fY+4v2oQ3BNvkA19f1BCU+gQNuxu0DABdhA2/7zQIU/CEHrWxZBj6ckQSrW
    MkFGKUFBcRsJQ2BxhEAy9wA+7/iuQDfZD0C1st9Ak2mGQGeaCUGeCL9A+RckQXVPmUJWTMhD34kG
    QQjGJ0WAgTRCjTwZQ874NEOKnQhBMQvIQA==
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
feature_vars: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADI3Mzk0OTUyMHECWAMAAABjcHVxA01NBk50cQRRLoACXXEAWAkAAAAyNzM5NDk1
    MjBxAWEuTQYAAAAAAADYpOBBHN8nQc0Uzjx9u0I+P+uUQoRhOjvS3RA8P+uUQtRWhDojb209Dccs
    PkklYTon8dc9CDH7SI1ivUOUYpY/kmrGQYCp1EGQjRhDZQEzQgAAAADnehk85OfCQNgIIkIAAAAA
    tE3GQQsiN0Dsavs/5GyXPgAAAAAPDZc/sgaaPh5LNz2dhGM8rRa4P42PV0bYZCFGT8/YRiqU70br
    PhVHt1oWR9uFGUfj5htHzqIbR2vS00SuBylFhIDcRZqVJUaJtTVGNmdKRpC3VUYCPWpG8sluRhIH
    DEbzOcJEKZ8rRqttMkYCSo9GDLeMRoyHi0Z9HJFGlW6IRkMqk0hFWwdI6fmTSMdgz0gEsO5ItyQA
    SYVTC0nB1hRJj0oUScu95krPu/5JCW+JSv1qu0r3GtlK5bjlSpVR90rCJgRLhgYES4wT2ErPxC9L
    +nnCSxuBDUziYCBMC6U2THtaTUzFfFlMSBxbTImIEUYqNCFGQXcLRzTBgEdOm6VH1W+uR7GBsEct
    xcdH38jJR+/rwkUdEeJFP769RjJHKkcpF1hH6+xkR61kakdq1IJHT1iER3dKwUWM3NhFN+e5RrHU
    JkeDR1RHmt5gR+VTZUd1gn9HPSyBRyh9rkNw+ApEJe+eRHd+9EQzmQxFPxkcRWEfMEWWTUJF+BtB
    RVZIgkrdYmNKA2tkS6mO4EunTRVMz78ZTDPdF0z4nDBMOL4xTC5KDECpuKs/nSj1Pww/tj9eUrs/
    Mr3UPyg1xz+sTtI/uTnpP5Hrbj33joM90/uYPXfOlz2str09/urHPRl0wT0NbPM94K0aPu0GG0Cv
    89c9PhAwP3VxiT7q8dU+QwTPPoOU7j430QM/uOr8PiQjLUP20itBTwdsQbTehkHzI61BvUupQY0K
    j0H6KrtBiPPuQVWCmkXuQUlDsI2MQzrpmUO318xDXkHHQ1Z2oEP+n9NDKdwMRObtq0Ow94JDXyPl
    Q4uezkNvpPZDT3AMRKUkEERP3iREMCxJRDAneT0kmIo8/LAVPTTMFD0P0EY9bm9PPYNqXz0Jc3k9
    nVZrPX4znz05SaA8/dg2PRQJMz15HXQ9QmGAPaJPhT2Q8ps9+WahPYmzrz16frY8NhNPPceuNT2l
    E309/u6EPY81ij0iJZk90SebPaDZBT21cYc8lTrIPDDNoDzMC8Y8DHjEPFHeyzxjcOA8TiMFPe3Z
    hEGLZytBzVHEQWIai0HDQq9BJ4amQZXwy0GwqMRBemfUQWz1/j3gXH49BmCWPRVGiz1LnK89Eh+8
    Pbofrz3Ag5E9hRWGPbPiUUWMmRVEMaWPRFBV+UTPvgtFQcNGRRgvMEUwgG1FOvYHRfaPhULehYVB
    YuW0QUBs70HdVgRC5gsjQhSAP0JRZTJCm8LxQUADF0WE7j5CfZ18RF6gjkNyti1EPUKpQ73c9END
    MSJEY+KKQwCI+EfwToREDQNWRbL2I0ZQNT9GJDc1RiL9YkbW+4FGQH4fRvcZdkrnQ5tGx/+SRzrJ
    cUjAmIhIctB9SIagqEhmX7hI9jdjSPgjwEirTwtGGpAMSA5rIkh9L1NIxSZKSM1XgEhGmKJIPD5G
    SMgiekAIPok9mxLbP2G2dz/j0bA/kBCPPwP+oT9dBtU/qvtjPzJb/EAoNuY9hSxfQC7JC0BYHExA
    M0k/QKKVUUAuBoZAXEkTQHmAK0GCAhU+sEmdQMlTMUDsLIBAfS1YQPQjfUD9hZ9ATeUqQIJebEE3
    v2U/MIiSQBITlEBePLpAf8u/QAad50AsSNZAtjKzQE2tg0Tw6ydDHM0FRMoPsEOcDsBDlia1Q9WU
    3UPzAgBE7BflQwtkCzjSbKU3Jh8oNwvCujZVEus2TyAQNzdsGDf8WAc3s8MJN3rhZD6FyAg+VYER
    PrcnJT7zKlI++FyCPjRbjD6v3P4+MCDFPkdSgDsWfqU7nwFWOxmWOjstBHI721yKOyS9nDtQetM7
    DP3HO5XzVj9bros89UwBPuvuqjzlEEI9y5a7PNEUPj2Pro896BQePaLVr0Jn3Zc+4XbnPgyokT/x
    GaQ/RbqhP2oJF0A/jCRA7fn8PwWQNEXc/bBA2FwfQdrW4kEnHu1B68foQZ6mZkJ5knFCO2Y4Qmjz
    wUB0w4ZA1XSoQTeYfEFpwZdByC+jQQyx3kFh0EZCutIyQrJYljrvcv03EJZkOTPblThwgNo422mq
    OLbaDTnKmEU5ZFoLOZGQAjuZjWk4ajPmOUckMTnhaYE5EzlvOS9gsTn2FwI6Kx+3OQfiPjuOEZM4
    XjUjOhahXDm7haA5UveEOTk61jnJZhk68GTPOeAWlDumpMI5hL8nOrNr7Tl3wRw6oH4qOjhlZDq3
    JXs6yU2QOsQZXT4cOoU9SPaZPefD7DzITe08cFgLPaeFQj22qGc9UBFrPRJeaDy0eac8jphIPPcE
    dTyO7Iw8GXmSPA7bgjyuNJI8yqAFPOMYCDxWaxo8Ev1JPCXWdzzHvYU8VIP2PDBgvjz3wFI8oQgS
    PIZj7TuGrCQ8II45PC2MUTwLj488fBmBPPijujulgns8+yn1O5hiUDzw1hs8vnZMPL2ryDzxBYg8
    oh0wO3Sksjuk8eU7uW4cPGdKPTxdzUY8Zlr4PH81sDxKCxs7LliyOyvw4jvLDRs8qvI5PERRRTwG
    5fc8EZ2wPMDH8Dr4lxY8oXXdOwNcBDzzlBU8GzNCPMCqwTyR1qI8ihGeO6UmizxkTw88JuFZPLL+
    STzWe38834TQPHIAmjwU4Gk7e85iPOMZGTyXOFo8ublqPBeOiDy56e88te+1PIGyfTsw84I8dEsd
    PKIdZDyl/V88196NPO3q6DwMrLA81WXRO6HPLzz6++s7Jqz/O6/CJTzMh1o8yvGVPGWXlDwWUKY8
    tP93PLIg1zu8pgM8uy4kPE6uUTwsiGQ8YwtyPBXgyjwwQkg9T4njPJjBIT1jbh49YXdGPZTiVj0V
    fFw9kwaPOy1xYjwnyzE8Q1F5PDjorjzbvts8aVAgPe8o+Dwk2388GdGDPGK3RzwnPKI8WkKqPGO4
    xDwS/fU8FsANPXfzBT0SIcI86M/uPDfPcD3NvLI9pxX4PS10Ij4ntQ0+NmAmPPhpejyFlRY88XKO
    PH4CCD13Nwk9kLMdPXenGD2e0yc8XDNvPLHODzwoZYY8ns4CPdQYBj26cxo96lwTPYQcOzw0hAk8
    BQvMO8hb/TtDRyw82vlEPO8riTzxg4g8jsShPLDXQj1p2dw8nQ4rPXLXVz1Cmos9z8nQPTm2qj1g
    GUA8z7wOPT1EvzyXjAA9HporPcJOYD1txKU9zdGFPZt4YjwF7Sg9jOXbPJk5FD1f9kc9e6KIPcGA
    wD2hfpo9tZT4PGBZbTzurw884I5ZPPnSrjyuJbY8OdW6PO/MzDw6YTU9i2RzPJdXHDxg6RU8x1B/
    PAC3rzx/L8c8sWjXPItomTptU4I75+LNPpeUuj6A0ec9JYJGPMlBGUA2/RE+P9Z4Qs3TUz2l/qxD
    7y2JPt3FjkC6qkE/PxYnPWC3MTm9npc9Pz5NOeKHwD3dCl05jwGcPuPwkDzoD90/9KmcPe2ZWD2Y
    fmRGgcllRQNdC0YUCWZGVTKgQIHJZUXgcUw/xkHFPlK4FzryUQo+ibR+RQHsDD8Id74+ae9kRiAc
    ZkW4dAtGzXJmRg9QoUAgHGZFQtTXP7FFxT6Vyxc6yk8KPkizfkVMIQ0/UHu+PjcA1EYaGNJF3ISA
    RsKY0kZiFCVBGhjSRTrEhj+0XsU+PzEXOoJqCj70G4BFEN0MPycAvj5o221G7lRvRcVMEEbqVG9G
    a1ykQO5Ub0UiUZY+0C3FPqiXFzo4VQo+Ymd/RVbnDD9Xar4+z6NoRuA1akVg/QxGnDZqRuQEoEDg
    NWpFheqzPhUoxT5klRc6GFUKPgKBf0VO/Qw/0G++PhiIYUaQPmNF9JgIRmQ/Y0YnM5pAkD5jRU//
    2D4xLMU+oYoXOmhXCj5JjH9FBP0MPypwvj4SVQtHJW8IRvdgpkYuVQlH0MNoQSVvCEaVY/9AYQbF
    PonmFjpIbwo+24CBRbBEDz/6Ir4+zT9dRkqzXkWEOgVGcbleRncXl0BKs15FGL+zPtAKxT6Aghc6
    blUKPkEogEWMjQ0/lIq+PlgXvUc6nyhDCgpaQhXZ8kIDzp8/OPw/PYCp1EGCKM9BvcsFQ7id0kDz
    WBM7noF0OnyOLj2sHpk89ya0P7QuiUEHbAxA7DptQCpNT0BXfQI+R/WWPJOjlTySFJQ8s7PDO2rR
    LTvEKSE8+45fPKvl8Dyzs8M7YfcIOz+ZUDvpxlE77PS1O7lTJj+d6oc8m0RdPaibYjuyJzo+hXMU
    OwtbFTxa5EY5tT3dP65ziEDoATJBGBj2PrBmWj+Kwc4/Ki60QSYGJUGFPhhBc7LBQIb3jEB+x0hA
    UfvfP2dGkD9kclc5tFY9OL0PijgH8UE4e78CON8mqzcabVc3bxvsNh3ncEFi1cNAvZaJQPWAEUBV
    Ep4/SwwlP1wNjz4TYQQ+pvpGOpgpDjow8qw56FMLOWADWTjNipE3nL/6NnmqOTZB5YxC6V+CQpEg
    akKXeRtD6zARQxDQFUPA8YNC55pGQ2e/yzuFCP47chGPOjUQTTkgZ7M5BBDEOds5kDqoZDo5ehNr
    RzJdakanEQJHehNrRwZIYUEyXWpGAAAAANsSxT5g/Bw6QIwJPtcCekUfURI/pnLCPlh6BEvmU8ZG
    +FTGRSdVbkbmU8ZG5C/7QPhUxkUFPcU+sZwYOusxCj7uan5FapYMPxXSvj4AAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAXZp4/rB6ZO7NetUAAAAAAr5YXPeVuH0GRGNg+AAAAAJ6xdz2UcKU/+BWFQDTB
    oD95k/o9AAAAAIaTnD4AAAAAAAAAAMz4iD9KuFI+fI4uPQAAAACsHpk79l6aPxeB3z4AAAAAB9e6
    PgAAAADJGgw+7gt+P+S9SD9U7sA9Dw2XPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAkWMePTYQ9z0AAAAA9dfdPbIGmj4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeSzc9AAAAAAAAAAAAAAAAAAAAAJ2E
    YzwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIYl/QLsRgz241ZVAAAAA
    AK371T1qOxFCGXSPPQAAAABwDa8+Xd41PlvYdEAG0YE/N0voPwAAAACf6iJBAAAAAAAAAAAy5RFB
    w0HuP6ABZkAAAAAAtarCPbZDukGLq90/AAAAABB0ij8AAAAAmUpEQSCMFkOSzLhBD4Y3QFNVVEMA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFBKtz2yCog+AAAAAOO0
    sT+nrTJBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAW0MHPwAAAAAAAAAAAAAAAAAAAAAatXQ9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAANnNST08SiA5M7q4PQAAAACnh2U6ia6lPCORWD0AAAAApi5KO8FXZT0z
    kkY9fJLPPDwY7z4AAAAAVL6ZPAAAAAAAAAAAMVdAPbBFKDzW/Z87AAAAAOc8ZTq87ko9xEoDPQAA
    AAC1a+Q8AAAAADuZzjxvqU0+Knc8PQJ9izw/OP89AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAABPAX0605xQOwAAAABmR5o8mU4APAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMWBxzoAAAAAAAAAAAAAAAAA
    AAAAYC2TOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADFoHQ9PEogOcRY
    6z0AAAAAgV1gOvkKuD3ku2k9AAAAAJVJFjuKsYU9SXuVPlSatTz3Je8+AAAAAPo3pDwAAAAAAAAA
    AEbjuj2nHiU81v2fOwAAAADnPGU6SpIsPVCjRD0AAAAA/m8TPQAAAACNI+k8qwdbPlx2YD1gIIg8
    jI/UPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJSiOOsNNTzsA
    AAAAlgGbPEyX6DsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAADFgcc6AAAAAAAAAAAAAAAAAAAAAGAtkzkAAAAAAAAAAAAAAAAAAAAA05v5
    RyS5HEFBi3Y5+nJeO9qp0TrsNug5UAOnQknDOjxPqaZBeMpFOiSI3kG7t1c8VkIHP29BCjplU31C
    NNOEPPfyNEBtSCo6TESVQ9QkET0mBiVBms0TOMldykLyNXk8badaQPJTOjoDUU49XyssOHoMgD12
    KPU3stjFN4tEKjkE9PE6DW3lOuxhnDYhGok6yA4IO9Aa+DrsY/45COSPOooGKTpJq1xBvrKGPAkf
    xDoJH8Q6AAAAANdLHkZeip47yXpfQJnBlT/xErU8zXy1Pcxd8j13gQA+BcMFPnXyCj742O9DOAYm
    RVYVlUUHwrlFGJvARYqmxUU8Y5Q64mZFO7/X+zo6i8I6kEvROoO0vzqxp246dqgpO0Go2zooVnQ6
    3Bx2OlWgYjpXMig+o6gMPuFXjT0/qUc97xlRPWoAPD10w75Bab4BQi5x+0GFHv1BLwj9QW6y/EF9
    X9pDGhvrQqITuUF7Ij1BcDArQaQ8J0HPgvhB8Dj6QAIvVkDUZ1g+1GdYPsQOJ0DSyY1Fv3O6ROov
    bkKlGs1BBaZcQq728kEwPJRB7IhfQxNum0NlUCpDXATCQsd/gUK+9AJCo5CwQRoLkUFvL3tCSQiX
    P02yIEKoowxB2Xk4Q/jiUkM8TulDAAAAAJ1uxUJ27m5CjkOIQ3YYT0Ic/glCjcksQ6O1s0N/2fJA
    u3vjQgAAAAAbd9pCXDLiQc0zqELCOZtC1pY+Q4M1lEOxl7lCiV6FQ8Y71EPreC1D4BV3QuqmM0L4
    lJpDO2+tQmB83EFGG1xBEsPqP1yC/EF9K+BAIUCXQHeYXUBtgyA9AQSbP6FS1j8woNw90qLvQf51
    NUJQ20Y9UtQ/QQogBz0o7b034Z8BPVwifTwJc488BewmORgbqT2ymPQ6iW9pP5ldTD7oxII841g9
    Q5WpEjqK2blBHaQ9PHcj2EJ3cWU8ledDQVlahjwrAdNAu9reO0qpiUAGGZU74CPlQs8FQ0Oz2rdD
    QQ4qRDZSgkSv/NVEpWAsRbL+fUUrlbNFgHXkRwtZUj0Oo1I9klhQPUk7fT3IqKI9wDcLPkmFST5u
    toc+CSTAPn1HAz+xYok+Y/03Q3rVpkL7lkg/4i2VPQAAAADOHsA+DyVeP80UzjwAAAAAAAAAAAAA
    AAAAAAAA53oZO+d6GTu87VU/AAAAAAAAAADXSMY+oUcoP80UzjwAAAAAAAAAAAAAAAAAAAAA53oZ
    O+d6GTvqzWQ/AAAAAAAAAACVk9k+hlU5PwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4jVw/
    AAAAAAAAAACVk9k+ew7YPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD339k+4i2VPQAAAAAC
    7UM+/PhaPs0UzjwAAAAAAAAAAAAAAAAAAAAA53oZO+d6GTvzsqE+AAAAAAAAAAAAIjA++fFHPs0U
    zjwAAAAAAAAAAAAAAAAAAAAA53oZO+d6GTu9O58+AAAAAAAAAAAAAAAAAAAAAKkj5TtHvJo+n3kR
    PlJnhDwAAAAAMWHyPIaTnD4AAAAAAAAAAAAAAAAAAAAAqSPlO0e8mj68Dgs+UmeEPAAAAAAxYfI8
    MH6XPgAAAAAAAAAAAAAAAAAAAAAAAAAA1b6GPs9sCT4AAAAAAAAAAKwemTtHkJM+AAAAAAAAAAAA
    AAAAAAAAAAAAAADVvoY+vHUEPgAAAAAAAAAArB6ZO8S7vT0AAAAAAAAAAAAAAAAAAAAAqSPlO1TG
    JT14DD48UmeEPAAAAADNFM48zee5PQAAAAAAAAAAAAAAAAAAAACpI+U7VMYlPTVmGDxSZ4Q8AAAA
    AM0UzjxEaKtAgT81O9uUB0BXgh1EkhsoROWYU0QFi4ZAWvdLP4OWBz/aA7Q+quELPsr0lD0zBCQ9
    ZH3dPApwhzzIbEo8aIm7OtkhHjkLbcs45yUoOJBb7Te8Nlw3HXkrN1/jFjcnQhs3fxMXNzAChDuq
    YIZBtQaHQKyQtzuca945Z0TbRc8AAD4KClpCeox3PbjRdj22in09xyOAPa9VhT12LYo9LICSPSV2
    mz3jd6c92g+DQ6NjbT3E5XI+b8B6Pe/chz9Wo4A9GURMQLA/hD3koMlAou2KPYlarkIGjRJG95uN
    P5v+Q0roAQxDyN+iRBzX4URlK7lAoGUFQA==
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
hidden_sizes: !!python/tuple
- 1800
- 1800
input_dim: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  SgAAAAAAAAA=
learning_rate: 1.0e-05
task_type: CLASSIFICATION
