feature_means: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADQ2NTkyNjI0MHECWAMAAABjcHVxA01NBk50cQRRLoACXXEAWAkAAAA0NjU5MjYy
    NDBxAWEuTQYAAAAAAADnTbVBZceJQbhn+TytoFw+aT0WQuyNHUDAPJtAaT0WQpKIpz81sYhAbbGL
    QF7rIT7ZzB9A0yIORDPLjUHJrN5AKyiXQe9TnEH/AkFCC8rlQQAAAAAAAAAABej3QIxFnEEAAAAA
    csanQYxCk0D1NfI/GnyTPgAAAADodyg/vUyAPqHZPz3nehk8zAF3P38j00OH4dNDkRIaRL8pFUSK
    jwxEORcCRErL80Npb9pDZIW2Q2UILUOxiFhDJMynQw+1t0PhmLBDvNWpQw67n0MVl5JDP0WBQ7JL
    Z0NEtClDmz+ZQ4jxrENAOLlDQ62vQ5d6qENx+Z9DCzONQ9iIr0QV97REv6YFRXy2D0Wx+wpFp8sC
    RX2Q+URUfOhEmSPKRPkXs0XRdq5FkL3+RXW0BUZk4/9FZ/rvRSZa5EVcTdRFfhq3RXZPM0Yl2F9G
    p7GiRmQmskbj+KtGunalRqtwnkYxWJJGHCGARjccvUPev8lDJ9MpRI3AU0SAXV5EpVhYRGwyTUQg
    qEREShA1RPCTm0Oe/qlD+YQNRL4jLkRJuDVEUEEwRIeFJ0RP4x9ET2sSRCmtmUPJLKZDQxgLRPFc
    K0SuMDNEn94tRK01JUR8ph1EmGQQRPj1nEKab8JCCBUQQzZKIkOOMR9DvFQZQ5wHE0OZGQpD9fD0
    Qo4V9kWgP+1FrnJQRrwFhkY7no9GrrKMRijQhEY9b4BGP21vRj1yDUG68AVBEiLqQC94tUD6LaJA
    o3OYQNGJlUBfJ4pABkt0QIgbZ0AroodAdrR7QH01W0BPc0hA+zxEQIVSQUAlojZA79QrQBDbmUDp
    tFVAnGRlQFDmTkD8hVJAhpBLQPOiTkBo6UtAP6dCQNtW7kFDD+NBQNrJQQ7UrUE/iaBBE6qZQTVw
    mUEbd5RBE3eKQZMy9EI8JNtC48vAQmJFokK8YZRCRnWNQkCxjEIJ+4dCnV97Qv7tb0P9QoxDC8p0
    Q9KeVUNHTkRDVmVAQyjPQEM82jdDG/orQ/cK+0D2nPtAJE78QN42+kAZx/lAxIf4QI3n+ECAbvdA
    K/H1QNWxzkD8HNRAJXbSQH4KzkDQd8xAeLTKQNdCy0BjMclAHLvGQEQWzEAzVc9ALcPOQKOoykCG
    iMlALN7HQKNoyEDlVsZAgfTDQAQq0j+GffM/LJLYP8krwj+SVLU/vRyyP9/osj92gq0/ARmlP6r9
    IkMx3xNDlWEaQwTAHUNIoCBDhTAhQ1vxIEOceiFDRtYiQzcMdT+/sAy/HioePr0UEr574c89B2vU
    uxeS2L1/zs09f3ljvUGjQ0O3s1lCNZDhQWQWuMHzc5nBFVHnweR1LMIUkp7BBzUZwTn360EcvBpB
    zylJv9vJpMBmfmfA6TUqwKQQl8DzPXbAej8qwKvLlkJAatnAmBerQZIEtsAFzDfA0mECwftLJ8Es
    Ln0+WGH2v/XJ8UNzhMlBiPMMQsXVRsKi1xrCOpLHwfHUfsLLh5bBwe5qwbD6EUVzD+ZC6QYtQ82y
    bMOq0jXDQcHZwisXmcOGwLvC4JeOwpFQEkUapBxCwEG/QvYejMMivonDJFR+Qjl/b8PFBIvDG7k5
    w8xkf0BhlTm+dZNMPySAHb9hwmq+8HQCv6LkEL+SI3k+ySsJve5dyECC0e+9a5+kP4MZZb8yg8a+
    PT05v5+pg7+17hw+LjzivFyV10AyDH2+t52/PwgWgL8crcS+2glRv8Orir9nlGw+ry6bvc5XQEH1
    y5G+8F4KP8D9v786fKq/wMSWPrdvOb+243u/WbmYvwg1t0ITajDBFNgEQfY6isGd5ALBym2LvYZG
    EcCckG6/g04XwY/PozzVMzG85E3pOmr6pLqGcXE6740UuZCEb7oNLnM66s4LustBgUDO5IU/mMmi
    Prv2br7dzWy+vUCSvv6P1L4lf0S+p7KtvUmVHD+uhEM+jY4GvBZsV70b0SC9VvL3vBHtP70sGiW9
    +ePHvJ1uxj9Z6Qm+8gd1PkKgX72ugP+8f/iVvWmrzL2Ykmi7NlyDvLRCJUHNSuQ+vaTPPhGH9b5D
    XNC++zePvl4WJL9cqgS+4/4Jvj1fSEIo5QJAcHr+P1BRE8B0+vW/fxSfv5ByRsDj5Se/LtApv6yR
    QULj4mo/VkB5P0yPLcBWnjXAGQRDPnzoCMAH4CfAxCjFv0MIqD0DrXe7RmkXPI2ltLs9Fhy7RDqd
    u2jstrsIkRs7amHWOOC7Az4UNTO76eJyPE90ALxzipS7oZHku3rsIry8QuA6BDirOWuEDT5EBam7
    EJiNPHHZDrxNqJC7RoAAvLGzLLxXVQ87fs46udkwgD5abna7ifS7O8atdbyMfUu8i4wPOjIs3bss
    oh+8gXQnvJTf8j8ZwUq+ANizPaj4Kb6QDpK9Bw//uxyHubxqCbG8Y3eovXMkB78peKU99Ql3vZGC
    LT1AXA28Q2csvasLPD003Ni8mUCFPooLmz0462i9ixRpvZ+Aj7388tC93oZUvXlUybz59KA+1aNb
    vI/Urb2z/YO9hFtLvd5/ob234oe9VVMhva7Mqb26fuQ9Og0EvfBnkLw0i1e9ytN6vUoYILs1KIm8
    2rZPPTQDOT0st0m9aPxVvT8HDL37d369EDimvNAXXrz1EEw9Ux09PXgkSb3P11i9pMAGvdqBe73C
    OK28nUJdvD1Qmzwl+KA8D8VpvY0IdL3g8jk7xpsyvSREWL0RVf+8oRArvWhuvT0+RYe9uzzrvEl1
    dr3Rq4W9ksu7POIGCLzuAYG8JCTFPdALeb0Edwy9iWxkvVBcmb3gsdQ73SCwu4QEBb3pwdI9z5aA
    vawj9bwtP3K9AtaZvaxkBjwbVhK8VHKWvH6CvzxxrXm9tqRavaJ9EjsiUNS8Gi8iveg7Mb3Q99m9
    iDUUPYyKrL0D/xu9DrNNu6OOnrxYBlO8WOkhvcxdyD8v3X0/wfOOP9cfgT+nf4Q/X/OEPyYyaT8H
    VXc/v8oBP38YVz9R5IE/QPCEP6YfiD+624o/24SCP8svgT9s/D8/TkuTPzcFlD/2j4g/D6WGP55l
    hj+ncn8/MAV3P8XtMz8Cfxw/VRFqP1OwfD9sZ4I/R0CGPyCDdj8K4ns/saMxP2dsSj/LQXk/UhOB
    PxFwfj/eVoE/Ytt+P+f1hT8URTE/EnJJPzubeD/I4YA/wLZ9P9g3gT/C834/pvGFP5McXz/TZGI/
    8qB/P8XGgT+J2XY/F8+AP/vwhD82C4Y/E2REPxAPSj8TvIE/qGWBP7ENgj+WhoI/2X5pP0uHdT9c
    Wzc/XNZCPzhAfT/RCoE/FJaBP4dJhD8BenE/+zp6P2QGQT8rg0Y/Z1eAPxOYgT8ikoI/tyGFP4/i
    bz+jnHc/Qdl5P55QbD8AaoM/fOiBP+SodD8+33o/igSBP7b2hD9K8pg/jM+BP1k5iz/tJ4M/k4F1
    P1SMfD9jEXU/Ump4P4Gg4T5rt+W+eYnHQHc+hj+MultAHGh/P9N81EC+nYs/7zxOQW+btUBB+NZB
    icY6QUNDskHBEmVBSm1xQAV2G0BxDWhAsucOQHqYbEC2rgtAzpYUQE60ND9vaXhBZ5wsQbriqz+/
    I4NDltoDQ7QMR0Om44NDnIMLQZbaA0ODnNs/p42nQGgBQD6EQStABZE6Q8mUykD7Q8ZAJjODQ/fo
    A0MsIUdDCvWDQ3SWC0H36ANDsDHbP+mLp0CW/z8+2UArQPWQOkPOlMpA50PGQMaQqEOlTidD3ld9
    Q6iwp0MBizBBpU4nQ9UQIcCxb6dAjdw/Pq41K0B/OTtDwlPLQNtixkAolYVDE0EGQwdfSkNzNoZD
    evINQRNBBkNcb7M/h4enQEL6Pz4tPytApcE6Q+7JykCGTMZA7V6EQwgZBUNcjkhDsA2FQ62/DEEI
    GQVDbkfDP4mFp0AO+D8+bT4rQDXHOkOsz8pAZE3GQPXEgkPqjwNDNydGQ86Dg0NQKgtB6o8DQ2uP
    1j/LgqdA3vQ/Pl09K0D9zjpDNdjKQLpOxkCmf7xDRrg5Q5h9jEN5qrpDvShEQUa4OUNoerHAPyWn
    QOuGPz4KGStA8jc8QwNnzECujcZAftiBQ1uXAkMQYURDGI2CQ1cpCkFblwJDTLjNP3Fzp0Ca4z8+
    ijcrQDMRO0PHHstAuVnGQM54i0RSZU1CsI7+QSNS9UGQMI0/lhIjPe9TnEGBeKVBAvckQi8WIUHb
    Kjk+ZszmPYpLBj1bOGY8KDcsQHDPMkHkiQ5AnPEHQAbilT+PM/49odk/PFXuPz7DNj8+wraJPIm8
    MjyTnfQ9qtfePhS3Kj/Ctok8eZEePMVkZT3o8xg+MCg9PiILA0DRf4o9NjLnPiPP9jxQQGg/+Th5
    PP5lCT5lIns7GqGOQOHZ4UDgyyhBTancP9miEED8bTJA0NegQRF5XkFahEtBhpgpQbN4DkG5eORA
    bW2dQJEeaUDCHTM/TN/fPpDVkD46Nzc+TNPpPVBmlj35DEA97Sb3PP+2gUEB9hlBGgvpQG+VpEAP
    YWVAyIQYQPKJrj/ox1U/NXcQP+Rwmj6vLCU+GXWwPRGJOj25XMY8QzdRPPCG3TtAwwtCZdUFQsvh
    AEKfuUNCMDo+QrepQEKffgdCCK5ZQmImOz8FeDM/e/ErP4zcgT9Fi3w/hLt/PxqhND9fRJA/04ge
    RIaGnkOAFuND04geRDvmqkGGhp5DAAAAAB54qECBGkE+nJwrQG2YN0NpK8dA/rPFQKqPlkVJerFD
    SXoxQ8MHhUNJerFD9kM8QUl6MUO3qKdAaCJAPiZMK0AvljpDTZnKQL9ExkAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAACqr5E/53oZO1s7F0AAAAAA53qZPNu2DUExCs0+AAAAAKHZPz3BOlo/Tnq8QEmV
    lT8QrxQ+AAAAACVJkj4AAAAAAAAAAM77lD+9TIA+iksGPQAAAADnehk7OOYAQFs45j4AAAAAJz3O
    PgAAAAC4Z/k9Z/+CPwffJD95pcQ96HcoPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAARKosPZ/lAz4AAAAAhGzhPb1MgD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACh2T89AAAAAAAAAAAAAAAAAAAAAOd6
    GTwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGMEAQPnnBjwzteE/AAAA
    AMyg9zyB0npBkkvCPAAAAAARat89BU18vgnvUUDkJXE/+KcIvwAAAABOYNM/AAAAAAAAAADoC1tA
    LlRAP3MWlz4AAAAA8tA8PIgjDEE+DWc/AAAAANI5OD8AAAAAqOOTP9eNSEGWbGBAW3oGP2eVDUEA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE+XgT0RpUE+AAAAAL+5
    yr5hXsM/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAwkIlPgAAAAAAAAAAAAAAAAAAAACzIZ88AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAPsQ6j/tBGFAl09DPwAAAAAQTsk/Ekb2PyuByz0AAAAAIhsQQLuuVr4N
    6WY/HJNUPyJ3aMAAAAAA3gq6QAAAAAAAAAAASGNEQDkHQEBlARBBAAAAAEJ4nUDDho9AOkgEQAAA
    AABiyes/AAAAAGwAGEFzMEZB2TGwQJDQrkA4iVlBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAABYL8I/h+G7PwAAAACnzGXAwq7DQAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABWFXEAAAAAAAAAAAAAAAAAA
    AAAAm7YEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLAts/7QRhQASH
    +j4AAAAA3oDCP87Nvz8vub88AAAAAKiTDkDPgsW+dzLiPUX6Oz9mN2nAAAAAAB38t0AAAAAAAAAA
    AHArOEC9ez9AZQEQQQAAAABCeJ1Ac0+GQBAm/j8AAAAA5ubkPwAAAABt1RdBHmRCQRberEB+eq5A
    H81WQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQI2+P16xuz8A
    AAAAb+BlwOkvwkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAVhVxAAAAAAAAAAAAAAAAAAAAAAJu2BEAAAAAAAAAAAAAAAAAAAAAAHDM9
    RBdHWkFXdfM+AgvlPUx3qz6GODA8T3cfQqh8sj8jT5hBx5wpP3qfpkGKXDs/p7uVPy4UJT3gL7FB
    Q3RAPz5QwEA7FVU+IDNTQpBU5j8ReV5BTQT4PmE29UHPEIY/4aH8QO1vjT4UM74+ys9MPBdHOT+Y
    isw89EdcOiDpzjw+GCE/IrxYPwIv4z7kzA0/fBZPP/sCPj7YWpo9HKvhvWBaGj1lBeU/E/6NPcJA
    ED/KHxo+AAAAAE3XYUPeMgA/4Zu0QMI36T+5T9M/5B5lQB8nkkCkraRAt5WnQFseqEANZJ9C+isu
    Q0tNX0N7oXtDYwmAQ7mEgEMaMpk+D78lP1kjUz993W0/2g9yP17Mcj/1yo8+gqUbP4xJRj/yVV8/
    PERjP8j2Yz+1JnlAW1/7P1IBej9Vmss+IRmdPtqOlD5Y3IxBOjIQQg0OL0KhGzZCov42QigtN0LS
    T7lCUJlOQmf4/0H4VthBKXDTQac40kGurq5B7L0dQWYqqkCCdTQ/jEIzP1DewMB2G49DBPwnQ2XI
    Y0GgQ9NAzeUOQag8lUDa6gJAkp+iQbdoKkIRj99BDciEQbgPMkEZIXFAa5iKQAtuPUBYQTZBWakw
    PghdekFSqbc/ns1nQba3lkF2DYJCAAAAADCgUEEfyD9BGj4FQqh25UD8T49ATG9vQW1CYELFGaE/
    AFCAQQAAAACbq1VB7gdkQCjDzkAhbSFB2aKnQSTK3EEhRytBur+yQYSh4EHMF8JB5wYWQZKeAUHI
    UIRBzG+SQQ3h8EC2hI1Acbj5PvChVkEJASlAwU7/PyWcAz8K8KE+8/UmQM0CKEDfRyQ/6apBQQ2o
    rUHAC+4/nLcJQUoB2j+dvgw+vXK8PncNkz5jTMQ+gXMKPqvqWj9NnoA+j2W6Pxp3lz8d/9o+bFJs
    QkShA0DyFXRBiO0HP4FEL0LHQsM/QtYXQVOnrD6wuV5Aw2bwPbg31z/+W2U92rwzQiVGbUKAgZxC
    RqHDQulx1EILyvVCdL0LQwzEF0Oa/SFDR95/RO9ScEBbMIxAeiufQK1VskAlWMNAL3bMQPKr2UA4
    muZAOjbwQJWQ+UBmQBBBqUZiQivC3UGWEoNACtBvPQAAAACVGIU/TYA+QESqrDwAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAQrxRAAAAAAAAAAABxzIE/B9+kP0SqrDwAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAByxl9AAAAAAAAAAABGpEo/YR0tQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA90ek/
    AAAAAAAAAABGpEo/Gn+EPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADnehk/CtBvPQAAAACP
    M34+YheLPkSqrDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACPM/4+AAAAAAAAAABw0mM+s3+BPkSq
    rDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFpzs/AAAAAAAAAAAAAAAAAAAAAOd6GTwF5QY/gXgl
    PopLhjwAAAAA53qZPN6nOD8AAAAAAAAAAAAAAAAAAAAA53oZPAXlBj/nehk+ikuGPAAAAADnepk8
    qqwgPwAAAAAAAAAAAAAAAAAAAAAAAAAA9TXyPtPgGz4AAAAAAAAAAOd6GTu/Rh4/AAAAAAAAAAAA
    AAAAAAAAAAAAAAD1NfI+JUkSPgAAAAAAAAAA53oZO9XU1z0AAAAAAAAAAAAAAAAAAAAA53oZPK2g
    XD3nehk8ikuGPAAAAACKS4Y8/gjTPQAAAAAAAAAAAAAAAAAAAADnehk8raBcPVs45juKS4Y8AAAA
    AIpLhjwC9JtAge4XPvZyfUAOVNxCiq+lQj7wsELmg7xAM/1NQHeqA0BB6M8/amFzPyKlHz//4dk+
    MSWZPl6sST5cVg4+b8E6PjExlD3qpDo95/MdPU8zxTyEgIY8yklNPFGLKDxG1wM8wqTMO1I71T5q
    8G1Bp7v1QFLUbj+rtfY+dBapQzZ0vkCwjv5BS2WgQFLDu0A0EthADQX0QJ4/CEGiWBZBC6EkQTHM
    MkEAHEFBLz8JQ66LhECD9uI9HQ6vQFknEECJv99AscqGQDCcCUGGk79ApRQkQQ5+mULztchDoZEG
    QVu7KEW7WDRCGIgZQ445NUPThAhBtXbIQA==
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
feature_vars: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADUyNjg1NTcyOHECWAMAAABjcHVxA01NBk50cQRRLoACXXEAWAkAAAA1MjY4NTU3
    MjhxAWEuTQYAAAAAAABZQttBGs4hQTFh8jyCYWI+CcKQQn3MOTubZAY8CcKQQjjWfDoKhmU9Nasj
    Ph/9WjrTjM89jP3lSGdxqUPCzI8/cQLLQZ2j2EFylRVDZicuQgAAAAAAAAAARlvDQEgoI0IAAAAA
    WuzCQaUIN0AXruo/MeuWPgAAAAAnGK0/Oq6jPh5LNz01Zhg8E9vIP+8WWUZIWSJGaCfgRuuA80YP
    kBJHpLEOR9E1EEeaHxhHeyEZR4cIz0TS1yRFq8HYRUrCIUaa2i9Gqz9BRh04SkZsrF9GsUVpRiHu
    EEaFpcBEU183RgqbNUbKmI5G37GGRpWRd0aMx4dGzg10RrYFg0h5xQFIIVSRSBg7yEgOR+RIoUXo
    SP8V+UiJkAhJUVgJSXcpxkq/XvRJWNmHSnkZtUp67M9K+HfPSvV43UoHAvNKMHT0SnFa0UrYuSpL
    ofG9S2zqCUyisBlMzA4qTGO0PUwq+UxMuwtSTLT3DUbtBR5Gz9oIR0VNfkey+KJHtwGqR+jyo0fn
    07tHScXBRxxovkX6vd1Fl126RsQ0KEe3WlRHM3teR6qeWUcrlXZHMdh9R1YqvUU89NRFVsa2Rq8G
    JUfLxFBHseVaR4Q2VUciMnFH1u13R092qEPlYwZEdquaRNn17UQd1gdFCXESRYF5IkXTbTZFfH05
    Rf5lgEoNb2BKvIRhS7au30sGaBRMNS8YTI3aDkzjOydMGaksTDk8G0A5S7Y/eU0JQPcFxD9YB8Q/
    gALZP7Tvzj8Bdug/HQn+P+kKgD3tx4s9hYagPeIBnT26ULA9+xrFPWehyz17D/k98MMLPq7lLECC
    hN89zRBXP+3Hmj4osfU+aAnfPijn8z7qsRI/qicIP2ipEENolC1BAbt1Qc66ikEvAa5Bw3alQW4y
    lEHJ6sRBiirhQaEteEUGtklDtv+QQ3xinUPVzsxDVD3CQx9lpEPZn9tDMmsDRGaFsUMcOYhDrlXu
    Q6Q130OXC+9Do6UHRBalGkTVQzFEK4MxRNT5hz0IxY88ptoiPY2sFT2GCFU9XD9WPQlbgT1FB409
    x0RxPaXLrz1yC6c8/SJLPflJOT06YYE99pyEPXlelz14XbU9O0WgPWOBwj3Tk7w8nV9lPfoSOj2g
    24U9P++JPSRXnj2VObM9QiidPYjl+zw20Ig8qu7JPDlVpjwFWbw8ElO7PCU02DxAfu88NprsPGF/
    jEH1Ti5BkZfKQQGuj0HvfbJBttCgQbJs6kEFm8xBBnzAQfwD+z3CgoM9MPGjPYrpkT2uH6893m+4
    PR7Qsj0ScqA9BiqWPaUiTUUjMhpEFRKVRPpQ+kTd/wdFLQdFRcg4QUVJVGpFM7YQRWr0gUKpHItB
    zTykQdUi8kEW3vJBRxoNQt0fQUKfGS5CxGn2QcT3HUWPYEpCihaXRNdZoUO3RS9EwU60Q44CFETk
    Zz5EfnqaQ5vaz0fcWnpERUlZRedEHEbgL05G6qY1RhCkVEaCEYBGMOEiRn1rSEpWxZJGucKVR9UA
    YUgewJNIxmh+SDjmnkgmJLVIDPpmSC8evUhgAghGP4MHSBOnFUhNLFxIVbxISCD/ckj0OJ9It1BE
    SD52f0AWNYo95YoHQOe9gj9VrsA/8tiUPxkBtj/PffQ/PqyRP8t4AkEfmPM9PUSIQB82EkAoB1xA
    5HVGQMa7eEDIBJRAAH0yQFhIM0HyyiA+Kr2/QAWIOkALs4pAKdNgQHwRmEDW/LRA+l5UQKvFVkHl
    /Fs/JkCNQCTUjUClqsFASJe0QLcG3kDKAM1AcpewQMCWjUTNLCRDTzoRREgFuEM5kdFDqILEQ8FX
    2kMlAPtDxIX1Q+GUDTiPqa03q3IxN+l3wDZ/pOk2Z/cON75rIDdPCiQ3FZomNx2bbD6aYgo+5pAT
    PuO8KT5e4VQ+d5GDPjLKnj7xXAk/7jvNPgLhgzs6oqg7J/JBO2E4RzsvkWc7Cl6BO990nDsXkuM7
    nNO8O/g8aj9ENpg8mr4fPqbpwjzd4EE9bkHJPGxViz0Sfrw9KzhAPW8NikKrB5M+XWTiPjdGgT+0
    3q0/CM2hPyEwFEBoDChAJL72P8fwCUUGBqtAgU4cQT0Aw0FbLftBANPnQRvYYkJW3HJCDO0yQouQ
    zUA2gYdAxq2iQQp3akGd7ZtBOLuxQQ6EzUEzbl1CyAYjQjXEoDpKZf43SUiRORSImjiC0PA4h+qz
    OPsLNjnZe3M5S1hROX8PDjuJo3E40FUQOmSqNDmrao055LZ4Ocri8Tk66Bg6mmb1OQmyUDte65k4
    W4pMOjrWYTndmq85aIGKOXn4FDofYDk6BvkROur0ZDt3hr85BWUlOnB06jn1LSQ6jownOhqdVToL
    cIQ6LdCDOtxmgT6m/IU9hkerPbTOAj2SQQQ9bDAbPb9INT0r8HA9zX6CPXA0ezwF2bQ8sd9VPEvY
    cjxD5YY8G5yXPMzRljz0Z6g8gMIDPCDmBTymYCA8aDFLPDiadDyKTIo8Oo3+PLizvDxa0ls8PzMG
    PKm6+ztcaB48sPQxPAeSUTzxuZs8t4h2PICnwTujsI48iDHwO8HyVDygzxY8DPdjPJj2yTyOLG88
    lioxO99DrDtXwts7UuAlPHVgRTxQiD88ePADPZhiozw5Bhw7fo2sOwMW2DuIZyQ8+8JCPOvJPjwd
    FAQ9bHOkPBQt9DpHJhM8ip/SOxw6CDyHByU8yVEzPBgS2jzHz5M8zNGcOw7lnTxJMgs89RJrPL21
    QTwqIoI8xT/IPDJgojyS92474iZ+PLL+FDzWpmg8kdFmPK3ujzxgnOk8nqSzPJqRgTtr+5E8M1cZ
    PND1cTzD51k8I6yVPEb54Dz306w8JaPRO7UBLzxXfO47NTUHPF+/LjzPvkA8/telPLjphDy5Z6c8
    avl8PKXU3jtorQo83vMlPCKyNjxGXlw8iHJxPAaY4TxOulc964HoPJ/+HD1lyxs9D6pRPXGsTD1f
    tGA9fsaXOx8WeTwF7zg8H6d9PFrJqTzZZ/Y8mvghPfzA3zwRW4g8wHVQPBubTjx8U5I8WmGhPGRb
    1jyeIv48/yL8PFfQAj0TkOY8OWr0PA48fj2GwrY9mgwEPhLpCT5uRtI9b3QoPE49gDyuaR08Gc2O
    PERc/zz+RQc9SyMSPYKXED0cJCo8xbd1PKRlFTwwJIc8iWH2PKQ4BD1CUg89cKsKPY9gOzy69w08
    uTTDO9T6ATz50T483KAzPGRJmzx4BWU8PRKhPKzIWz1B1OY8lr02PXouWD27VZQ9zya2PawKiT0g
    a0E8AbkgPdt6xjw/8Ac9DVsqPZd+dj1WXpM9fC9cPcevZjxn6D096y7kPBK1HT2PoEY9aPmTPTqC
    qT3eUHQ9mi30PMaBczwiURY8HzxYPDLXqTy0rJ88szHIPNq2sjwIdTo9gPeAPNtUJjyX3CA8BaV7
    PDJXpDyqwc48c03JPHxIqDpFEIc7MoDIPsphuD6QT+c9Ng5vPKmfIkDwkQ8+jPpZQh7KUz3M+5RD
    nS2JPpo7fUB080I/BhgmPc96Izm9nZk97EI+OcoTwz2xvEU5hVeFPvsIkjx0mOI/AkqaPXUbRj2a
    XGBGuJdhRW+wCEYJ1GFGh4qcQLiXYUWCh0s/LFa/PgitEjpayAU+GFx5RfdECT8mUrg+48VgRrjj
    YUX3xAhG9zZiRkyhnUC442FFrtrXP0Jbvz6ZvxI6csYFPttYeUVveAk/Ala4PmCb0EZBss5FG4h8
    RmA3z0ZayiFBQbLORRpHiz8CnL8+LNIROkHxBT5e1XpFiNQIPxCxtz5MmmhGjQlqRcEKDUZSC2pG
    GbGfQI0JakVKQJg+Hz6/PoSSEjooygU+vPh5RfI3CT9cQ7g+RE1jRkjXZEUZtwlGw9lkRptUm0BI
    12RFRBW4Puc2vz6mlRI6GckFPlcMekV9Tgk/s0q4PoEzXEba4l1FFFsFRoPlXUYLkpVA2uJdRfTT
    3j4nN78+2JISOtPJBT52FHpFolQJP3ROuD6vkQlHCacGRszZo0ZCkwdHYbtkQQmnBka+4wZBZ0a/
    PiFyETpA+QU+a8F9RY03Cz8F0bc+zqtXRj0eWUXU6AFGPyZZRqJdkkA9HllFHVm9Po4Ovz4imRI6
    4cQFPqfMekXK5wk/gm64PjHpuEdmfCVDVKFUQgCs8EK0Rpc/o/IcPZ2j2EF2VM9Br3oEQ4zo00Av
    vA47eC93OmYyAj2pI+U8Qc+gP3tIj0EoQwtA3u6AQMQAUEAQLN89eAw+PJzgmzwBeJk8lS+iO9un
    DjvE6Qs8E8lcPHSlBD2VL6I7w8PfOrh/PzvQ8lM7ejG3O/ZpKT9IFI08wRuDPXew1juC3iU+IgfW
    OqKzDzyImBA5683kPxXhikDPLC9BuPvuPtX9Tj93irw/0fmuQUh0IEHEZhVBY8y+QLC7i0CMWUZA
    gqvaP3Hiiz+W00o5VQU7OHQyjji+2D84IQf/N8N0pzenwVc3LS/xNhQoaEFgeLpAx2aCQPyaDEDK
    h5c/vlYbP3mThD6rVfM9PPM/OqpNCTqZ7KU5aEMMOSoEXjh/uZU3h5AAN7qtPDbN2IdCSW97QkKL
    Y0LoBhhD4fYNQ9mTEkPUVIBCOC9DQ8cnzDu9YPs72kCVOlnFXzmPfMU51U3YOa1skToD2EI5+Xpo
    R6RvaEbjWAJH+XpoRz6rU0Gkb2hGAAAAAFcNvz7M0Bc6ywQFPrSpdEXryw0/QAe8PpKwBEvADMJG
    wAzCRSIAaUbADMJGf6PzQMAMwkUlRr8+6owTOranBT70/HhFeqcIP1GTuD4AAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAADTSpg/53oZOyOLuEAAAAAAUSsFPRdeJEFqwNE+AAAAAMv7cD3iXaM/NlmHQM7+
    lz8qAgk+AAAAANtsoj4AAAAAAAAAABX9kz8a+1M+ZjICPQAAAADnehk7IQOYPwb14z4AAAAAPr2y
    PgAAAABtKeU9cQhvP29yRz/pBs89JxitPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAOAE5PWT47z0AAAAAhrLSPTquoz4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeSzc9AAAAAAAAAAAAAAAAAAAAADVm
    GDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3VlzQPUo7TycDJVAAAAA
    AJ5fuj2HqBRC75czPQAAAAAhFLk+C8pCPuUtfEBiwnY/f7cQQAAAAAB73ylBAAAAAAAAAACYIx1B
    +DPwPxjkJEAAAAAArkloPVe4tkHBo+A/AAAAAIGiij8AAAAAJQQhQWhqC0MB4bhB6q9EQEvYcUMA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKjz0z2hh4M+AAAAADkc
    rz/45j1BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAemAIPwAAAAAAAAAAAAAAAAAAAACmYiQ9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAANnDRD0AAAAAF7ChPQAAAABnrUU6ssSpPEcsxDwAAAAA2GqCO/3naj0z
    tUc978rIPFG6sz4AAAAA3LWZPAAAAAAAAAAAIFw+PUKJIzw15cg6AAAAAAAAAAAiykY9mzccPQAA
    AAB2v8E8AAAAANL5wTxd6Dw+0E1SPSjSrzzZLAk+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAADRxhI7zzRnOwAAAAB1A9w8t9UMPAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO4xvToAAAAAAAAAAAAAAAAA
    AAAAmVIOOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABJ2l89AAAAAA0r
    3z0AAAAA36gvOtZixD24e/M8AAAAAM5YOjvJa4s9XmmhPvNXrzwfP7Y+AAAAAId4pjwAAAAAAAAA
    AHoWuD3Y8Bw8NeXIOgAAAAAAAAAAMY8vPdHsXz0AAAAAVIH7PAAAAACl3Mk8VLdhPprTZj3kYq08
    nWbpPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAx5wXO+/FZTsA
    AAAAAZ7cPEMj8zsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAADuMb06AAAAAAAAAAAAAAAAAAAAAJlSDjkAAAAAAAAAAAAAAAAAAAAAT5Tz
    R3LEF0HgfHg5K1JMO9Vo1zotPeo5tPakQhJ7PTyIeqJBxZxGOoAS4UEfdl08sisEP4X7BTpqvnVC
    hrKCPPEjMEBuUTE6JgmRQ69GCj1IdCBBHUMQOG/Rx0J523w8UKVZQESHPDqlik09ZPcoONxggD3A
    bfM37ba5N8xoLjlx4gU719rzOnZ7lTYPCpY6Q8YOO8NLCTsKtwg6ZyudOtJeLTp9fmZBYyKLPLWZ
    zTqzmc06AAAAAOWyHUYMX5A7b+1bQJGWnT8C97g87v2oPdOS3D39uuc9+jzyPSfv+j1lUudDKHUg
    RW0WkEWQW7RFxyG7RSmOv0U/G5s6SYVCOzQi6Trva6Q6VbmuOmxjnTpPK3k6sL0lO8q5yjoG3EE6
    sJM/OncVKzrhQSo+DEsNPqyViD3t9TA9o+Q1PULKIT1ttLNBHfjzQVpX7EHAnvBBM3XwQUKr8EE4
    JdVDqCHuQgNyvkF04kVBFYA4QbQQLkFkgvBBD73xQM/0UUA1gFU+1nJXPpY+K0AcFIlF0nO0RCgN
    bELKN8JBu01XQnZqB0JbVpNBfphTQ/Y+kkOJVCdDDp3GQty5e0K4q/RBvuyzQbuziEEKPHlCOE1h
    P4REIUI8rPFABT03Q55vUEOcn+1DAAAAAJuwzEKLu25CF6GGQ9A1T0K7pgZCqAYiQ3mjuUMnCQFB
    2TPmQgAAAABlHPBCKMbgQYbsp0ItdI1C099EQ7+dnUMfY8BC8Pp4Q7Ub0UMxGTFDQcqDQgOsO0JC
    vadD5RunQp12yUE1Bm1BPu0AQLZxAELhAeJAf1acQKf0WEAdEt88BGeMP17Gxj/y9Iw90tT0QeIx
    MUJg9D49J8M7QRJvDD3P9jw43L/JPPtRVDwN3pk8d7wvOc9pnj32C6Q6yBttP+VPWD4o+448/LI4
    Q0VdCzrKY7lBZrRDPBHr1EJF/W48U8lDQWbIhDygi8VAWOLWO5Z9lUDShZ87MPrgQqslQUOY+bVD
    v3kmRF02ekT7x8tE3FIkRarbcEUBu6xF1xbcR/hxSj2DpUw9vQlOPSkAez2YTaE9ikoJPpavRz7D
    NYc+AorAPsAxAj85YYc+ofMyQ40rokKIi0Q/OYh1PQAAAAAVf8U+UTdkPy1sqTwAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAADxklU/AAAAAAAAAADKN8w+YGgqPy1sqTwAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAABGNWc/AAAAAAAAAACbr90+V5c/PwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADNDV8/
    AAAAAAAAAACbr90+F+jYPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqwNE+OYh1PQAAAAD6
    900+A1FePi1sqTwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABc8qE+AAAAAAAAAACdKjs+LY9LPi1s
    qTwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACP7qI+AAAAAAAAAAAAAAAAAAAAADVmGDwM/KM+vA4L
    PlJnhDwAAAAAR/WWPMjaoD4AAAAAAAAAAAAAAAAAAAAANWYYPAz8oz5HyAI+UmeEPAAAAABH9ZY8
    XTCXPgAAAAAAAAAAAAAAAAAAAAAAAAAAEouJPrx1BD4AAAAAAAAAAOd6GTtHkJM+AAAAAAAAAAAA
    AAAAAAAAAAAAAAASi4k+O137PQAAAAAAAAAA53oZO/iJwT0AAAAAAAAAAAAAAAAAAAAANWYYPNU7
    UT01Zhg8UmeEPAAAAABSZ4Q8xLu9PQAAAAAAAAAAAAAAAAAAAAA1Zhg81TtRPakj5TtSZ4Q8AAAA
    AFJnhDxMCZ9AIHcqO0iHC0ChkRlENIMtRGj4V0RFPYhAG1FPP9rCCT9TMKU+fJD+PTB0gj2ejhI9
    N4XSPGnhfjx6r0k8ciK8OuTkHzmwic84MQYfOH2K8De3DmI3kfYuNx4PETeMJQ03TKwIN2OvgTt/
    QIJBcnuCQFVwtztsw9453IzTRcy49z1UoVRCPZhwPe5lcD1/93c9/VF7PeU8gz2EU4g94/WQPY4S
    mj36UKY9ToJ/Q5y0ZT3WjVQ+CP9zPY2qhD9cQXw9tJFJQFOGgj1dIsdANayJPUZmqUJIVQ1G4wKM
    Px1aQUrCNAlDv26fRPyB3USm2rFA9xUBQA==
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
hidden_sizes: !!python/tuple
- 1800
- 1800
input_dim: 1613
learning_rate: 1.0e-05
task_type: CLASSIFICATION
