feature_means: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADIwOTU1MjMzNnECWAMAAABjcHVxA01NBk50cQRRLoACXXEAWAkAAAAyMDk1NTIz
    MzZxAWEuTQYAAAAAAACu3rRBXouJQf4I0zyh2T8+7+kVQjqqHUBPW5tA7+kVQveMpz/1mIhAio6L
    QONQIj6qgx9AV8EQREFkkEFLXd5AmAaXQYxFnEHjj0BCv0PlQQAAAADnepk71871QJ/lm0EAAAAA
    csanQZYPkkAPtfY/EK+UPgAAAABt4Rg/zAF3PqHZPz1bOGY8WzhmP+rh0UPtEtNDAToZRMIkFUR3
    yAxE3eECRNOi9UPvV9pD5u60Q92wLEPGH1hDMoSnQ8Wot0Oj0LBDrCOqQ/wRoEP3rJJDKbGAQyse
    ZkPjVSlD1W+XQ3fmrEN5J7lDKBOwQ/e8qUPaT6FDRyGOQ0hYsERnn7RELiwFRZLHD0XTEAtFMmcD
    RSzl+kQnPelE9VXKRG6FtEUpJa5F4NH9ReXQBUa8DABGd0zxRWa+5UU89NRFWE+3RfgeM0Yvl19G
    iH+iRoA+ska5U6xGETOmRvRBn0Z4zpJGpA2ARhx7vEOEKMlDVgopRNRYU0SJ6V1ENPJXRHxqTUQK
    X0VE+Ss1RJv+mkO9dqlDFtMMREzLLUSJVzVEj/MvRE6yJ0TtbiBEDXoSRB8SmUOCo6VDDWAKRLMC
    K0SQzTJEfYktROpXJURnLh5Eq3MQROwNnUKFZsJCWQ0QQytsIkNPkB9DmAAaQ+DVE0MjigpDXgf1
    QrEq9UXzfuxFkFhPRlaxhUaiLo9GUzCMRt7ChEYN2IBGs3JvRpXMDEEsvgVB7XzpQKKStUCWhaJA
    tkqZQBcDlkDk7YhAW+luQLMiZ0DvqIdAGiB8QE1cW0B1/0hAC75EQAh2QUDx8jVAS1IqQDMDmUAu
    yFVALw5jQFQET0DZalJAbsNLQBwqT0DnnkxAQ+VBQGc88EFY9+JBHK7JQWfnrUGbrKBBbhyaQYyT
    mUEO25NBwz2JQSBC90KNENtC3aPAQslgokKfiZRC8veNQlXqjEJUSIdCZQR5QnwqcEOlZoxDU0Z1
    Q1XiVUPz5kRDkDVBQ4tsQUMKszdDpOcqQ+e3+kB6c/tAB+z7QOQX+kCGmvlA+lX4QBiI+ECfZvdA
    can1QCVVzkDU79NAKRTSQIjrzUBQTsxA24nKQFjyykAMKMlAVlnGQFaxy0DFJM9An1TOQPCIykD1
    W8lAPa3HQHEMyEB5TsZAVZfDQLfG0j/M9fM/VjzZP/SBwj/UAbY/7+uyPzqQsz9TX60/HoOkPyPE
    IkMpxRNDsRAaQ8qnHUMZaiBDq+ggQ4qHIEOSaCFDgNwiQ7S2cz9nHwy/1PUZPgUtBr5Vh8M9wuh+
    vHfevL0Xo8M9n09WvfpxQkNjtVhCWFvjQaYdtsFWXqHB9QDiwT1xIMIZZqfB4yNGwfQH7EENYxxB
    I2pDv2ubmMDqV2HAv583wJTjocAL1IHA9MciwC67lULVeNrAzBeeQXnVycCtOXLA4j39wNAbC8Go
    tcA9X8cbwGQD9kNSKcpBoi4LQi+JQMKkbiHCEJLNwbAgesJzsKXBKc56wUw8FUX0q+ZCyXcqQzUX
    Z8NlzTzDvcfewp+ilsP4LM/CAU2ZwllCEkXVUzBCOtC6QqJ6g8MQT4PDIzxYQgWAgsPS/orDrVI9
    wyzyekDdwDS+brk+P/YzG7+VvYy+/H38vol+7b7K8WI+n7aHvQHixECRZvS9c52bP/P2Yb+e3Oi+
    5mc1v5XRXL/YJgY+PU7OvUyF00Cu73y+Uj20P1mkfL+H9uW+35xMv4ABZ7929Es+DkMSvngqQUFD
    QHS+Inz7PuG4s7/yPJ2/vPJlPlAdZr8y94K/rXCLvzFjtELAOCTBAGzUQNhmgsEGqujApZQEvlpy
    VsBJwsC/IXwIwaI6ozyo2DC8A7XkOnbrmrplxmo6zl9juYvGTLr+EWc6mmUHuk2jgEAgtYU/+E2k
    Pvknab6Z63C+gT6NvluWyL7bZW6+67bjvU3mHD+OY0Y+dwsCvJGKSL2xUB297AsDvRAeVr3YezG9
    zX6svJJoxD+Jawq+UolfPphib73L2RO92wyQvZ6Yob3CGDW8+QvWvGJEKUGH+eI+zw3PPveg8r4t
    4da+k9SKvjoJIL+Aal6+qaQGvoSVTkIwJgJAg9/8P14TE8A1Iv2/UhGYv5IqQsCN94q/4scmv6v6
    QUIv8oM/dDZuP0pWIsC+yzHAasNRPghYGcArVDnA2a++v7rgpD1V7HK7clwMPHXNsLvepyy7OxKW
    u5B+lbu8duw6f9sJuk9sAT4ZcTe7n+pkPK0c/bvLpaC7yyncuxIsBrz5JCs6lMtHuvnVCj7qZam7
    QqyEPJRjDLy/D5u7jyj4uwvmDbx8/4k6N7qmunwogT47GjK7dy+mO2mRZLy3BkO8m9fjOTpTErx8
    vTO8UHkMvIab7z+5OTq+pQ6GPTwUHr4UzIS9xOSUu6egHL1MV968wgCZvUOXB7+q5KM95OJmvYwX
    IT37byG86MURvVzwKz2gjtG8/7uFPnZhnj3jO2S9YZZrvUbKir0Ll8m93hiBvRH997wyn6I+45pZ
    vBOBo72G3IG9W7BVvW6bsb0NFJG93wELvTV0sL3R1N09Y+sIvXphprwCqVO9N3pavf+GVLzIrK28
    +k9OPeifOT00+j29z+FfvVytC70X6nS9PDzzvCapXbzNAks9ENk8PZfKPb2xgmK9Ay8GvZv3cb15
    g/m8+HVhvOLZrTwA/pg8ZfRYvd4Ib72hTVY7kiVJvQeIb73csva8edErvXZFvT2keoS92OH6vC6B
    b73sSHK9FzsxPA3tTLyiMIu8FOHFPZJsdr0aHxW9qfpcvUm7iL32Oce7ToI/vP/kCL0pZdM9EpJ+
    vfHy/rxIJmu93LSKvSMrkrvqonO8itJpvOZApjzbEmq9q4lTvQvOBjtWsgu9zD03va6rFb3ev8m9
    PvTbPEtlo71h7xG9b6YVuyJS5Lwr7Hi82FsOvREryD/uqXs/hHqOP7/YgT8+G4Q/U7KDPwrBbT97
    a3g/k84BP9E2Vj+MEYI/gxeFPyPVhz87EYo/elCEP3w8gj9WeD8/hvCTP6SVkz+xlog/Lf6GP595
    hz/A0X8/ukVzP52uND9nPBs/U9pqP29Dfz86sII/TSiFP92kfj9rGoA/KPYxP80KSj8lhng/bCqB
    PzT+fT9cdYA/0GOAPw7AhT+0mzE/VSpJP2z0dz9C7IA/0DN9PwRjgD+GfIA/ptuFP405Xj+YsWI/
    XnV+P4NygT8WUHY/03iBP/BbhT9M14U/E8FEP+oCSD/D6IE/+eqBPx+fgT9wOoE/UPtwP3u3eT+9
    Azg/XCpBPzv2fT+xhYE/KjKBPx22gj/XE3g/kGF+PyuPQT8RmEQ/2LGAP//9gT+hQYI/UquDP+AV
    dz9D53s/PFR4Px3kbD+T1II/s7SBP8mrdD8Cb3w/nRiBPxiigz+pIJg/VfeCP1sGiz+9MYM/G611
    P2yIfj8Lj3Y/jtN2P1sC4T52ZOS+bofGQORJhj8T5ltAmz5+Pyzx1EB/54o/vWNQQTeYtUCjzNlB
    BcU6QeKlskGGeWVBbvpwQLpuG0AseGdA3eAOQNXwa0CopQtAO6EVQEzwNT+lzHdBdossQSwerT8w
    RoJDsfkCQzZ6RUP7A4NDM6wKQbH5AkM/Zdk/HVCnQOxaQD758CpAmBk6Q4dgykD2BMZAD1eCQzgJ
    A0Pej0VDlhaDQ07ACkE4CQNDzrPYP0xOp0AHWUA+RvAqQPwZOkMDYcpA9gTGQBcTp0Px1CVD29h6
    Q6Q2pkMNBi9B8dQlQ6b7HsCKMqdAcTdAPmXlKkAXwTpDbR3LQFMjxkCBo4RDLE0FQ2efSEPJQoVD
    //wMQSxNBUOENrE/8UinQHhSQD417ipAsE46Q2iaykBEDsZA3HCDQ1UoBEMb0UZDPR2EQ2jMC0FV
    KARDcKrAP79Gp0D0T0A+Xu0qQDVVOkM0ocpAUA/GQH7cgUOZpAJDuXBEQ7yYgkMuPApBmaQCQ+Gv
    0z/AQ6dAX0xAPjLsKkCxXTpDmarKQNEQxkCeiLpDl843Q6f0ikNzvbhDQytCQZfON0OAHa7AY+um
    QInlPz4ByipA8bI7Q78jzEAdTMZA2uuAQ2inAUOin0JDfp2BQ6EzCUFopwFDVW7KP6U0p0AjO0A+
    beYqQMSfOkNA8cpA1xvGQGjAi0Se6ExCNfX9QQfc80EQr5Q/UHFJPYxFnEE19aVBjEUkQtnCIUH5
    qDk+bnDnPfNBNj3nehk8fZAtQHmiM0H2LxBAZ/8CQBCvlD8lSRI+53qZPN4uPD6ufzs+6d2fPARR
    TDx/qPU9AUzdPi58KT/p3Z884wM3PJILZT3LdBc+0ko8Pgb2AkCwmok9tsvmPlwy4jy8KGw/LMmV
    PHkkDD68wZU7xsaOQFbw4UDfXClB9gveP6qiEUD2kjRAiYigQWTuXUENCUtBlk8pQdMhDkFnSORA
    3cWdQIPmaUB8LTM/stffPku2kD7yETc+3lvpPaXtlT1sXj89t172PGiDgUFH0RlBV0HpQI87pED4
    5WRAvJgYQNdArz9iA1c/W40QPw2Vmj6KciU+cBSwPcznOT1Fc8U89B9QPBlm3DuBdgtCro4FQhSp
    AEIOMENC0a09QjUYQEKuVQdCOglZQlgWOz/nbDM/LwMsP2vKgT8eXnw/14l/P63RND+lLZA/7UIe
    RHEynkNJBeJD7UIeRJ70qkFxMp5DAAAAAMRDqECff0E+t08rQLP8NkPbycZA/mzFQO8rlkWcYrBD
    GGIwQw4KhEOcYrBDEzc7QRhiMEMTbKdAB31APvL7KkCGHjpDkmPKQFkFxkAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAABTYpQ/53qZO+xiEUAAAAAAodm/PMgWDkHqbtU+AAAAAK2gXD31OGM/WEe7QDT7
    lz9iFws+AAAAADnjjz4AAAAAAAAAAEmVlT+f5YM+80E2PQAAAADnepk7mQD9P+Ch1j4AAAAA/gjT
    PgAAAAAlSRI+8UqJPy8TID9t3qc9beEYPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAOeMPPXaxCD4AAAAACtDvPcwBdz4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACh2T89AAAAAAAAAAAAAAAAAAAAAFs4
    ZjwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2F4DQG7UjTzzWdU/AAAA
    APbvHD3k4ntBE/MmOwAAAACo5/k9VYJ3vrABUkCfyHI/pwvivgAAAACJdc8/AAAAAAAAAADk+VtA
    MLRFP/4R0T4AAAAApEGsPP2gCUHA9lc/AAAAAOhXOD8AAAAA6bytPy7hUkEdZVlAJIzlPla9AEEA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIqjWj1jXUk+AAAAAH4+
    1L5iH7w/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAACJIkPgAAAAAAAAAAAAAAAAAAAABtMu48AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAJMY6j9TkWxAGmc8PwAAAAA27s4/2/T1P5JRJj0AAAAA4+4NQLkPQ76d
    ZmU/gy1SP8F4TsAAAAAA85W5QAAAAAAAAAAAvAZEQA4BQECj1BJBAAAAAL6oj0BARo9An6cEQAAA
    AABScOc/AAAAAA2XGEHRskZBE9CvQOOurkCZ5VlBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAA5J8U/b4e8PwAAAAA2GWLA27HDQAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEOZW0AAAAAAAAAAAAAAAAAA
    AAAAX28EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8zto/U5FsQGfg
    9T4AAAAAgBLKP7t+wT+uBiC9AAAAALsbDUC8Ir6+ifXyPQW1OT9ZfU7AAAAAAJC0t0AAAAAAAAAA
    AEBcOEBDqD9Ao9QSQQAAAAC+qI9A+XeGQPKT/j8AAAAA6IjgPwAAAADWJxhBj7RCQSGLrEBWG65A
    fBJXQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0b3AP/5YvD8A
    AAAAyCtiwLBmwkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAABDmVtAAAAAAAAAAAAAAAAAAAAAAF9vBEAAAAAAAAAAAAAAAAAAAAAAtfY7
    RID+WUFqsfM+jFPoPRv3qz5VYzM8UmUfQkLesj9Hm5dB5DEpP10vp0Ghijw/9DuUP2rcIz0ftrBB
    BzNAP66yv0BizVQ+1v1SQt925j9k7l1Bd/n3PoxF9UG8U4Y/HCr8QAWJjT4ov74+dPJNPFZYOT/X
    Mc088yhjOuVeyzxptyA/uzRYP7su4z7Gag0/9mhOPy+APD4TZZo9SZvevWC8HD1ZQfk/5MWaPXe3
    ED/wRBg+AAAAALfpYEPqqP8+xSi0QKPQ7D+TutI/tLhkQBqtkUA2XKRAZ2inQBj4p0C0up5C+Z0t
    Q8NDXkPtvHpDk11/Q9YxgEOO35g+L5AlPymXUj8MlG0/Ff1xP/jCcj98cI8+emsbP9KyRT+R+l4/
    NBtjP7PWYz+xKHlAkJr7Px+vfD98bM4+c6mdPl6ulD7ek4xBwNoPQp7CLkJQ9jVCW+o2QjYWN0JB
    6bhCXMZOQn40AEJDK9hBN+jSQf+40UFQSq5BWBodQcgqqUARqTI/EakyP8v9v8A48Y5D5KQnQ08B
    YUFilNtAto8MQXQ/jkCF5AlALhqmQeh1KUKk7t5BtIyDQTfYLEFFA4FAXpWGQKevTEDaBjRBRMFv
    PgvTd0Gn28Y/cIFmQWRGkkHsXYJCAAAAAMV2UkGtdD5BO4YDQtjE30Dz9o9AfZB3QRsBYUIGFJs/
    N9+BQQAAAADVPE5BVjpjQMFYzEA3NSlBGsimQYvW1kGneiVBZna4QUoY4UEyb8FBouoQQepLA0Hb
    7XpBJV6UQVY//UDR7I1AYhjePiJ0WUFwhilAUOb7P6cz8D5Nybo+xCQpQK9aKUAuV2w/HStAQT6W
    rkEVi+8/9V8MQYoW0z+O4zg+PrbAPiD7mz6APdM+1ecKPoATWj8W6Xw+Eoi5P37bmD+0ytQ+Prxr
    QvubA0B26HFBX+wGP7M5L0LHuMM/aH8WQXLiqz4YMGJAXyHzPafryD+PHlY9g3IzQssHbULpcZxC
    YRrEQnPA1UIXjvdCRKoMQ9fLGEPdsCJDHHOAREpEcEBwNYxApUCfQAt4skCXlMNAxtvMQGAm2kCf
    GudA4M/wQD4f+kCHfhBBSQJiQtFc3EHYxYJAYheLPQAAAADsZYI/jzM+QP4I0zwAAAAAAAAAAAAA
    AAAAAAAA53oZO+d6GTvilRJAAAAAAAAAAACPM34/G3miP/4I0zwAAAAAAAAAAAAAAAAAAAAA53oZ
    O+d6GTtyxl9AAAAAAAAAAADLCko/v0MtQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMBOg/
    AAAAAAAAAADLCko/Z/+CPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8FBc/YheLPQAAAAAy
    BGs+gH6HPv4I0zwAAAAAAAAAAAAAAAAAAAAA53oZO+d6GTvhm/Q+AAAAAAAAAAATo1A+pM17Pv4I
    0zwAAAAAAAAAAAAAAAAAAAAA53oZO+d6GTtPdDo/AAAAAAAAAAAAAAAAAAAAAFs45js45gA/MBAv
    PopLhjwAAAAAuGf5PGQOOD8AAAAAAAAAAAAAAAAAAAAAWzjmOzjmAD+BeCU+ikuGPAAAAAC4Z/k8
    LxMgPwAAAAAAAAAAAAAAAAAAAAAAAAAAKDfsPpYSIz4AAAAAAAAAAOd6mTu/Rh4/AAAAAAAAAAAA
    AAAAAAAAAAAAAAAoN+w+0+AbPgAAAAAAAAAA53qZO/4I0z0AAAAAAAAAAAAAAAAAAAAAWzjmO0Sq
    LD2h2T88ikuGPAAAAAD+CNM8Jz3OPQAAAAAAAAAAAAAAAAAAAABbOOY7RKosPed6GTyKS4Y8AAAA
    AP4I0zyumppADFYWPkT5e0DVMdxCgQenQhFPskIfZ7xAUR9OQHEfBEA6ldE/P4l3P7fTIT+689o+
    +36ZPqPsSD7aVA0+wjw7Pu+3lD0gYjs9ELcePVCKxzyWeoc8ZW1MPHD1KDzMpwI83tPMO3fz1T4V
    l2xBxSj0QIpTbz/W+fY+4v2oQ3BNvkA19f1BCU+gQNuxu0DABdhA2/7zQIU/CEHrWxZBj6ckQSrW
    MkFGKUFBcRsJQ2BxhEAy9wA+7/iuQDfZD0C1st9Ak2mGQGeaCUGeCL9A+RckQXVPmUJWTMhD34kG
    QQjGJ0WAgTRCjTwZQ874NEOKnQhBMQvIQA==
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
feature_vars: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCAAAADQyNzU1NjY0cQJYAwAAAGNwdXEDTU0GTnRxBFEugAJdcQBYCAAAADQyNzU1NjY0
    cQFhLk0GAAAAAAAA2KTgQRzfJ0HNFM48fbtCPj/rlEKEYTo70t0QPD/rlELUVoQ6I29tPQ3HLD5J
    JWE6J/HXPQgx+0iNYr1DlGKWP5JqxkGAqdRBkI0YQ2UBM0IAAAAA53oZPOTnwkDYCCJCAAAAALRN
    xkELIjdA7Gr7P+Rslz4AAAAADw2XP7IGmj4eSzc9nYRjPK0WuD+Nj1dG2GQhRk/P2EYqlO9G6z4V
    R7daFkfbhRlH4+YbR86iG0dr0tNErgcpRYSA3EWalSVGibU1RjZnSkaQt1VGAj1qRvLJbkYSBwxG
    8znCRCmfK0arbTJGAkqPRgy3jEaMh4tGfRyRRpVuiEZDKpNIRVsHSOn5k0jHYM9IBLDuSLckAEmF
    UwtJwdYUSY9KFEnLveZKz7v+SQlviUr9artK9xrZSuW45UqVUfdKwiYES4YGBEuME9hKz8QvS/p5
    wksbgQ1M4mAgTAulNkx7Wk1MxXxZTEgcW0yJiBFGKjQhRkF3C0c0wYBHTpulR9VvrkexgbBHLcXH
    R9/IyUfv68JFHRHiRT++vUYyRypHKRdYR+vsZEetZGpHatSCR09YhEd3SsFFjNzYRTfnuUax1CZH
    g0dUR5reYEflU2VHdYJ/Rz0sgUcofa5DcPgKRCXvnkR3fvREM5kMRT8ZHEVhHzBFlk1CRfgbQUVW
    SIJK3WJjSgNrZEupjuBLp00VTM+/GUwz3RdM+JwwTDi+MUwuSgxAqbirP50o9T8MP7Y/XlK7PzK9
    1D8oNcc/rE7SP7k56T+R6249946DPdP7mD13zpc9rLa9Pf7qxz0ZdME9DWzzPeCtGj7tBhtAr/PX
    PT4QMD91cYk+6vHVPkMEzz6DlO4+N9EDP7jq/D4kIy1D9tIrQU8HbEG03oZB8yOtQb1LqUGNCo9B
    +iq7QYjz7kFVgppF7kFJQ7CNjEM66ZlDt9fMQ15Bx0NWdqBD/p/TQyncDETm7atDsPeCQ18j5UOL
    ns5Db6T2Q09wDESlJBBET94kRDAsSUQwJ3k9JJiKPPywFT00zBQ9D9BGPW5vTz2Dal89CXN5PZ1W
    az1+M589OUmgPP3YNj0UCTM9eR10PUJhgD2iT4U9kPKbPflmoT2Js689en62PDYTTz3HrjU9pRN9
    Pf7uhD2PNYo9IiWZPdEnmz2g2QU9tXGHPJU6yDwwzaA8zAvGPAx4xDxR3ss8Y3DgPE4jBT3t2YRB
    i2crQc1RxEFiGotBw0KvQSeGpkGV8MtBsKjEQXpn1EFs9f494Fx+PQZglj0VRos9S5yvPRIfvD26
    H689wIORPYUVhj2z4lFFjJkVRDGlj0RQVflEz74LRUHDRkUYLzBFMIBtRTr2B0X2j4VC3oWFQWLl
    tEFAbO9B3VYEQuYLI0IUgD9CUWUyQpvC8UFAAxdFhO4+Qn2dfEReoI5DcrYtRD1CqUO93PRDQzEi
    RGPiikMAiPhH8E6ERA0DVkWy9iNGUDU/RiQ3NUYi/WJG1vuBRkB+H0b3GXZK50ObRsf/kkc6yXFI
    wJiISHLQfUiGoKhIZl+4SPY3Y0j4I8BIq08LRhqQDEgOayJIfS9TSMUmSkjNV4BIRpiiSDw+RkjI
    InpACD6JPZsS2z9htnc/49GwP5AQjz8D/qE/XQbVP6r7Yz8yW/xAKDbmPYUsX0AuyQtAWBxMQDNJ
    P0CilVFALgaGQFxJE0B5gCtBggIVPrBJnUDJUzFA7CyAQH0tWED0I31A/YWfQE3lKkCCXmxBN79l
    PzCIkkASE5RAXjy6QH/Lv0AGnedALEjWQLYys0BNrYNE8OsnQxzNBUTKD7BDnA7AQ5YmtUPVlN1D
    8wIAROwX5UMLZAs40mylNyYfKDcLwro2VRLrNk8gEDc3bBg3/FgHN7PDCTd64WQ+hcgIPlWBET63
    JyU+8ypSPvhcgj40W4w+r9z+PjAgxT5HUoA7Fn6lO58BVjsZljo7LQRyO9tcijskvZw7UHrTOwz9
    xzuV81Y/W66LPPVMAT7r7qo85RBCPcuWuzzRFD49j66PPegUHj2i1a9CZ92XPuF25z4MqJE/8Rmk
    P0W6oT9qCRdAP4wkQO35/D8FkDRF3P2wQNhcH0Ha1uJBJx7tQevH6EGepmZCeZJxQjtmOEJo88FA
    dMOGQNV0qEE3mHxBacGXQcgvo0EMsd5BYdBGQrrSMkKyWJY673L9NxCWZDkz25U4cIDaONtpqji2
    2g05yphFOWRaCzmRkAI7mY1pOGoz5jlHJDE54WmBORM5bzkvYLE59hcCOisftzkH4j47jhGTOF41
    IzoWoVw5u4WgOVL3hDk5OtY5yWYZOvBkzzngFpQ7pqTCOYS/Jzqza+05d8EcOqB+Kjo4ZWQ6tyV7
    OslNkDrEGV0+HDqFPUj2mT3nw+w8yE3tPHBYCz2nhUI9tqhnPVARaz0SXmg8tHmnPI6YSDz3BHU8
    juyMPBl5kjwO24I8rjSSPMqgBTzjGAg8VmsaPBL9STwl1nc8x72FPFSD9jwwYL4898BSPKEIEjyG
    Y+07hqwkPCCOOTwtjFE8C4+PPHwZgTz4o7o7pYJ7PPsp9TuYYlA88NYbPL52TDy9q8g88QWIPKId
    MDt0pLI7pPHlO7luHDxnSj08Xc1GPGZa+Dx/NbA8SgsbOy5Ysjsr8OI7yw0bPKryOTxEUUU8BuX3
    PBGdsDzAx/A6+JcWPKF13TsDXAQ885QVPBszQjzAqsE8kdaiPIoRnjulJos8ZE8PPCbhWTyy/kk8
    1nt/PN+E0DxyAJo8FOBpO3vOYjzjGRk8lzhaPLm5ajwXjog8uenvPLXvtTyBsn07MPOCPHRLHTyi
    HWQ8pf1fPNfejTzt6ug8DKywPNVl0Tuhzy88+vvrOyas/zuvwiU8zIdaPMrxlTxll5Q8FlCmPLT/
    dzyyINc7vKYDPLsuJDxOrlE8LIhkPGMLcjwV4Mo8MEJIPU+J4zyYwSE9Y24ePWF3Rj2U4lY9FXxc
    PZMGjzstcWI8J8sxPENReTw46K48277bPGlQID3vKPg8JNt/PBnRgzxit0c8JzyiPFpCqjxjuMQ8
    Ev31PBbADT138wU9EiHCPOjP7jw3z3A9zbyyPacV+D0tdCI+J7UNPjZgJjz4aXo8hZUWPPFyjjx+
    Agg9dzcJPZCzHT13pxg9ntMnPFwzbzyxzg88KGWGPJ7OAj3UGAY9unMaPepcEz2EHDs8NIQJPAUL
    zDvIW/07Q0csPNr5RDzvK4k88YOIPI7EoTyw10I9adncPJ0OKz1y11c9QpqLPc/J0D05tqo9YBlA
    PM+8Dj09RL88l4wAPR6aKz3CTmA9bcSlPc3RhT2beGI8Be0oPYzl2zyZORQ9X/ZHPXuiiD3BgMA9
    oX6aPbWU+DxgWW087q8PPOCOWTz50q48riW2PDnVujzvzMw8OmE1PYtkczyXVxw8YOkVPMdQfzwA
    t688fy/HPLFo1zyLaJk6bVOCO+fizT6XlLo+gNHnPSWCRjzJQRlANv0RPj/WeELN01M9pf6sQ+8t
    iT7dxY5AuqpBPz8WJz1gtzE5vZ6XPT8+TTnih8A93QpdOY8BnD7j8JA86A/dP/SpnD3tmVg9mH5k
    RoHJZUUDXQtGFAlmRlUyoECByWVF4HFMP8ZBxT5SuBc68lEKPom0fkUB7Aw/CHe+PmnvZEYgHGZF
    uHQLRs1yZkYPUKFAIBxmRULU1z+xRcU+lcsXOspPCj5Is35FTCENP1B7vj43ANRGGhjSRdyEgEbC
    mNJGYhQlQRoY0kU6xIY/tF7FPj8xFzqCago+9BuARRDdDD8nAL4+aNttRu5Ub0XFTBBG6lRvRmtc
    pEDuVG9FIlGWPtAtxT6olxc6OFUKPmJnf0VW5ww/V2q+Ps+jaEbgNWpFYP0MRpw2akbkBKBA4DVq
    RYXqsz4VKMU+ZJUXOhhVCj4CgX9FTv0MP9Bvvj4YiGFGkD5jRfSYCEZkP2NGJzOaQJA+Y0VP/9g+
    MSzFPqGKFzpoVwo+SYx/RQT9DD8qcL4+ElULRyVvCEb3YKZGLlUJR9DDaEElbwhGlWP/QGEGxT6J
    5hY6SG8KPtuAgUWwRA8/+iK+Ps0/XUZKs15FhDoFRnG5XkZ3F5dASrNeRRi/sz7QCsU+gIIXOm5V
    Cj5BKIBFjI0NP5SKvj5YF71HOp8oQwoKWkIV2fJCA86fPzj8Pz2AqdRBgijPQb3LBUO4ndJA81gT
    O56BdDp8ji49rB6ZPPcmtD+0LolBB2wMQOw6bUAqTU9AV30CPkf1ljyTo5U8khSUPLOzwztq0S07
    xCkhPPuOXzyr5fA8s7PDO2H3CDs/mVA76cZRO+z0tTu5UyY/neqHPJtEXT2om2I7sic6PoVzFDsL
    WxU8WuRGObU93T+uc4hA6AEyQRgY9j6wZlo/isHOPyoutEEmBiVBhT4YQXOywUCG94xAfsdIQFH7
    3z9nRpA/ZHJXObRWPTi9D4o4B/FBOHu/AjjfJqs3Gm1XN28b7DYd53BBYtXDQL2WiUD1gBFAVRKe
    P0sMJT9cDY8+E2EEPqb6RjqYKQ46MPKsOehTCzlgA1k4zYqRN5y/+jZ5qjk2QeWMQulfgkKRIGpC
    l3kbQ+swEUMQ0BVDwPGDQueaRkNnv8s7hQj+O3IRjzo1EE05IGezOQQQxDnbOZA6qGQ6OXoTa0cy
    XWpGpxECR3oTa0cGSGFBMl1qRgAAAADbEsU+YPwcOkCMCT7XAnpFH1ESP6Zywj5YegRL5lPGRvhU
    xkUnVW5G5lPGRuQv+0D4VMZFBT3FPrGcGDrrMQo+7mp+RWqWDD8V0r4+AAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAF2aeP6wemTuzXrVAAAAAAK+WFz3lbh9BkRjYPgAAAACesXc9lHClP/gVhUA0waA/
    eZP6PQAAAACGk5w+AAAAAAAAAADM+Ig/SrhSPnyOLj0AAAAArB6ZO/Zemj8Xgd8+AAAAAAfXuj4A
    AAAAyRoMPu4Lfj/kvUg/VO7APQ8Nlz8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAJFjHj02EPc9AAAAAPXX3T2yBpo+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHks3PQAAAAAAAAAAAAAAAAAAAACdhGM8
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGJf0C7EYM9uNWVQAAAAACt
    +9U9ajsRQhl0jz0AAAAAcA2vPl3eNT5b2HRABtGBPzdL6D8AAAAAn+oiQQAAAAAAAAAAMuURQcNB
    7j+gAWZAAAAAALWqwj22Q7pBi6vdPwAAAAAQdIo/AAAAAJlKREEgjBZDksy4QQ+GN0BTVVRDAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQSrc9sgqIPgAAAADjtLE/
    p60yQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAFtDBz8AAAAAAAAAAAAAAAAAAAAAGrV0PQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAADZzUk9PEogOTO6uD0AAAAAp4dlOomupTwjkVg9AAAAAKYuSjvBV2U9M5JG
    PXySzzw8GO8+AAAAAFS+mTwAAAAAAAAAADFXQD2wRSg81v2fOwAAAADnPGU6vO5KPcRKAz0AAAAA
    tWvkPAAAAAA7mc48b6lNPip3PD0CfYs8Pzj/PQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAATwF9OtOcUDsAAAAAZkeaPJlOADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADFgcc6AAAAAAAAAAAAAAAAAAAA
    AGAtkzkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxaB0PTxKIDnEWOs9
    AAAAAIFdYDr5Crg95LtpPQAAAACVSRY7irGFPUl7lT5UmrU89yXvPgAAAAD6N6Q8AAAAAAAAAABG
    47o9px4lPNb9nzsAAAAA5zxlOkqSLD1Qo0Q9AAAAAP5vEz0AAAAAjSPpPKsHWz5cdmA9YCCIPIyP
    1D0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACUojjrDTU87AAAA
    AJYBmzxMl+g7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAxYHHOgAAAAAAAAAAAAAAAAAAAABgLZM5AAAAAAAAAAAAAAAAAAAAANOb+Uck
    uRxBQYt2OfpyXjvaqdE67DboOVADp0JJwzo8T6mmQXjKRTokiN5Bu7dXPFZCBz9vQQo6ZVN9QjTT
    hDz38jRAbUgqOkxElUPUJBE9JgYlQZrNEzjJXcpC8jV5PG2nWkDyUzo6A1FOPV8rLDh6DIA9dij1
    N7LYxTeLRCo5BPTxOg1t5TrsYZw2IRqJOsgOCDvQGvg67GP+OQjkjzqKBik6SatcQb6yhjwJH8Q6
    CR/EOgAAAADXSx5GXoqeO8l6X0CZwZU/8RK1PM18tT3MXfI9d4EAPgXDBT518go++NjvQzgGJkVW
    FZVFB8K5RRibwEWKpsVFPGOUOuJmRTu/1/s6OovCOpBL0TqDtL86saduOnaoKTtBqNs6KFZ0Otwc
    djpVoGI6VzIoPqOoDD7hV409P6lHPe8ZUT1qADw9dMO+QWm+AUIucftBhR79QS8I/UFusvxBfV/a
    Qxob60KiE7lBeyI9QXAwK0GkPCdBz4L4QfA4+kACL1ZA1GdYPtRnWD7EDidA0smNRb9zukTqL25C
    pRrNQQWmXEKu9vJBMDyUQeyIX0MTbptDZVAqQ1wEwkLHf4FCvvQCQqOQsEEaC5FBby97QkkIlz9N
    siBCqKMMQdl5OEP44lJDPE7pQwAAAACdbsVCdu5uQo5DiEN2GE9CHP4JQo3JLEOjtbNDf9nyQLt7
    40IAAAAAG3faQlwy4kHNM6hCwjmbQtaWPkODNZRDsZe5QolehUPGO9RD63gtQ+AVd0LqpjNC+JSa
    QztvrUJgfNxBRhtcQRLD6j9cgvxBfSvgQCFAl0B3mF1AbYMgPQEEmz+hUtY/MKDcPdKi70H+dTVC
    UNtGPVLUP0EKIAc9KO29N+GfAT1cIn08CXOPPAXsJjkYG6k9spj0OolvaT+ZXUw+6MSCPONYPUOV
    qRI6itm5QR2kPTx3I9hCd3FlPJXnQ0FZWoY8KwHTQLva3jtKqYlABhmVO+Aj5ULPBUNDs9q3Q0EO
    KkQ2UoJEr/zVRKVgLEWy/n1FK5WzRYB15EcLWVI9DqNSPZJYUD1JO309yKiiPcA3Cz5JhUk+braH
    PgkkwD59RwM/sWKJPmP9N0N61aZC+5ZIP+ItlT0AAAAAzh7APg8lXj/NFM48AAAAAAAAAAAAAAAA
    AAAAAOd6GTvnehk7vO1VPwAAAAAAAAAA10jGPqFHKD/NFM48AAAAAAAAAAAAAAAAAAAAAOd6GTvn
    ehk76s1kPwAAAAAAAAAAlZPZPoZVOT8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOI1cPwAA
    AAAAAAAAlZPZPnsO2D4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99/ZPuItlT0AAAAAAu1D
    Pvz4Wj7NFM48AAAAAAAAAAAAAAAAAAAAAOd6GTvnehk787KhPgAAAAAAAAAAACIwPvnxRz7NFM48
    AAAAAAAAAAAAAAAAAAAAAOd6GTvnehk7vTufPgAAAAAAAAAAAAAAAAAAAACpI+U7R7yaPp95ET5S
    Z4Q8AAAAADFh8jyGk5w+AAAAAAAAAAAAAAAAAAAAAKkj5TtHvJo+vA4LPlJnhDwAAAAAMWHyPDB+
    lz4AAAAAAAAAAAAAAAAAAAAAAAAAANW+hj7PbAk+AAAAAAAAAACsHpk7R5CTPgAAAAAAAAAAAAAA
    AAAAAAAAAAAA1b6GPrx1BD4AAAAAAAAAAKwemTvEu709AAAAAAAAAAAAAAAAAAAAAKkj5TtUxiU9
    eAw+PFJnhDwAAAAAzRTOPM3nuT0AAAAAAAAAAAAAAAAAAAAAqSPlO1TGJT01Zhg8UmeEPAAAAADN
    FM48RGirQIE/NTvblAdAV4IdRJIbKETlmFNEBYuGQFr3Sz+Dlgc/2gO0PqrhCz7K9JQ9MwQkPWR9
    3TwKcIc8yGxKPGiJuzrZIR45C23LOOclKDiQW+03vDZcNx15Kzdf4xY3J0IbN38TFzcwAoQ7qmCG
    QbUGh0CskLc7nGveOWdE20XPAAA+CgpaQnqMdz240XY9top9PccjgD2vVYU9di2KPSyAkj0ldps9
    43enPdoPg0OjY209xOVyPm/Aej3v3Ic/VqOAPRlETECwP4Q95KDJQKLtij2JWq5CBo0SRvebjT+b
    /kNK6AEMQ8jfokQc1+FEZSu5QKBlBUA=
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
hidden_sizes: !!python/tuple
- 1800
- 1800
input_dim: 1613
learning_rate: 1.0e-05
task_type: CLASSIFICATION
