feature_means: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADYzMTQzODI1NnECWAMAAABjcHVxA01NBk50cQRRLoACXXEAWAkAAAA2MzE0Mzgy
    NTZxAWEuTQYAAAAAAACifLVBiumJQbhn+Tx5pUQ+/V8WQnCwHUAHVZtA/V8WQp94pz9ywIhAL32L
    QMxiIT7a1B9AvmsTRBwbk0FMYt9AmAmYQSNSnUFOekBCMQ3mQQAAAAAAAAAAZA74QAPxmkEAAAAA
    AACoQRGpkkCUG/Y/yROdPgAAAACBeCU/4Zt0PkSqLD2h2T88hGlwPw2+00NDsNRDboQaRFCbFUR2
    Gw1EB7oCRM5Q9UMsnttDmjG3Q/saLUODclhDX6anQxmFt0MUmrBD27apQ7R5n0N3LpJDwbqAQy8X
    aEMuUSpDXxeZQwaurEO3brlDEwOwQzHTqEPjiaBDi7CNQ53ur0Sa/bREotMFRW4oEEWmUQtF4CED
    Rdgl+kQES+hEQ/DJRP+Ys0VPia5FxkL/RQo8BkYJSQBGbqbwRTcV5UWfEtRFvfu2RRF8M0Yq6l9G
    gMSiRkNUskYXUaxGkMWlRhWHnka5OpJGEp5/RumqvENzSMlDDu8oRGWNUkRtr11EDMxXRAWUTETy
    IUREr440RGRCm0PrnqlDw9AMRMM7LURIODVE2NgvRJcIJ0QgfB9E9QcSRNBbmUORzqVDemEKRNVx
    KkRErzJEtnMtRMC1JEQnQR1ElgcQRP40nUJxeMJC9R0QQ0RZIkMobh9DfJ8ZQ0QhE0Pd7wlDPCj0
    Qk4q9UWrhuxF4PlORrj2hEbn645G6heMRqFChEa++X9Gn6JuRrofDkGYrgZBab/rQMbLtkBueaNA
    ZfKZQCY3l0A8XItADTt1QGLYZ0DF8YdA+9Z8QPcoXEDVR0lAUN9EQH3nQUCUBTdALp8rQN3jmkA6
    7FZAUSNmQNLLT0BAV1NA1WJMQGG+T0ATh01A76BDQNv670G9t+NBCjTLQeg/r0GfhaFBQaiaQUmD
    mkGJEJVBgpWKQXo49kL019tCDjvCQrO3o0KKWZVCjHaOQgLajUJIdIhC9ZZ7Qs7XcENKsoxD+j92
    Q6r1VkPqdkVDQ3lBQ8fcQUN8zDhDURksQ7wd+0A3qPtATkL8QNtK+kDW1flA+5L4QDrQ+EDVj/dA
    vgz2QKTOzkCYKtRAxXjSQIItzkC5kMxAC8fKQL06y0DmY8lA+NXGQM4wzECJYM9AhbrOQN3DykBj
    m8lAEerHQDtXyEAshsZAvhTEQA4z0z9nSPQ/4+bZP1Jawz8sYbY/fySzP4/hsz9tTK4/NS6lP0vR
    IkM/yhNDyw4aQwJ9HUMrYSBDLPMgQ0ajIEMuRCFDd9QiQ1x+dz+Hqg6/z24gPiSUDb4A3Mo98MlM
    vPVhwb3lHrg9G50+vVYIQ0MoO1dChpPaQcKtx8HzlKrBWM7twedWJMIkpJTBSLsVwQEh7EGz0xtB
    FxJNvwmnpcDb1GnA7/sxwNTVm8Cx4HbAyrUcwOowl0LjJt7ACvCoQbPKy8Dn9WvAmTIHwfJyFcEU
    imI/n18AwPjd8UP4wsJBaNkSQu37RcKCTSvCB+TuwaRmfMJbTMPBhsBXwU8iEkWZz95CfWEzQ+37
    bMNuPEnDMakDwzuSl8PjQvLCFf2Dwn/GEUVYWTdCQCDJQhdUkcM+yovD6jZEQmv0ecN/647DmwA0
    wwH1fkDMKkO+mKpMP/qtH78bcYu+D6sIv+teAL+MSHU+E4m9vBGix0A60wq+E+ukPywSa79KbOq+
    Z9xFv5C5bb+mlSc+sFqovH/81kAHUIe+0Yi/P8IZhL8W1Ou+Xwhcv3x/eL9K530+1ViHvf/JQEG6
    FV6+WrYSP4/byL8Eyau/tNR+PqTWUr+6doi/riORv9qjtkLicyLBHkcDQSigjcET+QLB2ACcvW1f
    LsBXF6m/yL0MwZKApTw53zO8ngfwOozvo7psiG065Ek9uUvVULp3wFc6rLP5uRQdgUCVeYQ/cPae
    PpM7f77xznW+ZJaQvjrdy77EM1S+Uwu7vfMuHT9SFEU+YawKvOkVVb02Ih+9z9r8vEVDTb1YSy+9
    iO+vvI3gxz9l1Q2+SU5yPm4Le72cLhO9KoqZvYN7sL1khSm75Am9vP+cJkF9ldw++YfXPuxi9L6U
    g92+AWeavsm0Ib+Jdn6+t8UbvkZkSkKMiP0/TGkDQMioE8DZvgLADe+qv5arQ8CbPp6/RP8+v5p3
    QUIgRIo/EN18PwHDMcDZcjbAXqVDPv+6D8DL2kDAVhHKv7oCqD0Vn4G7JjcYPO8HuLsLVi27tmih
    u6UEobuGeQQ7qefMuFx+Az6k3Ey7xJd0PF87BbzTgKG7jajru1JHEbzdCZo6QiQJuYFjDT6L3rS7
    Qy2OPMDfFLxYj5+7hEUDvMJCGby9neI6xD4luqQigT5BKw67PSK9O3pde7x9eU28OGkgOsS9Abxe
    bkO8lfohvC7J8j9VVja+0raqPWqIK77LV5S9dL25u3Zk6bwrAP68uyefvRdCCL/G6qw9uvV2vVpe
    JT3hRga87Z0UvZ51IT1o58a8B/qDPjmZlz3ePXq9CHxwvd7ejL2hwsm9zrxmvbkx07zhZKE+7Ilm
    vMh4rL3lzIK9FTNPvbBeqr3HII69jIMMvUZ8sb36Q+Y9quYWvX4uo7zXC1a9njVfvUTWybtRlK68
    t7lIPRe/Qj0IVki9xfVevSZpE71Fr3i9of3xvME3gLyq7EU9MZBGPRxjSL2nsmG9O9sNvU7sdb1Y
    k/i8J4eAvJ71tjwwuqE884VtvZ9Rdb1AMk07+Lc8vSAter2yWwS9yEA3ve2kxT0XWom9O5v8vA1k
    dr2o9XW9qN1xPOinHrzH5KC8L3LMPT1Hgb1E2RS99kZlvcb9i73DVoK6EukRvHJ+E73Y3Nk9hk6G
    vUEMAr3mRW+9dM2MvdFPuDruF0m8U75FvDZUvjy1tn+9N85avWReTju+0/a8mApFvSSILL1bbMO9
    iqILPeEUsL02yhq942o2uxaxwLzJW5K8QLQPvf2gyD+vDHo/GnqOP8hggT+beYM/ejWDP+nbbD9F
    8nc/qPUBP65vVj8uKII/IgGFPwTmhz9p74k/evGCP2avgT9nB0A/XLGTP4rukz8cX4g/mJaGP/G+
    hj8odn8/EEF0P+/yND9oJRs/5PBqPzVRfj/I9II/gSiEP5PYeD8LHYA/A4sxP4emST+wcHk/x5CB
    Pw7Ifz+8KoE/LsuAPygvhj/FKDE/m7NIPx/GeD/AUoE/jfh+Py0RgT8i2oA/wTeGPztHXT8xCmI/
    Ls9/P/rZgT8M7nY/1TGBP1XZhT+RGoY/MT5FPxpZRz9tz4E/jAWCP7BHgj8P7YA/YdtsP0sseT9I
    SDg/nmBAP02ZfT9ecIE/Q6OBP8Wdgj8/H3Q/wIx9P0ziQT/F4EM/7pOAP578gT++eoI/MWmDP+bA
    cj+7Xns/ySN3Pw5ibD/mz4M/MUiCP3AmdT9tMXw/lQOCP8xwhD8lHJc//s2BPz1/iz/GOYM/v0t1
    P7kQfT9SjHY/qx53P0F44T4emuW+wivHQP1yhj9IclxAG6V+PzoN1UDhGIo/afFOQamWtUBRl9dB
    GcQ6QRGmskGQPGVBP01xQJdsG0B9zWdAW94OQLZRbEBTpAtA1KwVQCr6ND+k3XdB22ssQRIsrD/2
    +4JDObMDQ7PTRkNnvIND8FMLQTmzA0OfCtw/cq6nQITJPz4YcCtADs06Q5jCykDua8ZAoQuDQ87B
    A0NP6EZD+82DQ/9mC0HOwQNDC4vbP7qsp0Czxz8+bm8rQBHNOkO2wspA4GvGQFk7qEN7+SZDItJ8
    Qwxcp0MkFjBBe/kmQ67vIMDFjqdAOaM/PqhjK0AlfTtD54jLQMKLxkACfIVDnygGQ+08SkOfHYZD
    O9UNQZ8oBkOAXrM/MamnQFjDPz4UbitAcfk6Q6DzykDec8ZA5EqEQ50FBUP5c0hD0/mEQ8+oDEGd
    BQVDswfDP2Onp0BNwT8+ZW0rQEz+OkO0+MpApXTGQLm0gkNqgANDJhNGQ8Rzg0PaGAtBaoADQ2FR
    1j/JpKdAPb4/PmJsK0AuBTtDbgDLQOJ1xkDhGLxDDVI5Q7QrjEPURbpDB49DQQ1SOUOjUrHAcEKn
    QN1LPz5cRitAv4M8Q9KjzECNt8ZA89aBQw2WAkNbYURDOIuCQ5YmCkENlgJDBN7MP7OVp0BSrT8+
    qWYrQBZHO0NyRstAx4DGQGw0jESh3ExC1tH+QcoN80GGY44/WzhmPSNSnUF3q6ZBLxMkQo0/IkHS
    1jg+DobnPVBxST1bOGY8o9AsQGUFNUHsYhFAvUwAQE19jT+4Z/k9/gjTPJJQOD7hczc+ecp7PIb/
    KDwk1PU9+xHfPuXMKj95yns8QfUSPLbSZj04vhk+adM+PlTaA0CXDI49zw7oPh0O9TwhnWo/I4iQ
    PBKxDD5kg5s7hnWPQL0J40CIpSlB3r/eP/hXEkD+/zRAKxehQd6uXkHAyUtBd/IpQW7EDkEk8ORA
    5kCeQD6sakC3MzM/hNPfPlm+kD5iCzc+HW3pPYPwlT0XYT89Z1j2PJ+4gUFJtxlBxuToQIKppECh
    vWVA+/EYQLbZrz/JuVc/T1UQP4Ihmj4e6iQ+qiuwPSBLOj2IH8Y8BTBRPAe93Ts9zwtCUu0FQr3X
    AEKtOUNCBsY9QhYzQEJWZgdCnvhYQiK9Oz+6GjQ/jV0sP5nhgT/Jnnw/fM1/P3AHNT+LMJA/CQcf
    RHMDn0NcneNDCQcfRHNkq0FzA59DAAAAAKqcqECH5UA+bswrQI26N0OsPcdAxNfFQBPblkVuk7FD
    bpMxQ5MZhUNuk7FD41U8QW6TMUNox6dA2+c/PuJ5K0AB1jpDa8vKQGNtxkAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAABTYpQ/53qZOwPxCkAAAAAAodm/PKLWDkExCs0+AAAAALN/gT31OGM/5Ya9QN2t
    mj+WEiM+AAAAAPwUlz4AAAAAAAAAADT7lz+VGIU+UHFJPQAAAADnepk7Q7P/P/Q71D4AAAAAodm/
    PgAAAAAQrxQ+Z/+CP/JEJz95pcQ9gXglPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAUHFJPfwUFz4AAAAA1dTXPeGbdD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEqiw9AAAAAAAAAAAAAAAAAAAAAKHZ
    PzwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAp/QCQG7UjTxBVcg/AAAA
    APbvHD09wnxBlGfWOwAAAAB/4RQ+yXB7vpjGUkBlfHk/j/AFvwAAAADkKto/AAAAAAAAAAB66F9A
    yQxIP6Ge5T4AAAAApEGsPFzeCkHgEVM/AAAAAAnVKT8AAAAAbSawP22rSEG6fmNAyJ8HP/LWCkEA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+Ulj2zQ14+AAAAAGBi
    wL75ALo/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAA3SQUPgAAAAAAAAAAAAAAAAAAAAAgRsY8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAABb55z9TkWxAa7M4PwAAAAA17s4/kwr2P8YtSj0AAAAAVWkPQLEVTr78
    CGU/wBdUP5zFT8AAAAAABrm5QAAAAAAAAAAA+MhEQHx7QEB25xFBAAAAAL6oj0CGIo9ALxsDQAAA
    AAAFI+g/AAAAAJ4vGEFiP0ZB1yWwQDU8sED+VVlBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAApEcE/zEa8PwAAAAA9s2PA2k3DQAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOCkW0AAAAAAAAAAAAAAAAAA
    AAAAMEkEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYWto/U5FsQBzE
    9D4AAAAAgBLKP9dywD9MnA29AAAAAAhUDkAEkr6+9fzhPTFFOz/Wz0/AAAAAAPjqt0AAAAAAAAAA
    AI6MOECWI0BAducRQQAAAAC+qI9AojiGQIPB+z8AAAAApjDjPwAAAABJwhdBNG5CQRjErEA3na9A
    aEBWQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlPq9P9kcvD8A
    AAAA7MdjwN0jwkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAADgpFtAAAAAAAAAAAAAAAAAAAAAADBJBEAAAAAAAAAAAAAAAAAAAAAA/U49
    RK6RWkFHi/M+G2nnPSXjqz64mzc8+CkgQjUGsz/2L5hBrTYpP/kjqEG61Tw/wy6WPzxEJT1Vy7BB
    oQxAP7Z4v0BvBVQ+rp9TQle75j/erl5BM/H3Pgp09kFnq4Y/BeX9QLzkjT4X3r8+KFdPPJkcOj8S
    qM08ttZpOpb2zTxHWCE/+KhYP3Qt4z7DxA0/f65OPzUGPz4fnJw9SnDhvYmnHz0mQP8/YvicPSBY
    ED9Pwhk+AAAAAO3IYUMtCQA/b9W0QHqc8T9rgNM/jillQCPzkUDstKRAiqmnQBk9qEBNGp9CO7Yt
    Q/tXXkO06HpDxmJ/QzE4gEN8Ypk+aNYlP/LvUj/3BG4/wEtyP7wWcz84448+b6UbP2f8RT84WV8/
    alljP3sZZD/m4XhAGvH6P1Lvej8dwsk+MHiaPkM/kT5pL41BR0UQQv6OL0IStDZCAZ83QkjMN0LC
    RblCBbhPQu9yAEJwz9hBNbzTQcV00kE5765B57AdQdvAqUAcdjE/EakyP0pfwcBnHY9DlSEoQxUv
    ZkGdPtJAZKANQY44lUAtUxJANwCjQV4TKUKZUN9BAX6FQcpZMkG9OnNAiS+LQITAQ0AaOzlBA3+E
    Pk0pd0Gqe8M/BFtfQeaXkkHgUoJCAAAAAE/7VkGPA0JBF9oCQlbP3kCxEI5AIMdtQe/qYUKWkpk/
    vu2CQQAAAAB23lRBdyJwQIz1zUC41yNB8GioQbf110HHxiZBcJO1Qfph50EszL9BnnETQTrPAkHE
    94FBNCqSQYNoAEFW+I9AmOb4PnVJWkHTaB9AD0vxP6jyDz9fdL8+JxknQJopKUCDGGM/BY4+Qd96
    rkEQ5fU/MYIMQd8p1T/loxM+9Se6PlbEnT6wlNA+gXMKPjwVVD/Rjn4+bj+6P/2Elj+T68w+1JJs
    QpmeA0CB43NBVJIHP4eRL0INa8M/JuEWQUonqz7jOmJA2djzPXRm0T9Vy149lRU0QgTubUKYBp1C
    gIHEQsYi1kJn/PdCAvcMQ/wRGUNVWSNDMcqARB6QcECzVoxAh2GfQBGYskBwp8NA1O3MQKs+2kAc
    PudAEevwQLBe+kCfjxBBGh5iQuTH20GWEoNAraBcPQAAAADN/oU/MQ0+QP4I0zwAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAC8VRNAAAAAAAAAAACpsoI/qqygP/4I0zwAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAACEbGFAAAAAAAAAAACi1k4/27YtQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADCN+k/
    AAAAAAAAAACi1k4/ccyBPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACf4hI/raBcPQAAAADh
    m3Q+qbKCPv4I0zwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADXzvU+AAAAAAAAAADBOlo+zAF3Pv4I
    0zwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxDT4/AAAAAAAAAAAAAAAAAAAAAOd6GTwF5QY/lhIj
    PopLhjwAAAAAuGf5PDvaPD8AAAAAAAAAAAAAAAAAAAAA53oZPAXlBj+/Rh4+ikuGPAAAAAC4Z/k8
    JUYhPwAAAAAAAAAAAAAAAAAAAAAAAAAA4Zv0PvwUFz4AAAAAAAAAAOd6mTuqrCA/AAAAAAAAAAAA
    AAAAAAAAAAAAAADhm/Q+EK8UPgAAAAAAAAAA53qZO1s45j0AAAAAAAAAAAAAAAAAAAAA53oZPFBx
    ST2h2T88ikuGPAAAAAD+CNM8hGzhPQAAAAAAAAAAAAAAAAAAAADnehk8UHFJPed6GTyKS4Y8AAAA
    AP4I0zxr55pAwHwWPu3ofkBJm9xCuPenQjuOtEKZA75A+HpOQF97BEBJeNE/Kwl2P/AhID99F9s+
    PYWZPheLSj7h2g8+Pms8PrhElD1uczs9Sq0ePe/3xjxo/YY8tp9OPIOvKTzUAAQ8LnrQO6SO1j7I
    Fm5BBuL1QBQSbz+G2/Y+YTepQ2GJvkDW0f5B3XmgQALcu0AbMdhACSn0QN9UCEG2cBZBfbwkQanq
    MkHhPUFBC1wJQ/6ZhEDI7sk9XySvQCIgEECq3d9AuBSHQASvCUEEG8BAfCskQdWemULv2shDeQwH
    QZ+VKEUC9zRCP8UZQ6+UNUM/GQlBUrvIQA==
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
feature_vars: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADYzMTIyNDY0MHECWAMAAABjcHVxA01NBk50cQRRLoACXXEAWAkAAAA2MzEyMjQ2
    NDBxAWEuTQYAAAAAAADqgNRBMsAcQTFh8jxJt0U+iJyNQpkmNzvafgk8iJyNQtDJeDruFF89WFsg
    PpgvWDryi8g9vfUBST2LxENecZI/E8vLQU/z2kE8OhFDynMpQgAAAAAAAAAAi+u7QE6fHkIAAAAA
    bA68QQx0NUDIHfQ/0DedPgAAAAAWJ64/Xv+WPlTGJT14DD48l3DJP3LiVkYMSCFGaHvcRink6UbB
    Eg5Hu00LR3x7D0edlxhHPOYXR5jOx0TU7B5FN1XPRQ98G0YoESlG//E6RlW9REZP1FpGN0pjRhDm
    C0YmE75EMbsyRoiOJkZl4YlGF0uCRpqgc0Zcf4ZGKJNzRtJYg0hZaflHy7CKSDWLwEgd+9xI+2ni
    SOAR9Ug3UwVJqDAHSfHzy0okqepJMHOBSimsrkqEuchKgvXJShw/2ko2I+1KgUnxSn5cykoFXCRL
    9zG1S4mrA0yb2BNMDJIkTCJ6OExbl0dMgppMTP5WCkYRwxlGHuMERylFckdHWJ5H6mCmRzLNokcg
    0bpHXsW9R4CquUVc79dFmwG1RlVgIEdvi05HtL1ZR3+wV0econRHA414R+KbuEV+jM9FU8ixRiJb
    HUf9PEtHuVxWR4ZvU0d5a29Hq9pyR2O3oUPcegBEZ9KSRGsy4kQs3gFFOZUNRcIwHkUsfDFFd+wz
    RV3ieUpVPlpKDltbS0OI1Evy7A9MHpgUTBBSDkx+gydMt1YpTP68GEB3LLQ/ryUGQHVUvj/PysU/
    ra/cPx0f0z8gU+M/Whr1P5RqeT36F4k9MG+bPdeMlz0l7rg9n9rLPclBxj0QP/I9krEVPgL/JkAX
    O9s9xr1NPzl5iz6BD98+Th7RPvHj+D6nJwk/pnP7Pq9pHkPJFCxBezRzQUaSh0H4GaxBQ6aoQVJc
    lEH+1rpBDczjQWaRi0Wrw0hDquKPQ5BLmkNaw8lDydrFQzRmpUPzINFDJswFROvfskNWE4lD0dvt
    Q3330UNOBfZDqxMNRIDuF0TE0SZEQAQ9ROrPgz3CO4s85vsdPSAfDz1H60c9eQdRPdmscj18bn89
    yN1kPS15qz0VpKI8UxZFPXUYLz17Kng921qDPe52kD3HnaE9u96ZPYDlvj23lbk84idgPRpeMj0y
    o4A9Yd2IPb7dlj1A2589IKGVPaP4Bj1Fdo08Js3RPJVcpTwMdcY8karGPBDz1jzgmeQ8Gq/8PAD9
    jUFQzC5ByyDJQXVdjUHHNa9Bg6WjQXDw2UHkHr1BFlTOQZvlAD64AYE9q1GfPaJAij19ra49EIq8
    Pdchqz3kg6E9wpqTPezUSkUTTRlE4uuQRJJ29ETs4f9EilxVRepDPEXEWmRFlOcKRWpkd0Jra4tB
    PgSqQWP88kElSwNCP7oSQh4XPUJ/BTNCIYXsQej4GEWM4z5CG6eURLOohENljTRER3u3Q4NPCUTH
    LSFEu+KPQ3sF2UfXWXdE9c5SRaZwJEZtODNGjP4uRt9dYkZtbYFG3hckRh2gVUoTF5FG86uQR6/g
    b0jzfX1I5FV0SKHSp0iGtLdIZfdnSHnbtUjVrwhGr7EKSA1+JUiVHVtIsKw+SPRegUgoz6dIk8pH
    SDxUfkDKqog9+rsAQC35cz+nQr0/i/GYP6SUqT+wHtw/8FSFP3fFAUF8Kek9FrGBQGvbB0DZyVRA
    JoROQDhkZUBYD4dAB9klQDKFMkEDoBY+iq+3QIIaLUBzyIZAqZZrQLLviUDwVKJAerpDQBOXVEGX
    HWo/YcuOQNI3mECGFsFAAJ26QLpR5kB3+9lAEsm5QEF0i0Q/uiVDYmcQRJPCs0MGyshDW625Q6od
    5kMugwFE+50AREW/CjgzgqY3k6MtNwKXuDaChek26UMPNx7XETfCuhk36wwiN6x3aj4sXws+Wm8U
    PuRKKD6PRkw+FtuDPj8Cmz6EjP0+CQzDPoGdejsjLKg736RLO78BQzuScmg72FKAO4BuoTuactQ7
    znu4O2iMYz8PUZA80vQZPkHIqTzaOUs96GPTPERcbz33JJI9h1grPa/8nELNPpU+pN/fPpoGkT8B
    opc/GVSdP93ZGEAQXCVA6pv9P2A7IEX+yK1AzIMZQUme3kGO4NhBILrhQbhhaELEbnJCVcg2QqaC
    zEAuQYRA51OiQRV1f0GO8ZhBvP2cQd7g2kHf5UlCSLoaQksjnzrPiv83Bj6GOaJNljhtq+o47Si6
    OG7oHDkbrUo5b6swOT8pDTugOm0418EFOjiHLzn+/4c5VLyAOZ+ZzDlyXwE65a3YOXnITzvurpQ4
    T58+OsT4WjnUR6o5nqiROScV9zlELRo6G1r7Of+shzu7XcM5iG8jOkoY9TmzkR06SZkqOtsvXTrv
    0YE6gA2EOrVRgT6mMYA9uLClPX0q9Tyu2/48aucPPRDvPz3MmHU9CuKEPbVxaTxK8Ks861JFPEO8
    bTw52Ig8coGLPKAPjzxFvKQ8ncoFPP1IBjwpix485ktEPJgTdTyQpI08h4DzPB7ztjysXlY8BvMJ
    PF7Z9TvpcRs8V3UuPAP5WDzBl488Qp9uPEZduzs+Ooc83HvxO5QqWjyYxxk81ydQPLJtuDxGLpA8
    YXIuO48Jqjv6S+07N8wcPKd9OTzpzE88ESPxPFzcpDyHjhk7Q7SpO6Yr6TvggBs8V5k2PO3RTjzp
    HPE8QFGlPCYR7ToAnxE8SwLfO6UIBjzVJBA8qXk+PDSWxDx3bIw8g/WcO44FlzyZwws8PlFjPP3C
    SDxjG308qbTAPCqeqjzTkGk7rT1zPEXhFDw8NmI8NKZpPK2fjTwwGt08qz7APOMQezt2JIw8LzIZ
    PEqsbTwj/V48ExmQPJtk1jyHWrs8YvbNOzrTKjzGHPA7RBQGPOmlIjz6ikY8wv+ZPNnTezzROJ48
    n955PBax1jsf/wM8P5AhPCDMPjzUgXA8rI1+PB4izzyihU49sB7lPM/lET0i0CA9+aJEPXgaWz2x
    7W099FCaO5I7bTxHxzg8u9xzPLyErjxneuc86nocPT5x7jx4cn8836uGPGYFVzyfLpg8i2ypPPHB
    yTy/HuU8S0MFPWMQBD2JWNI8e1v7PN6NeT1JrbY9IuTwPXIbFD7vXSE+3rAhPCvcdjz59yk8eRaQ
    PKuSAj2lSgw9KrkUPby2Fz2SkCM8VatqPP40ITx634c8Vpz6PJCbCD2cphE9J54RPT22PDz2Mv87
    u6LMO+rGAjyrtyk8sbY3PAAjjTzkkGg8ac+iPN+QUT1Fk+s8oRorPdMZXz0too8904e/PfFlvj3p
    +kQ8NTcYPUeNyTxXxAE9UI8vPSvdbD0UlpU9BXuQPSapaDwS8TM9gVXoPNVYFz1O6Us9hzOOPQNh
    rj2DbqY9lez4PEG1XTwt+xU85/JfPGxIrDyBdqY8LyK+PCgMuDxuPTQ9NQV+PC+TLDzaHRc8kqF+
    POUlqzzwJM08OTLGPNL8nDrE84U7DMTCPr2/vT7Cz+49tAFcPLUFGUDs9w4+KeZfQsCpUz2ZH5pD
    rSaJPqyuhUByqz0/7X8gPSfqFznca5Q98RUyOXNUvD16dDw5YXWRPue2izxjj94/39igPQFYTT2I
    CVpG4ENbRXhMBUaqdVtG+rmZQOBDW0VML0Q/nmm6Pn0hDjpzKwI+jIxxRfofBT8ONbM+IXVaRtWR
    W0XoYQVGitpbRvjSmkDVkVtF6g3UP3Vvuj5fMw46vSkCPoGJcUUJUgU/mjizPvaozEYDxspFlZR4
    Rp1Jy0aMcyFBA8bKRf4Yiz/VnLo+XG4NOl1NAj5MGnNF5wwFPyKvsj5Bw2FG7StjRSiCCUZGLWNG
    RYecQO0rY0WTFpU+NVm6Pi4IDjrdLQI+sANyRf3rBD9VILM+GIdcRkQKXkVtOgZGPwxeRvAjmEBE
    Cl5FYHi1PlJUuj7vCA46XC0CPs8RckXt+AQ/MiWzPj97VUYYJFdF3+cBRjwmV0YgTpJAGCRXRWre
    3D5BWLo+ggIOOvsuAj6oEnJFyvAEP0olsz4ABQhHBCEFRpBSoka7CQZHdJRmQQQhBUb7EgdB0DS6
    Pn8eDTpTUQI+Tjp2RSPjBz8O4LI+andRRrrjUkXre/1Fb+pSRm6Lj0C641JFqQG8Pkwsuj79Bg46
    zCkCPifSckWjiAU/eUSzPiuBs0ewdCBD/8FOQv+n60INnZQ/WcpZPU/z2kEOT89BQt4AQ5WjzUCC
    Ww47kJeBOjj8Pz2pI+U82CaoPxFJj0E4yAVAjMNpQI0lRUD6i9s9zRTOPJQ5lzx3n5Q8/mOgO4+4
    HjtF8Rg84a5hPMFq/Tz+Y6A7vuLqOrjvTTsxxl47ifTBO9w9HT9eb4g85s9iPSA+eDtnUCM+P9IM
    OxOrGDy0YE05PIXUP7+ogkCyKidBXATuPodeUj+VQ8U/rtOpQYbJHEGwNg9B5vK4QLRIh0DXyj5A
    5cfSPxWEhz80/0o5p5Y0OPwIizgDxzs4H4n4N4FxpDe47FE3GJTkNmqIYEGIyrFAk1x1QJ09CEDX
    +pM/yCcYP2F8hT7U7fQ9LZdDOpp8BzriFqk5jo8QOZPGZTiEmp03D5IIN5p0Rjb+N4NC28xyQqxx
    XEI02BNDWRcKQ+6gDkPmtHdCS7k9Q8V7yzspLvw73xuVOhMkWDkD2r852GHTOf+5lTq0NEU5QXtj
    RzhqY0br1/5GQXtjR6NYWUE4amNGAAAAAK84uj6A8RI6rHUBPgMObUUzqAk/2sO2Pmn7/0r+6rxG
    /uq8RXCqY0b+6rxGm0rxQP7qvEWyXLo+NuwOOvENAj45MXFFGIkEPwZysz4AAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAADFmZ8/rB6ZO0lBqkAAAAAAr5YXPS31IkEkj9Y+AAAAALJwlj3mPKQ/JsqDQCH8
    nz9BChM+AAAAAMhwpD4AAAAAAAAAAMq4iz9wEk8+OPw/PQAAAACsHpk7ULuUP7Dk1z4AAAAA/oKj
    PgAAAADj0A0+/2plP5QnVT/NQeI9FieuPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAHDdTPanmBT4AAAAAaifLPV7/lj4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUxiU9AAAAAAAAAAAAAAAAAAAAAHgM
    PjwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoFKBQLsRgz0ocIVAAAAA
    AK371T0d1hNCbxJMPQAAAADxw90+1085Pk1/ckD9GYM/LiUMQAAAAABV+ytBAAAAAAAAAAAX/RRB
    0pvrP8jLeUAAAAAAtarCPbvSskEe0NA/AAAAAKVYfD8AAAAANtRFQY08BkOY1sRBXhhbQEfFckMA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMb87z33FZM+AAAAAEL7
    pD/erS5BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAQ930PgAAAAAAAAAAAAAAAAAAAAAWI0w9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAJkWSz08SiA5/y+uPQAAAACnh2U63/ibPFgVAj0AAAAA/O2NO5zjcj3j
    jj09Q8rSPI6uCT8AAAAA2mqhPAAAAAAAAAAA2AdKPQ9cHDybRbE7AAAAAOc8ZTrWEkI9EWcPPQAA
    AACBUNE8AAAAAFqQ1TwS80c+iONNPaBEtzzOU/49AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAADEIRs7BtplOwAAAACmB4o8LdMHPAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFtezDoAAAAAAAAAAAAAAAAA
    AAAAC/qSOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtzVk9PEogOQso
    3j0AAAAAgV1gOulJxT0EmRA9AAAAAF5zUDtRKYc9E82bPuhFszwLvwk/AAAAAH6MrDwAAAAAAAAA
    ADBJwT1uMxk8m0WxOwAAAADnPGU6MVMvPWtTRj0AAAAA4TD9PAAAAACwlu48yWVuPugQcj1RQrM8
    i8rPPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsfweOw9/ZDsA
    AAAAHbSKPPCW+TsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAABbXsw6AAAAAAAAAAAAAAAAAAAAAAv6kjkAAAAAAAAAAAAAAAAAAAAAGRLu
    R7XPEkGWSX05Cc9OO5wU0TpF9+Q5yNqhQqZmOjwos59BefQ1OrFO3UFjrVk8qjYFP/orBTr3mGxC
    bY59PNAVKUCD+iU63/iLQ93sBD2GyRxB+WkNONbIwUIMtXE8bhNYQMMMNDo6fEI9QgQlOPAPcD1B
    Mu03/3XLNyhvLjmqsgA7pd/sOkFtkzY4HJA65UAOO/bMAzvDewU6YgeXOhC8KzojMWVBV9mHPPeJ
    zDr1icw6AAAAAD6fGEYag5k7MMpYQO/RmD/Leq88g12qPQUl3j02Suo921bzPZeh/j2aROBDNKsc
    RZH/jEVGGbBFpii2RaxXu0VIc5Q6RxtCO7+O8TphK7Q6ibvAOuBlrzq93W06zdAmOw/P1Dp9Tl06
    4u9aOmvORjrekyQ+S58KPuLXiT1i6j09FotGPRqrMT2jNbNB8e3xQWjM7EFb5/BB3rPwQfSz8EEe
    Wc9DEmPqQiJxukE7a0FBfHIwQZmaJkHXnupBVqnwQOw3TUAqSVo+1GdYPgVuJECLm4RFau6uRDPC
    cUK6MMFBhB9SQqy6CkLBvqBBJbZRQy4QiUOD7SpDAQe/Qk+ZfULQJ/JBQD+5QWDqi0Gyu3hCuhym
    PyyHGEJ/LwxBUSYvQyz/UEOOauxDAAAAALwAwELDOHVCR3iDQy1zRULLKglCyFQeQ2Wpt0MOE+5A
    xAbcQgAAAAAxE99Cyw7sQXYZqUJXF4ZCT4Y9Q8OQkkPIBr1CWwp+Q61q2ENZoCVDxXx5QsOEMkKJ
    mqRDMUyuQsy91kESkWlBwxD/P8osAEL35eFAa22UQLkwVEAI5R89NcKWPwQyxz8fn/I9kA/iQRxu
    KUKmXoA9DTw4QbSyJT1TIS04mi7MPFIpcTwmH6E8d7wvOSMssD3rXac64j9tPx9MNj7m4F48d8kz
    Q73bCjq75bJBZO83PKZbzUITmmE8KoZBQZ+5gTy0oc5AboTdO9nmlUCGEp47XPfXQqq6OUOxOK5D
    cBUfROHOcUTK6MZEVOYhReBRb0Vrn6tFv+PWR6aMRT3u3kY9CmpIPVdscz0I3pw9HYUEPiCMQT4L
    jYI+PqG5PoAI/T7OmoQ+D7UsQwtSoEJ98EA/nrF3PQAAAABr+8M+k+lfP80UzjwAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAACmU0Y/AAAAAAAAAACu48o+zpAmP80UzjwAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAACcsGo/AAAAAAAAAAAUc90+GWRDPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFBFU/
    AAAAAAAAAAAUc90+mDzYPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABRctY+nrF3PQAAAACN
    CUk+QltWPs0UzjwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsv6E+AAAAAAAAAABdvTU+wnpFPs0U
    zjwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC91ps+AAAAAAAAAAAAAAAAAAAAADVmGDxTLZ8+z2wJ
    PlJnhDwAAAAAMWHyPM6Wmj4AAAAAAAAAAAAAAAAAAAAANWYYPFMtnz5PIAY+UmeEPAAAAAAxYfI8
    vnmUPgAAAAAAAAAAAAAAAAAAAAAAAAAA+UGHPvAXAT4AAAAAAAAAAKwemTukYZI+AAAAAAAAAAAA
    AAAAAAAAAAAAAAD5QYc+cMn+PQAAAAAAAAAArB6ZO/3RzD0AAAAAAAAAAAAAAAAAAAAANWYYPDj8
    Pz14DD48UmeEPAAAAADNFM48FBXJPQAAAAAAAAAAAAAAAAAAAAA1Zhg8OPw/PTVmGDxSZ4Q8AAAA
    AM0UzjzR1qBAtrUkO6EICEBliBRETB4qRCvWU0TK6IBAD4FGPyonAj9/rJ4+2c71PVRJfj2DGxM9
    sN3KPNv/cTwXLEU8f1K3OofVITmxtcs4a0gfOOhR7De6FGE3MiUeN9VACDcKZBA36YYTN9n8fTsz
    mIFB3uCCQEvGrzulotM56PXLRYDb8D3/wU5CFHBoPattZz3odW09Ws5vPdVmeT3vMYE9SQWJPWN4
    kT3Y35w9I6V3Q7thXz1ilkI+g1JrPbDVgT/qO3E9zLFGQMw3eD3Ki8RAQ5iCPZHaoULSfQhGQ5aM
    Py1hOUqmYgRDwNiZRBNQ1UTEKKtA9BX+Pw==
- 0
- !!python/tuple
  - 1613
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
hidden_sizes: !!python/tuple
- 1800
- 1800
input_dim: 1613
learning_rate: 1.0e-05
task_type: CLASSIFICATION
